'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { getCategoriesForOutlet, getDepartmentForCategory } from '@/lib/categories';
import { PRINTERS_BY_GROUP, OUTLETS_BY_GROUP, OutletGroup } from '@/lib/outlets';
import { Combobox } from '@/components/ui/combobox';
import { Checkbox } from '@/components/ui/checkbox';
import { MultiSelect } from '@/components/ui/multi-select';
import { toast } from 'sonner';
import { Loader2, Plus, Trash2, Copy } from 'lucide-react';
import { SuccessModal } from '@/components/SuccessModal';
import { suggestPLUCode, assemblePLUCode } from '@/lib/pluCode';

const REQUEST_TYPES = [
  { value: 'NEW_ITEM', label: 'New Item' },
  { value: 'UPDATE_PRICE', label: 'Update Price' },
  { value: 'UPDATE_NAME', label: 'Update Name' },
  { value: 'UPDATE_PRINTER', label: 'Change Printer' },
  { value: 'UPDATE_FULL', label: 'Other Update' },
] as const;

type RequestTypeValue = (typeof REQUEST_TYPES)[number]['value'];

interface ItemRow {
  _id: string;
  code: string;
  codeIsAutoGenerated: boolean;
  codeLoading: boolean;
  name: string;
  category: string;
  department: string;
  price: string;
  folder: string;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  printers: string[];
  outlets: string[];
  errors: Partial<Record<string, string>>;
}

const POS_FIELDS: { key: keyof ItemRow; abbr: string; full: string }[] = [
  { key: 'serviceCharge', abbr: 'SC', full: 'Service Charge' },
  { key: 'tax1', abbr: 'T1', full: 'Tax 1' },
  { key: 'tax2', abbr: 'T2', full: 'Tax 2' },
  { key: 'noDiscount', abbr: 'ND', full: 'No Discount' },
  { key: 'hideReceipt', abbr: 'HR', full: 'Hide on Receipt' },
];

function uid() { return Math.random().toString(36).slice(2, 10); }

function makeDefaultRow(): ItemRow {
  return {
    _id: uid(), code: '', codeIsAutoGenerated: true, codeLoading: false, name: '', category: '', department: '',
    price: '', folder: '',
    serviceCharge: true, tax1: true, tax2: true, noDiscount: true, hideReceipt: false,
    printers: [], outlets: [], errors: {},
  };
}

const INPUT_STYLE: React.CSSProperties = {
  width: '100%', height: '34px', border: '1px solid var(--input-border)',
  borderRadius: '4px', background: 'var(--bg-card)', color: 'var(--text-primary)',
  padding: '0 0.625rem', fontSize: '0.8rem', outline: 'none', boxSizing: 'border-box',
};

export default function BatchNewPage() {
  const { data: session } = useSession();
  const router = useRouter();
  const sessionUser = session?.user as any;
  const outlet = sessionUser?.outlet ?? 'ROMSCBD';
  const outletGroup = (sessionUser?.outletGroup as OutletGroup) ?? 'IBR';

  const categories = getCategoriesForOutlet(outlet);
  const availablePrinters = PRINTERS_BY_GROUP[outletGroup] ?? [];
  const availableOutlets = OUTLETS_BY_GROUP[outletGroup] ?? [];
  const categoryOptions = categories.map((c) => ({ value: c.category, label: c.category, group: c.department }));

  const [title, setTitle] = useState('');
  const [requestType, setRequestType] = useState<RequestTypeValue>('NEW_ITEM');
  const [items, setItems] = useState<ItemRow[]>([makeDefaultRow()]);
  const [loading, setLoading] = useState(false);
  const [successModal, setSuccessModal] = useState({ open: false, title: '', count: 0 });
  const [titleError, setTitleError] = useState('');

  // Sequence management for auto-generated PLU codes
  const seqBaseCache = useRef<Record<string, number>>({});
  const seqOffsetMap = useRef<Record<string, number>>({});
  const seqFetchPromises = useRef<Record<string, Promise<number>>>({});
  const processingRef = useRef<Set<string>>(new Set());

  // Async effect: assign real sequences to rows that need them
  useEffect(() => {
    const loadingRows = items.filter(
      (r) => r.codeLoading && r.codeIsAutoGenerated && r.category && !processingRef.current.has(r._id)
    );
    if (loadingRows.length === 0) return;

    for (const row of loadingRows) {
      const rowId = row._id;
      const rowCategory = row.category;
      const rowOutlets = row.outlets;
      processingRef.current.add(rowId);

      const s = suggestPLUCode(rowCategory, outlet, rowOutlets, 4000);
      if (!s) {
        processingRef.current.delete(rowId);
        setItems((prev) => prev.map((r) => r._id === rowId ? { ...r, codeLoading: false, code: '' } : r));
        continue;
      }

      const { prefix, deptCode, catCode } = s;
      const key = `${prefix}${deptCode}${catCode}`;

      (async () => {
        try {
          if (seqBaseCache.current[key] == null) {
            if (!seqFetchPromises.current[key]) {
              seqFetchPromises.current[key] = fetch(
                `/api/plu/next-sequence?prefix=${encodeURIComponent(prefix)}&deptCode=${encodeURIComponent(deptCode)}&catCode=${encodeURIComponent(catCode)}`
              )
                .then((res) => res.json())
                .then((data) => {
                  const seq = typeof data.sequence === 'number' ? data.sequence : 4000;
                  seqBaseCache.current[key] = seq;
                  if (seqOffsetMap.current[key] == null) seqOffsetMap.current[key] = 0;
                  return seq;
                })
                .catch(() => {
                  seqBaseCache.current[key] = 4000;
                  if (seqOffsetMap.current[key] == null) seqOffsetMap.current[key] = 0;
                  return 4000;
                });
            }
            await seqFetchPromises.current[key];
          }

          const base = seqBaseCache.current[key];
          const offset = seqOffsetMap.current[key] ?? 0;
          seqOffsetMap.current[key] = offset + 1;
          const code = assemblePLUCode(prefix, deptCode, catCode, base + offset);

          setItems((prev) => prev.map((r) => {
            if (r._id !== rowId) return r;
            if (!r.codeIsAutoGenerated || !r.codeLoading) return r;
            return { ...r, code, codeLoading: false };
          }));
        } finally {
          processingRef.current.delete(rowId);
        }
      })();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items]);

  const isUpdate = requestType !== 'NEW_ITEM';
  const needsPrice = requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRICE';
  const showCategoryCol = requestType === 'NEW_ITEM' || requestType === 'UPDATE_FULL';

  const addRow = useCallback(() => {
    setItems((prev) => {
      const last = prev[prev.length - 1];
      const hasCategory = Boolean(last.category);
      const newRow: ItemRow = {
        ...last, _id: uid(), code: '', codeIsAutoGenerated: true,
        codeLoading: hasCategory, name: '', errors: {},
      };
      return [...prev, newRow];
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [outlet]);

  function duplicateRow(idx: number) {
    setItems((prev) => {
      const src = prev[idx];
      const copy: ItemRow = { ...src, _id: uid(), name: '', errors: {} };
      if (copy.codeIsAutoGenerated && copy.category) {
        copy.code = '';
        copy.codeLoading = true;
      }
      const next = [...prev];
      next.splice(idx + 1, 0, copy);
      return next;
    });
  }

  function deleteRow(idx: number) {
    if (items.length <= 1) { toast.error('Cannot remove the last item'); return; }
    setItems((prev) => prev.filter((_, i) => i !== idx));
  }

  function updateRow(idx: number, key: keyof ItemRow, value: any) {
    setItems((prev) => prev.map((row, i) => {
      if (i !== idx) return row;
      const updated = { ...row, [key]: value, errors: { ...row.errors, [key]: undefined } };
      if (key === 'category') updated.department = getDepartmentForCategory(value as string);
      // When category or outlets change on an auto-generated row, trigger async re-gen
      if ((key === 'category' || key === 'outlets') && updated.codeIsAutoGenerated) {
        const cat = key === 'category' ? (value as string) : updated.category;
        if (cat) {
          updated.code = '';
          updated.codeLoading = true;
        }
      }
      return updated;
    }));
  }

  function updateRowCode(idx: number, code: string) {
    setItems((prev) => prev.map((row, i) => {
      if (i !== idx) return row;
      return { ...row, code, codeIsAutoGenerated: false, errors: { ...row.errors, code: undefined } };
    }));
  }

  function validate(): boolean {
    let valid = true;
    if (!title.trim()) { setTitleError('Batch title is required'); valid = false; }
    const updatedItems = items.map((row) => {
      const errors: Record<string, string> = {};
      if (!row.name.trim()) errors.name = 'Name required';
      if (isUpdate && !row.code.trim()) errors.code = 'Code required';
      if (needsPrice && (!row.price || Number(row.price) <= 0)) errors.price = 'Price required';
      if (row.printers.length === 0) errors.printers = 'Select printer';
      if (row.outlets.length === 0) errors.outlets = 'Select outlet';
      if (Object.keys(errors).length > 0) valid = false;
      return { ...row, errors };
    });
    setItems(updatedItems);
    return valid;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) { toast.error('Please fix the errors before submitting'); return; }
    setLoading(true);
    try {
      const payload = {
        title: title.trim(),
        requestType,
        items: items.map((row) => ({
          code: row.code || undefined,
          codeIsAutoGenerated: row.codeIsAutoGenerated,
          name: row.name.trim(),
          category: row.category,
          department: row.department,
          price: row.price ? Number(row.price) : undefined,
          folder: row.folder || undefined,
          serviceCharge: row.serviceCharge,
          tax1: row.tax1,
          tax2: row.tax2,
          noDiscount: row.noDiscount,
          hideReceipt: row.hideReceipt,
          printers: row.printers,
          outlets: row.outlets,
        })),
      };
      const res = await fetch('/api/batches', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? 'Submission failed');
      }
      setSuccessModal({ open: true, title: title.trim(), count: items.length });
      setTitle('');
      setItems([makeDefaultRow()]);
    } catch (err: any) {
      toast.error(err.message ?? 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <SuccessModal
        isOpen={successModal.open}
        itemName={`${successModal.count} item${successModal.count !== 1 ? 's' : ''} submitted under "${successModal.title}"`}
        title="Batch Submitted"
        body="Your batch request has been received and is pending review."
        submitAnotherLabel="Submit Another Batch"
        onSubmitAnother={() => setSuccessModal({ open: false, title: '', count: 0 })}
        onViewRequests={() => { setSuccessModal({ open: false, title: '', count: 0 }); router.push('/cashier/dashboard'); }}
      />

      <h1 className="page-title" style={{ marginBottom: '0.375rem' }}>New Batch Request</h1>
      <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '1.75rem' }}>
        Submit multiple items in one batch. Group them by event or request context.
      </p>

      <form onSubmit={handleSubmit}>

        {/* Batch Header */}
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div>
              <label className="label-caps" style={{ display: 'block', marginBottom: '0.4rem' }}>Request Title</label>
              <input
                type="text"
                value={title}
                onChange={(e) => { setTitle(e.target.value); setTitleError(''); }}
                placeholder="e.g. New Request Item - Event WTT CORK"
                required
                style={{ ...INPUT_STYLE, height: '48px', fontSize: '1rem', borderColor: titleError ? 'rgba(122,46,31,0.5)' : undefined }}
              />
              {titleError && <p style={{ fontSize: '0.75rem', color: '#8B3A2A', marginTop: '0.3rem' }}>{titleError}</p>}
              <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.3rem' }}>
                Give this batch a name that describes what you're adding or updating.
              </p>
            </div>

            <div>
              <div className="label-caps" style={{ marginBottom: '0.75rem' }}>Request Type</div>
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {REQUEST_TYPES.map((t) => (
                  <button key={t.value} type="button" onClick={() => setRequestType(t.value)}
                    style={{ padding: '0.5rem 1rem', borderRadius: '0.375rem', border: `1px solid ${requestType === t.value ? 'var(--bg-dark)' : 'var(--border)'}`, background: requestType === t.value ? 'var(--bg-dark)' : 'transparent', color: requestType === t.value ? 'var(--accent-gold)' : 'var(--text-secondary)', fontSize: '0.8rem', fontWeight: requestType === t.value ? 500 : 400, cursor: 'pointer', transition: 'all 200ms ease' }}
                  >
                    {t.label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Items Table */}
        <div className="card" style={{ marginBottom: '1rem', overflow: 'hidden' }}>
          <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem' }}>
              <span className="section-title">Items</span>
              <span style={{ background: 'var(--bg-dark)', color: 'var(--accent-gold)', fontSize: '0.7rem', fontWeight: 600, padding: '0.1rem 0.5rem', borderRadius: '9999px' }}>
                {items.length}
              </span>
              <span style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', fontStyle: 'italic' }}>
                ← scroll right for printers, outlets & POS settings
              </span>
            </div>
            <button
              type="button"
              onClick={addRow}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '0.375rem', padding: '0.375rem 0.875rem', background: 'transparent', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.8rem', color: 'var(--text-secondary)', cursor: 'pointer', flexShrink: 0 }}
            >
              <Plus size={13} /> Add Row
            </button>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ tableLayout: 'auto', minWidth: '900px' }}>
              <thead>
                <tr>
                  <th style={{ width: '36px', textAlign: 'center' }}>#</th>
                  {(isUpdate || requestType === 'NEW_ITEM') && <th style={{ minWidth: '160px' }}>Code</th>}
                  <th style={{ minWidth: '180px' }}>Name</th>
                  {showCategoryCol && <th style={{ minWidth: '160px' }}>Category</th>}
                  {showCategoryCol && <th style={{ minWidth: '90px' }}>Dept</th>}
                  {needsPrice && <th style={{ minWidth: '105px' }}>Price (IDR)</th>}
                  {showCategoryCol && <th style={{ minWidth: '120px' }}>Folder</th>}
                  <th style={{ minWidth: '155px' }}>Printers</th>
                  <th style={{ minWidth: '140px' }}>Outlets</th>
                  <th style={{ minWidth: '72px' }}>POS</th>
                  <th style={{ width: '66px' }}></th>
                </tr>
              </thead>
              <tbody>
                {items.map((row, idx) => {
                  const hasError = Object.keys(row.errors).length > 0;
                  return (
                    <tr key={row._id} style={{ borderLeft: hasError ? '2px solid rgba(122,46,31,0.6)' : undefined, verticalAlign: 'top' }}>
                      <td style={{ textAlign: 'center', fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 600, paddingTop: '0.6rem' }}>{idx + 1}</td>

                      {isUpdate && (
                        <td>
                          <input type="text" value={row.code} onChange={(e) => updateRow(idx, 'code', e.target.value)} placeholder="PLU code"
                            style={{ ...INPUT_STYLE, borderColor: row.errors.code ? 'rgba(122,46,31,0.5)' : undefined }} />
                          {row.errors.code && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.code}</p>}
                        </td>
                      )}

                      {requestType === 'NEW_ITEM' && (
                        <td>
                          {row.codeLoading ? (
                            <input
                              type="text"
                              value="…"
                              readOnly
                              style={{
                                ...INPUT_STYLE,
                                fontFamily: 'monospace',
                                fontSize: '0.72rem',
                                background: '#1A1008',
                                color: 'rgba(201,168,76,0.35)',
                              }}
                            />
                          ) : (
                            <div style={{ position: 'relative' }}>
                              <input
                                type="text"
                                value={row.code}
                                onChange={(e) => updateRowCode(idx, e.target.value.toUpperCase())}
                                placeholder={row.category ? 'Select category first' : '—'}
                                maxLength={16}
                                style={{
                                  ...INPUT_STYLE,
                                  fontFamily: 'monospace',
                                  fontSize: '0.72rem',
                                  background: row.codeIsAutoGenerated && row.code ? '#1A1008' : 'var(--bg-card)',
                                  color: row.codeIsAutoGenerated && row.code ? '#C9A84C' : 'var(--text-primary)',
                                  borderColor: row.codeIsAutoGenerated && row.code ? 'rgba(201,168,76,0.4)' : 'var(--input-border)',
                                  paddingRight: '2.5rem',
                                }}
                              />
                              {row.code && (
                                <span style={{
                                  position: 'absolute', right: '0.375rem', top: '50%', transform: 'translateY(-50%)',
                                  fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.06em',
                                  padding: '1px 5px', borderRadius: '3px',
                                  background: row.codeIsAutoGenerated ? 'rgba(201,168,76,0.15)' : 'rgba(201,120,30,0.15)',
                                  color: row.codeIsAutoGenerated ? '#C9A84C' : '#C97820',
                                }}>
                                  {row.codeIsAutoGenerated ? 'AUTO' : 'MANUAL'}
                                </span>
                              )}
                            </div>
                          )}
                        </td>
                      )}

                      <td>
                        <input type="text" value={row.name} onChange={(e) => updateRow(idx, 'name', e.target.value)} placeholder="Item name"
                          style={{ ...INPUT_STYLE, borderColor: row.errors.name ? 'rgba(122,46,31,0.5)' : undefined }} />
                        {row.errors.name && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.name}</p>}
                      </td>

                      {showCategoryCol && (
                        <td>
                          <Combobox options={categoryOptions} value={row.category} onChange={(v) => updateRow(idx, 'category', v)} placeholder="Category..." searchPlaceholder="Search..." />
                        </td>
                      )}

                      {showCategoryCol && (
                        <td>
                          <input type="text" value={row.department} readOnly style={{ ...INPUT_STYLE, background: 'var(--bg-cream)', fontSize: '0.75rem' }} />
                        </td>
                      )}

                      {needsPrice && (
                        <td>
                          <input type="number" value={row.price} onChange={(e) => updateRow(idx, 'price', e.target.value)} placeholder="0"
                            style={{ ...INPUT_STYLE, borderColor: row.errors.price ? 'rgba(122,46,31,0.5)' : undefined }} />
                          {row.errors.price && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.price}</p>}
                        </td>
                      )}

                      {showCategoryCol && (
                        <td>
                          <input type="text" value={row.folder} onChange={(e) => updateRow(idx, 'folder', e.target.value)} placeholder="Folder" style={INPUT_STYLE} />
                        </td>
                      )}

                      {/* Printers */}
                      <td>
                        <MultiSelect
                          options={availablePrinters}
                          value={row.printers}
                          onChange={(v) => updateRow(idx, 'printers', v)}
                          placeholder="Printers…"
                          error={row.errors.printers}
                        />
                      </td>

                      {/* Outlets */}
                      <td>
                        <MultiSelect
                          options={availableOutlets}
                          value={row.outlets}
                          onChange={(v) => updateRow(idx, 'outlets', v)}
                          placeholder="Outlets…"
                          error={row.errors.outlets}
                        />
                      </td>

                      {/* POS Settings */}
                      <td style={{ paddingTop: '0.5rem' }}>
                        {POS_FIELDS.map(({ key, abbr, full }) => (
                          <label key={key} title={full} style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.72rem', cursor: 'pointer', marginBottom: '0.2rem', whiteSpace: 'nowrap' }}>
                            <Checkbox checked={row[key] as boolean} onCheckedChange={(v) => updateRow(idx, key, v)} />
                            <span style={{ color: 'var(--text-secondary)' }}>{abbr}</span>
                          </label>
                        ))}
                      </td>

                      {/* Actions */}
                      <td style={{ paddingTop: '0.5rem' }}>
                        <div style={{ display: 'flex', gap: '0.25rem', justifyContent: 'center' }}>
                          <button type="button" onClick={() => duplicateRow(idx)} title="Duplicate row"
                            style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: '3px', padding: '0.25rem 0.4rem', cursor: 'pointer', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center' }}>
                            <Copy size={11} />
                          </button>
                          <button type="button" onClick={() => deleteRow(idx)} title={items.length <= 1 ? 'Cannot remove the last item' : 'Delete row'}
                            style={{ background: 'transparent', border: `1px solid ${items.length <= 1 ? 'var(--border)' : 'rgba(139,58,42,0.25)'}`, borderRadius: '3px', padding: '0.25rem 0.4rem', cursor: items.length <= 1 ? 'not-allowed' : 'pointer', color: items.length <= 1 ? 'var(--text-secondary)' : '#7A2E1F', display: 'flex', alignItems: 'center', opacity: items.length <= 1 ? 0.4 : 1 }}>
                            <Trash2 size={11} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Duplicate PLU code warning (NEW_ITEM only) */}
        {requestType === 'NEW_ITEM' && (() => {
          const autoCodes = items.filter((r) => r.codeIsAutoGenerated && r.code).map((r) => r.code);
          const dupes = Array.from(new Set(autoCodes.filter((c, i) => autoCodes.indexOf(c) !== i)));
          if (dupes.length === 0) return null;
          return (
            <div style={{
              marginBottom: '0.75rem', padding: '0.625rem 0.875rem', borderRadius: '0.375rem',
              background: 'rgba(122,46,31,0.07)', border: '1px solid rgba(122,46,31,0.25)',
              fontSize: '0.8rem', color: '#8B3A2A',
            }}>
              Duplicate PLU codes detected: {dupes.join(', ')}. Check outlet/category selection.
            </div>
          );
        })()}

        {/* Submit bar */}
        <div className="card" style={{ padding: '1rem 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}>
          <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
            <strong style={{ color: 'var(--text-primary)' }}>{items.length}</strong> item{items.length !== 1 ? 's' : ''} ready to submit
          </span>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button
              type="submit"
              disabled={loading}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.625rem 1.5rem', background: loading ? 'rgba(26,16,8,0.5)' : 'var(--bg-dark)', color: 'var(--accent-gold)', border: 'none', borderRadius: '0.375rem', fontSize: '0.875rem', fontWeight: 600, cursor: loading ? 'not-allowed' : 'pointer' }}
            >
              {loading && <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />}
              {loading ? 'Submitting…' : 'Submit Batch'}
            </button>
            <button
              type="button"
              onClick={() => { setTitle(''); setItems([makeDefaultRow()]); }}
              style={{ padding: '0.625rem 1.125rem', background: 'transparent', color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.875rem', cursor: 'pointer' }}
            >
              Clear
            </button>
          </div>
        </div>

      </form>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
