'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { CategoryCodeEntry, suggestPLUCode, assemblePLUCode, derivePrefixGroups, getCategoryCodeParts, prefixForOutlet } from '@/lib/pluCode';
import { Combobox } from '@/components/ui/combobox';
import { MultiSelect } from '@/components/ui/multi-select';
import { toast } from 'sonner';
import { Loader2, Plus, Trash2, Copy, AlertTriangle, Upload, X, Check, Download } from 'lucide-react';
import { SuccessModal } from '@/components/SuccessModal';
import { PLUCodeSearch } from '@/components/PLUCodeSearch';
import type { PLUSearchResult } from '@/components/PLUCodeSearch';
import type { RowMatch, MatchCandidate, BarcodeMismatch, PriceLevelsWarning } from '@/lib/itemMatch';
import { WineWarnings } from '@/components/WineWarnings';

const REQUEST_TYPES = [
  { value: 'NEW_ITEM', label: 'New Item' },
  { value: 'UPDATE_PRICE', label: 'Update Price' },
  { value: 'UPDATE_NAME', label: 'Update Name' },
  { value: 'UPDATE_PRINTER', label: 'Change Printer' },
  { value: 'REMOVE_PLU', label: 'Remove PLU' },
] as const;

type RequestTypeValue = (typeof REQUEST_TYPES)[number]['value'];

interface ConfigCategory {
  id: string; name: string; department: string; departmentCode: number; categoryCode: number; isActive: boolean;
}
interface ConfigPrinter {
  id: string; name: string; group: string; isActive: boolean;
}

interface ItemRow {
  _id: string;
  code: string;
  codeIsAutoGenerated: boolean;
  codeLoading: boolean;
  name: string;
  category: string;
  department: string;
  price: string;
  folder: string;
  barcode: string;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  salesDef: string;
  printers: string[];
  outlets: string[];
  remarks: string;
  currentName: string;  // reference (UPDATE_PRICE/UPDATE_NAME) — display only, not submitted
  currentPrice: string; // reference (UPDATE_PRICE/UPDATE_NAME) — display only, not submitted
  errors: Partial<Record<string, string>>;
}

interface ParsedIssue {
  field: string;
  message: string;
  severity?: 'error';
}

interface ParsedRow {
  rowNum: number;
  status: 'OK' | 'ERROR';
  issues: ParsedIssue[];
  data: Record<string, string>;
}

const IMPORT_COLUMNS: Record<string, { key: string; label: string }[]> = {
  NEW_ITEM: [
    { key: 'Name', label: 'NAME' },
    { key: 'Category', label: 'CATEGORY' },
    { key: 'Department', label: 'DEPARTMENT' },
    { key: 'Price', label: 'PRICE' },
    { key: 'Folder', label: 'FOLDER' },
    { key: 'Printers', label: 'PRINTERS' },
    { key: 'Outlets', label: 'OUTLETS' },
    { key: 'SalesDef', label: 'SALES DEF' },
  ],
  UPDATE_PRICE: [
    { key: 'Name', label: 'NAME' },
    { key: 'Category', label: 'CATEGORY' },
    { key: 'Department', label: 'DEPARTMENT' },
    { key: 'Barcode', label: 'BARCODE' },
    { key: 'Price', label: 'PRICE' },
  ],
  UPDATE_NAME: [
    { key: 'Code', label: 'CODE' },
    { key: 'Name', label: 'NAME' },
  ],
  UPDATE_PRINTER: [
    { key: 'Code', label: 'CODE' },
    { key: 'Printers', label: 'PRINTERS' },
  ],
  REMOVE_PLU: [
    { key: 'Code', label: 'CODE' },
    { key: 'Remarks', label: 'REMARKS' },
  ],
};

const POS_FIELDS: { key: keyof ItemRow; abbr: string; full: string }[] = [
  { key: 'serviceCharge', abbr: 'SC', full: 'Service Charge' },
  { key: 'tax1', abbr: 'T1', full: 'Tax 1' },
  { key: 'tax2', abbr: 'T2', full: 'Tax 2' },
  { key: 'noDiscount', abbr: 'ND', full: 'No Discount' },
  { key: 'hideReceipt', abbr: 'HR', full: 'Hide on Receipt' },
];

const TEMPLATE_HEADERS = ['Code', 'Name', 'Category', 'Department', 'SalesDef', 'Price', 'PLU', 'Barcode', 'UOM', 'Folder', 'ServiceCharge', 'Tax1', 'Tax2', 'NoDiscount', 'HideReceipt', 'Printers', 'Outlets'];

function uid() { return Math.random().toString(36).slice(2, 10); }

function formatPriceDisplay(raw: string): string {
  if (!raw) return '';
  const n = parseInt(raw, 10);
  return isNaN(n) ? '' : n.toLocaleString('id-ID');
}

function makeDefaultRow(): ItemRow {
  return {
    _id: uid(), code: '', codeIsAutoGenerated: true, codeLoading: false, name: '', category: '', department: '',
    price: '', folder: '', barcode: '',
    serviceCharge: true, tax1: true, tax2: true, noDiscount: true, hideReceipt: false,
    salesDef: 'SALES', printers: [], outlets: [], remarks: '', currentName: '', currentPrice: '', errors: {},
  };
}

const INPUT_STYLE: React.CSSProperties = {
  width: '100%', height: '34px', border: '1px solid var(--input-border)',
  borderRadius: '4px', background: 'var(--bg-card)', color: 'var(--text-primary)',
  padding: '0 0.625rem', fontSize: '0.8rem', outline: 'none', boxSizing: 'border-box',
};

async function fetchWithRetry<T>(url: string): Promise<T> {
  const doFetch = async () => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json() as Promise<T>;
  };
  try { return await doFetch(); }
  catch { return await doFetch(); }
}

function findClosestCategory(value: string, categories: ConfigCategory[]): string | null {
  const v = value.toLowerCase().trim();
  for (const c of categories) {
    const cn = c.name.toLowerCase();
    if (cn === v || cn.includes(v) || v.includes(cn)) return c.name;
  }
  return null;
}

function validateImportRows(rows: Record<string, string>[], requestType: RequestTypeValue, categories: ConfigCategory[]): ParsedRow[] {
  return rows.map((row, i) => {
    const rowNum = i + 1;
    const issues: ParsedIssue[] = [];

    if (requestType === 'NEW_ITEM') {
      if (!row['Name']?.trim()) issues.push({ field: 'Name', message: 'Name is required' });
      const catVal = (row['Category'] ?? '').trim();
      if (catVal) {
        const exact = categories.find((c) => c.name.toLowerCase() === catVal.toLowerCase());
        if (!exact) {
          const closest = findClosestCategory(catVal, categories);
          if (closest) {
            issues.push({ field: 'Category', message: `Tidak dikenali. Maksudnya: ${closest}?` });
          } else {
            issues.push({ field: 'Category', message: 'Kategori tidak dikenali', severity: 'error' });
          }
        }
      } else {
        issues.push({ field: 'Category', message: 'Category is required' });
      }
    } else if (requestType === 'UPDATE_NAME') {
      if (!row['Code']?.trim()) issues.push({ field: 'Code', message: 'Code is required' });
      if (!row['Name']?.trim()) issues.push({ field: 'Name', message: 'Name is required' });
    } else if (requestType === 'UPDATE_PRINTER') {
      if (!row['Code']?.trim()) issues.push({ field: 'Code', message: 'Code is required' });
      if (!row['Printers']?.trim()) issues.push({ field: 'Printers', message: 'Printers is required' });
    } else if (requestType === 'REMOVE_PLU') {
      if (!row['Code']?.trim()) issues.push({ field: 'Code', message: 'Code is required' });
      if (!row['Remarks']?.trim()) issues.push({ field: 'Remarks', message: 'Remarks is required' });
    }

    return { rowNum, status: issues.length === 0 ? 'OK' : 'ERROR', issues, data: row };
  });
}

function parsedRowToItemRow(parsed: ParsedRow, requestType: RequestTypeValue, categories: ConfigCategory[]): ItemRow {
  const d = parsed.data;
  const catName = categories.find((c) => c.name.toLowerCase() === (d['Category'] ?? '').toLowerCase())?.name ?? d['Category'] ?? '';
  const dept = categories.find((c) => c.name === catName)?.department ?? d['Department'] ?? '';
  const printers = d['Printers'] ? d['Printers'].split(';').filter(Boolean) : [];
  const outlets = d['Outlets'] ? d['Outlets'].split(';').filter(Boolean) : [];
  const boolVal = (v: string | undefined) => v === '1' || v?.toLowerCase() === 'true';

  return {
    _id: uid(),
    code: d['Code'] ?? '',
    codeIsAutoGenerated: requestType === 'NEW_ITEM' && !d['Code'],
    codeLoading: false,
    name: d['Name'] ?? '',
    category: catName,
    department: dept,
    price: d['Price'] ?? '',
    folder: d['Folder'] ?? '',
    barcode: d['Barcode'] ?? '',
    serviceCharge: d['ServiceCharge'] !== undefined ? boolVal(d['ServiceCharge']) : true,
    tax1: d['Tax1'] !== undefined ? boolVal(d['Tax1']) : true,
    tax2: d['Tax2'] !== undefined ? boolVal(d['Tax2']) : true,
    noDiscount: d['NoDiscount'] !== undefined ? boolVal(d['NoDiscount']) : true,
    hideReceipt: d['HideReceipt'] !== undefined ? boolVal(d['HideReceipt']) : false,
    salesDef: d['SalesDef'] ?? 'SALES',
    printers,
    outlets,
    remarks: d['Remarks'] ?? '',
    currentName: '',
    currentPrice: '',
    errors: {},
  };
}

// ── UPDATE_PRICE import: code resolved by matching against the master registry ──

// Real PIC price-change files carry Name/Category/Department/Barcode/Price (no Code).
const PRICE_TEMPLATE_HEADERS = ['Name', 'Category', 'Department', 'Barcode', 'Price'];

interface PriceMatchRow {
  rowNum: number;
  name: string;
  category: string;
  department: string;
  barcode: string;
  price: string;       // digits only
  match: RowMatch;
  resolvedCode: string; // current code (auto-filled for clean exact match; chosen/typed otherwise)
  confirmed: boolean;   // user explicitly accepted a review row
}

function sanitizePrice(raw: string): string {
  return String(raw ?? '').replace(/[^\d]/g, '');
}

function buildPriceRow(rowNum: number, data: Record<string, string>, match: RowMatch): PriceMatchRow {
  const price = sanitizePrice(data['Price'] ?? '');
  // Clean exact match (no category/department mismatch) auto-fills the code.
  const isExact = match.type === 'barcode' || match.type === 'namecat';
  const cleanExact = isExact && !!match.resolvedCode && !match.categoryMismatch && !match.departmentMismatch;
  return {
    rowNum,
    name: data['Name'] ?? '',
    category: data['Category'] ?? '',
    department: data['Department'] ?? '',
    barcode: data['Barcode'] ?? '',
    price,
    match,
    // Mismatched exact matches keep the resolved code visible but still require confirmation.
    resolvedCode: cleanExact || (isExact && match.resolvedCode) ? (match.resolvedCode ?? '') : '',
    confirmed: false,
  };
}

function priceIsValid(price: string): boolean {
  return price.trim() !== '' && Number(price) > 0;
}

// True for a clean exact match (barcode or name+category) with no category/department
// mismatch — these auto-fill the code and are ready without user action.
function isCleanExact(m: RowMatch): boolean {
  return (m.type === 'barcode' || m.type === 'namecat')
    && !!m.resolvedCode && !m.categoryMismatch && !m.departmentMismatch;
}

// Wine advisory flags that apply to whichever identity is currently selected:
// the resolved exact master, or the candidate the user picked for a fuzzy row.
function effectiveWineWarnings(r: PriceMatchRow): { barcodeMismatch?: BarcodeMismatch; priceLevels?: PriceLevelsWarning } {
  const m = r.match;
  if (m.barcodeMismatch || m.priceLevels) return { barcodeMismatch: m.barcodeMismatch, priceLevels: m.priceLevels };
  const cand = r.resolvedCode ? m.candidates?.find((c) => c.code === r.resolvedCode) : undefined;
  if (cand) return { barcodeMismatch: cand.barcodeMismatch, priceLevels: cand.priceLevels };
  return {};
}

// A row counts toward "siap diimport" only when it has a valid price and either an
// auto-resolved clean exact match, or a code the user explicitly confirmed.
function priceRowReady(r: PriceMatchRow): boolean {
  if (!priceIsValid(r.price) || !r.resolvedCode.trim()) return false;
  return isCleanExact(r.match) || r.confirmed;
}

function csvEscape(v: string | number): string {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function toCsv(headers: string[], rows: (string | number)[][]): string {
  return [headers.join(','), ...rows.map((r) => r.map(csvEscape).join(','))].join('\n');
}
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

export default function BatchNewPage() {
  const { data: session } = useSession();
  const router = useRouter();
  const sessionUser = session?.user as any;
  const outlet = sessionUser?.outlet ?? '';
  const outletGroup = sessionUser?.outletGroup ?? '';

  const [configCategories, setConfigCategories] = useState<ConfigCategory[]>([]);
  const [configPrinters, setConfigPrinters] = useState<ConfigPrinter[]>([]);
  const [configOutlets, setConfigOutlets] = useState<string[]>([]);
  const [configLoading, setConfigLoading] = useState(true);
  const [configError, setConfigError] = useState<string | null>(null);

  useEffect(() => {
    if (!outletGroup) return;
    setConfigLoading(true);
    setConfigError(null);
    Promise.all([
      fetchWithRetry<ConfigCategory[]>(`/api/config/categories?activeOnly=true`),
      fetchWithRetry<ConfigPrinter[]>(`/api/config/printers?group=${encodeURIComponent(outletGroup)}&activeOnly=true`),
      fetchWithRetry<{ code: string }[]>(`/api/config/outlets?group=${encodeURIComponent(outletGroup)}&activeOnly=true`),
    ])
      .then(([cats, printers, outlets]) => {
        setConfigCategories(cats);
        setConfigPrinters(printers);
        setConfigOutlets(outlets.map((o) => o.code));
      })
      .catch(() => setConfigError('Gagal memuat data konfigurasi. Coba muat ulang halaman.'))
      .finally(() => setConfigLoading(false));
  }, [outletGroup]);

  const categoryOptions = configCategories.map((c) => ({ value: c.name, label: c.name, group: c.department }));
  const categoryCodeMap: CategoryCodeEntry[] = configCategories.map((c) => ({
    department: c.department, departmentCode: c.departmentCode, category: c.name, categoryCode: c.categoryCode,
  }));
  const availablePrinters = configPrinters.map((p) => p.name);

  const [title, setTitle] = useState('');
  const [requestType, setRequestType] = useState<RequestTypeValue>('NEW_ITEM');
  const [items, setItems] = useState<ItemRow[]>([makeDefaultRow()]);
  const [loading, setLoading] = useState(false);
  const [successModal, setSuccessModal] = useState({ open: false, title: '', count: 0 });
  const [titleError, setTitleError] = useState('');
  const [globalOutlets, setGlobalOutlets] = useState<string[]>([]);
  const [globalPrinters, setGlobalPrinters] = useState<string[]>([]);
  const [globalRemarks, setGlobalRemarks] = useState('');
  const [applyHighlight, setApplyHighlight] = useState(false);

  // Import state
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importModal, setImportModal] = useState<{ open: boolean; rows: ParsedRow[] }>({ open: false, rows: [] });
  const [priceImportModal, setPriceImportModal] = useState<{ open: boolean; rows: PriceMatchRow[] }>({ open: false, rows: [] });
  const [matching, setMatching] = useState(false);
  const [showRejected, setShowRejected] = useState(false);
  const [isDragOver, setIsDragOver] = useState(false);

  // Sequence management
  const seqBaseCache = useRef<Record<string, number>>({});
  const seqOffsetMap = useRef<Record<string, number>>({});
  const seqFetchPromises = useRef<Record<string, Promise<number>>>({});
  const processingRef = useRef<Set<string>>(new Set());

  // Generate one code for a specific prefix+dept+cat, drawing from a per-key serial
  // sequence so codes never collide — across rows OR across a row's prefix groups.
  async function generateCodeForKey(prefix: string, deptCode: string, catCode: string): Promise<string> {
    const key = `${prefix}${deptCode}${catCode}`;
    if (seqBaseCache.current[key] == null) {
      if (!seqFetchPromises.current[key]) {
        seqFetchPromises.current[key] = fetch(
          `/api/plu/next-sequence?prefix=${encodeURIComponent(prefix)}&deptCode=${encodeURIComponent(deptCode)}&catCode=${encodeURIComponent(catCode)}`
        ).then(async (res) => {
          if (!res.ok) throw new Error();
          const data = await res.json();
          if (typeof data.sequence !== 'number') throw new Error();
          seqBaseCache.current[key] = data.sequence;
          if (seqOffsetMap.current[key] == null) seqOffsetMap.current[key] = 0;
          return data.sequence;
        });
      }
      try { await seqFetchPromises.current[key]; }
      catch { delete seqFetchPromises.current[key]; return ''; }
    }
    const base = seqBaseCache.current[key];
    const offset = seqOffsetMap.current[key] ?? 0;
    seqOffsetMap.current[key] = offset + 1;
    return assemblePLUCode(prefix, deptCode, catCode, base + offset);
  }

  // Standalone PLU generation — used by confirmImport to generate codes serially per group.
  // Uses the row's first derived prefix group (single-prefix rows are the common case;
  // multi-prefix rows are fully expanded at submit time).
  async function generatePluForRow(rowData: { category: string; outlets: string[] }): Promise<string> {
    if (!rowData.category) return '';
    const s = suggestPLUCode(rowData.category, outlet, rowData.outlets, 4000, categoryCodeMap);
    if (!s) return '';
    return generateCodeForKey(s.prefix, s.deptCode, s.catCode);
  }

  useEffect(() => {
    if (configLoading || categoryCodeMap.length === 0) return;
    const loadingRows = items.filter(
      (r) => r.codeLoading && r.codeIsAutoGenerated && r.category && !processingRef.current.has(r._id)
    );
    if (loadingRows.length === 0) return;

    for (const row of loadingRows) {
      const rowId = row._id;
      const rowCategory = row.category;
      const rowOutlets = row.outlets;
      processingRef.current.add(rowId);

      const s = suggestPLUCode(rowCategory, outlet, rowOutlets, 4000, categoryCodeMap);
      if (!s) {
        processingRef.current.delete(rowId);
        setItems((prev) => prev.map((r) => r._id === rowId ? { ...r, codeLoading: false, code: '' } : r));
        continue;
      }

      const { prefix, deptCode, catCode } = s;
      const key = `${prefix}${deptCode}${catCode}`;
      const capturedOutletsKey = [...rowOutlets].sort().join('\x00');
      const capturedCategory = rowCategory;

      (async () => {
        try {
          if (seqBaseCache.current[key] == null) {
            if (!seqFetchPromises.current[key]) {
              seqFetchPromises.current[key] = fetch(
                `/api/plu/next-sequence?prefix=${encodeURIComponent(prefix)}&deptCode=${encodeURIComponent(deptCode)}&catCode=${encodeURIComponent(catCode)}`
              ).then(async (res) => {
                if (!res.ok) throw new Error();
                const data = await res.json();
                if (typeof data.sequence !== 'number') throw new Error();
                seqBaseCache.current[key] = data.sequence;
                if (seqOffsetMap.current[key] == null) seqOffsetMap.current[key] = 0;
                return data.sequence;
              });
            }
            try { await seqFetchPromises.current[key]; }
            catch {
              delete seqFetchPromises.current[key];
              toast.error('Could not load PLU code sequence.', { id: `seq-err-${key}` });
              setItems((prev) => prev.map((r) => r._id === rowId ? { ...r, code: '', codeLoading: false } : r));
              return;
            }
          }
          const base = seqBaseCache.current[key];
          const offset = seqOffsetMap.current[key] ?? 0;
          seqOffsetMap.current[key] = offset + 1;
          const code = assemblePLUCode(prefix, deptCode, catCode, base + offset);
          setItems((prev) => prev.map((r) => {
            if (r._id !== rowId) return r;
            if (!r.codeIsAutoGenerated || !r.codeLoading) return r;
            if ([...r.outlets].sort().join('\x00') !== capturedOutletsKey || r.category !== capturedCategory) return { ...r, codeLoading: true };
            return { ...r, code, codeLoading: false };
          }));
        } finally {
          processingRef.current.delete(rowId);
        }
      })();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items, configLoading]);

  const isUpdate = requestType !== 'NEW_ITEM';
  const isRemovePLU = requestType === 'REMOVE_PLU';
  const showNameCol = requestType === 'NEW_ITEM' || requestType === 'UPDATE_NAME';
  const showCategoryCol = requestType === 'NEW_ITEM';
  const showPriceCol = requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRICE';
  const showFolderCol = requestType === 'NEW_ITEM';
  const showBarcodeColumn = showCategoryCol && items.some((r) => r.department === 'WINE');
  const showPrintersCol = requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRINTER';
  const showOutletsCol = requestType === 'NEW_ITEM';
  // Update/remove types get a dedicated optional Outlets column after Remarks; NEW_ITEM keeps its own column above.
  const showUpdateOutletsCol = requestType !== 'NEW_ITEM';
  const showAnyOutlets = showOutletsCol || showUpdateOutletsCol; // outlets apply to every request type
  const showPOSCol = requestType === 'NEW_ITEM';
  const showCurrentRefCols = requestType === 'UPDATE_PRICE' || requestType === 'UPDATE_NAME';
  const showRemarksCol = requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRICE' || requestType === 'UPDATE_NAME';
  const showGlobalRemarks = requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRICE' || requestType === 'UPDATE_NAME';
  const showApplyCard = showAnyOutlets || showPrintersCol || showGlobalRemarks;
  // Heads-up when the globally-chosen outlets span multiple prefixes — each NEW_ITEM
  // row will then expand into one item per prefix at submit.
  const globalPrefixCount = new Set(globalOutlets.map(prefixForOutlet)).size;
  const showGlobalMultiPrefixNotice = requestType === 'NEW_ITEM' && globalOutlets.length > 0 && globalPrefixCount > 1;
  const showApplyHighlight = applyHighlight && items.some(
    (r) => (showOutletsCol && r.outlets.length === 0) || (showPrintersCol && r.printers.length === 0)
  );

  const addRow = useCallback(() => {
    setItems((prev) => {
      const last = prev[prev.length - 1];
      const hasCategory = Boolean(last.category);
      const newRow: ItemRow = {
        ...last, _id: uid(), code: '', codeIsAutoGenerated: true,
        codeLoading: hasCategory && requestType === 'NEW_ITEM', name: '', remarks: '',
        currentName: '', currentPrice: '', errors: {},
      };
      return [...prev, newRow];
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [outlet, requestType]);

  function duplicateRow(idx: number) {
    setItems((prev) => {
      const src = prev[idx];
      const copy: ItemRow = { ...src, _id: uid(), name: '', remarks: '', errors: {} };
      if (copy.codeIsAutoGenerated && copy.category) { copy.code = ''; copy.codeLoading = true; }
      const next = [...prev];
      next.splice(idx + 1, 0, copy);
      return next;
    });
  }

  function deleteRow(idx: number) {
    if (items.length <= 1) { toast.error('Cannot remove the last item'); return; }
    setItems((prev) => prev.filter((_, i) => i !== idx));
  }

  function updateRow(idx: number, key: keyof ItemRow, value: any) {
    setItems((prev) => prev.map((row, i) => {
      if (i !== idx) return row;
      const updated = { ...row, [key]: value, errors: { ...row.errors, [key]: undefined } };
      if (key === 'category') {
        updated.department = configCategories.find((c) => c.name === (value as string))?.department ?? '';
        if (updated.department !== 'WINE') updated.barcode = '';
      }
      if ((key === 'category' || key === 'outlets') && updated.codeIsAutoGenerated && requestType === 'NEW_ITEM') {
        const cat = key === 'category' ? (value as string) : updated.category;
        if (cat) { updated.code = ''; updated.codeLoading = true; }
      }
      return updated;
    }));
  }

  function handleCodeSearchChange(idx: number, code: string) {
    // Manual typing keeps the linked current name/price — only a dropdown selection re-syncs them.
    setItems((prev) => prev.map((r, i) => {
      if (i !== idx) return r;
      return { ...r, code, codeIsAutoGenerated: false, errors: { ...r.errors, code: undefined } };
    }));
  }

  // UPDATE_PRICE / UPDATE_NAME item-name search box — manual typing keeps the PLU code untouched
  function handleNameSearchChange(idx: number, name: string) {
    setItems((prev) => prev.map((r, i) => (i === idx ? { ...r, currentName: name } : r)));
  }

  function handleCodeItemSelect(idx: number, item: PLUSearchResult) {
    setItems((prev) => prev.map((r, i) => {
      if (i !== idx) return r;
      const updated = { ...r, code: item.code, codeIsAutoGenerated: false, errors: { ...r.errors, code: undefined } };
      if (isRemovePLU) {
        updated.name = item.name;
        updated.folder = item.folder ?? '';
      }
      if (requestType === 'UPDATE_PRICE' || requestType === 'UPDATE_NAME') {
        updated.currentName = item.name;
        updated.currentPrice = item.price != null ? String(item.price) : '';
      }
      return updated;
    }));
  }

  function validate(): boolean {
    let valid = true;
    const errorRows: number[] = [];
    if (!title.trim()) { setTitleError('Batch title is required'); valid = false; }
    const updatedItems = items.map((row, idx) => {
      const errors: Record<string, string> = {};
      if (requestType === 'NEW_ITEM') {
        if (!row.name.trim()) errors.name = 'Name required';
        // outlets/printers validated globally below
      } else if (requestType === 'UPDATE_PRICE') {
        if (!row.code.trim()) errors.code = 'Code required';
        if (!row.price || Number(row.price) <= 0) errors.price = 'Price required';
      } else if (requestType === 'UPDATE_NAME') {
        if (!row.code.trim()) errors.code = 'Code required';
        if (!row.name.trim()) errors.name = 'Name required';
      } else if (requestType === 'UPDATE_PRINTER') {
        if (!row.code.trim()) errors.code = 'Code required';
        // printers validated globally below
      } else if (requestType === 'REMOVE_PLU') {
        if (!row.code.trim()) errors.code = 'Code required';
        if (!row.remarks.trim()) errors.remarks = 'Alasan penghapusan harus diisi';
      }
      if (Object.keys(errors).length > 0) { valid = false; errorRows.push(idx + 1); }
      return { ...row, errors };
    });
    setItems(updatedItems);
    if (!valid) {
      if (errorRows.length > 0) toast.error(`Periksa baris: ${errorRows.join(', ')}`);
      else toast.error('Judul batch harus diisi');
      return false;
    }
    if (requestType === 'NEW_ITEM' && items.some((r) => r.outlets.length === 0 || r.printers.length === 0)) {
      toast.error('Gunakan tombol Terapkan ke Semua Baris untuk mengisi outlet dan printer sebelum submit.');
      return false;
    }
    if (requestType === 'UPDATE_PRINTER' && items.some((r) => r.printers.length === 0)) {
      toast.error('Gunakan tombol Terapkan ke Semua Baris untuk mengisi outlet dan printer sebelum submit.');
      return false;
    }
    return true;
  }

  // Map a row to a batch payload item, with outlets/code supplied per-call so a
  // multi-prefix row can be split into several items each carrying its own subset.
  function rowToPayloadItem(row: ItemRow, outlets: string[], code: string | undefined) {
    return {
      code: code || undefined,
      codeIsAutoGenerated: row.codeIsAutoGenerated,
      name: row.name.trim() || '',
      category: row.category || '',
      department: row.department || '',
      price: parseInt(row.price || '0', 10),
      folder: row.folder || undefined,
      serviceCharge: row.serviceCharge,
      tax1: row.tax1,
      tax2: row.tax2,
      noDiscount: row.noDiscount,
      hideReceipt: row.hideReceipt,
      printers: row.printers,
      outlets,
      salesDef: row.salesDef || 'SALES',
      barcode: row.department === 'WINE' ? row.barcode || undefined : undefined,
      remarks: row.remarks || undefined,
    };
  }

  // Expand NEW_ITEM rows into payload items: auto rows split by prefix group (one
  // item per group, each with a freshly-allocated code for its prefix); manual-code
  // rows pass through untouched. Returns null if any sequence fetch fails.
  async function buildNewItemPayloadItems(): Promise<ReturnType<typeof rowToPayloadItem>[] | null> {
    // Fresh allocation so the submitted codes are a clean contiguous block.
    seqBaseCache.current = {};
    seqOffsetMap.current = {};
    seqFetchPromises.current = {};

    type Exp = { row: ItemRow; outlets: string[]; prefix: string; deptCode: string; catCode: string };
    const expanded: Exp[] = [];
    for (const row of items) {
      const parts = getCategoryCodeParts(row.category, categoryCodeMap);
      const groups = derivePrefixGroups(row.category, row.outlets, categoryCodeMap);
      // Manual-code rows, unknown categories, or rows without outlets pass through as-is.
      if (!row.codeIsAutoGenerated || !parts || groups.length === 0) {
        expanded.push({ row, outlets: row.outlets, prefix: '', deptCode: '', catCode: '' });
        continue;
      }
      for (const g of groups) {
        expanded.push({ row, outlets: g.outlets, prefix: g.prefix, deptCode: parts.deptCode, catCode: parts.catCode });
      }
    }

    // Generate codes grouped by prefix key — serial within a key, parallel across keys.
    const byKey = new Map<string, Exp[]>();
    for (const e of expanded) {
      if (!e.prefix) continue;
      const key = `${e.prefix}${e.deptCode}${e.catCode}`;
      if (!byKey.has(key)) byKey.set(key, []);
      byKey.get(key)!.push(e);
    }
    const codes = new Map<Exp, string>();
    let failed = false;
    await Promise.all(Array.from(byKey.values()).map(async (entries) => {
      for (const e of entries) {
        const code = await generateCodeForKey(e.prefix, e.deptCode, e.catCode);
        if (!code) { failed = true; return; }
        codes.set(e, code);
      }
    }));
    if (failed) return null;

    return expanded.map((e) => rowToPayloadItem(e.row, e.outlets, e.prefix ? codes.get(e) : (e.row.code || undefined)));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (items.length === 0) { toast.error('Tambahkan minimal 1 item sebelum submit'); return; }
    if (!validate()) return;
    setLoading(true);
    try {
      const payloadItems = requestType === 'NEW_ITEM'
        ? await buildNewItemPayloadItems()
        : items.map((row) => rowToPayloadItem(row, row.outlets, row.code));
      if (!payloadItems) {
        toast.error('Gagal membuat kode PLU. Coba lagi.');
        return;
      }
      const payload = { title: title.trim(), requestType, items: payloadItems };
      const res = await fetch('/api/batches', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? 'Submission failed');
      }
      setSuccessModal({ open: true, title: title.trim(), count: payloadItems.length });
      setTitle('');
      setItems([makeDefaultRow()]);
    } catch (err: any) {
      toast.error(err.message ?? 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }

  // ── File import ──────────────────────────────────────────────────────────────

  async function parseFile(file: File): Promise<Record<string, string>[]> {
    const XLSX = await import('xlsx');
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = e.target?.result;
          const wb = XLSX.read(data, { type: 'binary' });
          const ws = wb.Sheets[wb.SheetNames[0]];
          const raw = XLSX.utils.sheet_to_json<unknown[]>(ws, { header: 1 }) as unknown[][];
          if (raw.length < 2) { resolve([]); return; }
          const headers = (raw[0] as string[]).map((h) => String(h ?? '').trim());
          const rows: Record<string, string>[] = [];
          for (let i = 1; i < raw.length; i++) {
            const cells = raw[i] as unknown[];
            const row: Record<string, string> = {};
            headers.forEach((h, j) => { row[h] = cells[j] != null ? String(cells[j]).trim() : ''; });
            const hasData = headers.some((h) => row[h] !== '');
            if (hasData) rows.push(row);
          }
          resolve(rows);
        } catch (err) { reject(err); }
      };
      reader.onerror = reject;
      reader.readAsBinaryString(file);
    });
  }

  async function handleFile(file: File) {
    if (!file.name.match(/\.(xlsx|csv)$/i)) {
      toast.error('Only .xlsx and .csv files are supported');
      return;
    }
    try {
      const rows = await parseFile(file);
      if (rows.length === 0) { toast.error('File is empty or has no data rows'); return; }

      // UPDATE_PRICE files have no Code column — resolve it by matching against
      // the master registry instead of validating a Code field.
      if (requestType === 'UPDATE_PRICE') {
        setMatching(true);
        try {
          const inputs = rows.map((r) => ({
            name: r['Name'] ?? '', category: r['Category'] ?? '',
            department: r['Department'] ?? '', barcode: r['Barcode'] ?? '',
          }));
          const res = await fetch('/api/plu/match-batch', {
            method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: inputs }),
          });
          if (!res.ok) throw new Error('match failed');
          const data = await res.json();
          const results: RowMatch[] = data.results ?? [];
          const priceRows = rows.map((r, i) => buildPriceRow(i + 1, r, results[i] ?? { type: 'none' }));
          setShowRejected(false);
          setPriceImportModal({ open: true, rows: priceRows });
        } catch {
          toast.error('Gagal mencocokkan data dengan master item. Coba lagi.');
        } finally {
          setMatching(false);
        }
        return;
      }

      const validated = validateImportRows(rows, requestType, configCategories);
      setImportModal({ open: true, rows: validated });
    } catch {
      toast.error('Failed to parse file. Please check the format.');
    }
  }

  function handleFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file) handleFile(file);
    e.target.value = '';
  }

  function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    if (file) handleFile(file);
  }

  function updatePriceRow(rowNum: number, patch: Partial<PriceMatchRow>) {
    setPriceImportModal((prev) => ({
      ...prev,
      rows: prev.rows.map((r) => (r.rowNum === rowNum ? { ...r, ...patch } : r)),
    }));
  }

  // Pull ready rows (auto-resolved clean exact + user-confirmed) into the items
  // table, carrying the resolved code, new price, and the master name/price for reference.
  function confirmPriceImport() {
    const ready = priceImportModal.rows.filter(priceRowReady);
    if (ready.length === 0) return;
    const newItems: ItemRow[] = ready.map((r) => {
      const cand = r.match.candidates?.find((c) => c.code === r.resolvedCode);
      const displayName = r.match.master?.name ?? cand?.name ?? r.name;
      const oldPrice = r.match.master?.price ?? cand?.price ?? null;
      return {
        ...makeDefaultRow(),
        code: r.resolvedCode.trim(),
        codeIsAutoGenerated: false,
        price: r.price,
        name: displayName,
        currentName: displayName,
        currentPrice: oldPrice != null ? String(oldPrice) : '',
      };
    });
    setItems(newItems);
    setPriceImportModal({ open: false, rows: [] });
    toast.success(`${newItems.length} baris berhasil diimport`);
  }

  async function confirmImport() {
    const okRows = importModal.rows.filter((r) => r.status === 'OK');
    const newItems = okRows.map((r) => parsedRowToItemRow(r, requestType, configCategories));
    const finalItems = newItems.length > 0 ? newItems : [makeDefaultRow()];
    setItems(finalItems);
    setImportModal({ open: false, rows: [] });
    toast.success(`${okRows.length} baris berhasil diimport`);

    // Highlight global apply card if any row is missing outlets or printers
    if (requestType === 'NEW_ITEM' || requestType === 'UPDATE_PRINTER') {
      const needsHighlight = finalItems.some(
        (r) => (showOutletsCol && r.outlets.length === 0) || (showPrintersCol && r.printers.length === 0)
      );
      if (needsHighlight) setApplyHighlight(true);
    }

    // Auto-generate PLU codes for NEW_ITEM rows with category+department but no code
    if (requestType !== 'NEW_ITEM') return;

    const rowsForGen = finalItems.filter(
      (r) => r.codeIsAutoGenerated && r.category && r.department && !r.code
    );
    if (rowsForGen.length === 0) return;

    // Group by prefix+dept+cat to prevent sequence collisions — process each group serially
    const groups = new Map<string, { row: ItemRow; prefix: string; deptCode: string; catCode: string }[]>();
    for (const row of rowsForGen) {
      const s = suggestPLUCode(row.category, outlet, row.outlets, 4000, categoryCodeMap);
      if (!s) continue;
      const key = `${s.prefix}${s.deptCode}${s.catCode}`;
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push({ row, prefix: s.prefix, deptCode: s.deptCode, catCode: s.catCode });
    }

    // Different groups run in parallel; rows within a group run serially
    await Promise.allSettled(
      Array.from(groups.values()).map(async (entries) => {
        for (const { row } of entries) {
          try {
            const code = await generatePluForRow({ category: row.category, outlets: row.outlets });
            if (code) {
              setItems((prev) => prev.map((r) => r._id === row._id ? { ...r, code } : r));
            }
          } catch {
            // leave code as '—'
          }
        }
      })
    );
  }

  async function downloadTemplate() {
    const XLSX = await import('xlsx');
    const date = new Date().toISOString().split('T')[0];
    const headers = requestType === 'UPDATE_PRICE' ? PRICE_TEMPLATE_HEADERS : TEMPLATE_HEADERS;
    const ws = XLSX.utils.aoa_to_sheet([headers]);
    ws['!cols'] = headers.map(() => ({ wch: 15 }));
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Template');
    const buffer = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `template-batch-${requestType.toLowerCase()}-${date}.xlsx`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const allOk = importModal.rows.length > 0 && importModal.rows.every((r) => r.status === 'OK');
  const okCount = importModal.rows.filter((r) => r.status === 'OK').length;

  const configBanner = configLoading ? (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 0.75rem', borderRadius: '0.375rem', background: 'var(--bg-cream)', border: '1px solid var(--border)', marginBottom: '0.75rem' }}>
      <Loader2 size={13} style={{ animation: 'spin 1s linear infinite', color: 'var(--text-secondary)' }} />
      <span style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>Memuat data konfigurasi…</span>
    </div>
  ) : configError ? (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 0.75rem', borderRadius: '0.375rem', background: 'rgba(122,46,31,0.07)', border: '1px solid rgba(122,46,31,0.2)', marginBottom: '0.75rem' }}>
      <AlertTriangle size={13} style={{ color: '#8B3A2A' }} />
      <span style={{ fontSize: '0.78rem', color: '#8B3A2A' }}>Gagal memuat data konfigurasi. Coba muat ulang halaman.</span>
    </div>
  ) : null;

  return (
    <div>
      {/* Import validation modal */}
      {importModal.open && (() => {
        const cols = IMPORT_COLUMNS[requestType] ?? [];
        return (
          <>
            <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 60 }} />
            <div style={{
              position: 'fixed', top: '5vh', left: '50%', transform: 'translateX(-50%)',
              width: 'min(900px, 96vw)', maxHeight: '90vh',
              zIndex: 70, background: 'var(--bg-card)', borderRadius: '0.5rem',
              boxShadow: '0 8px 40px rgba(0,0,0,0.2)', display: 'flex', flexDirection: 'column', overflow: 'hidden',
            }}>
              <div style={{ padding: '1.25rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 }}>
                <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.25rem', fontWeight: 500, margin: 0 }}>Periksa Data Sebelum Import</h2>
                <button onClick={() => setImportModal({ open: false, rows: [] })} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-secondary)', padding: '0.25rem' }}>
                  <X size={18} />
                </button>
              </div>

              <div style={{ flex: 1, overflow: 'auto' }}>
                <table style={{ tableLayout: 'auto', minWidth: '500px', borderCollapse: 'collapse' }}>
                  <thead>
                    <tr style={{ position: 'sticky', top: 0, background: 'var(--bg-card)', zIndex: 1 }}>
                      <th style={{ width: '44px', textAlign: 'center', padding: '0.625rem 0.5rem', borderBottom: '1px solid var(--border)', fontSize: '0.65rem', letterSpacing: '0.08em', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase' }}>#</th>
                      <th style={{ width: '130px', padding: '0.625rem 0.75rem', borderBottom: '1px solid var(--border)', fontSize: '0.65rem', letterSpacing: '0.08em', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase' }}>STATUS</th>
                      {cols.map((col) => (
                        <th key={col.key} style={{ minWidth: '120px', padding: '0.625rem 0.75rem', borderBottom: '1px solid var(--border)', fontSize: '0.65rem', letterSpacing: '0.08em', color: 'var(--text-secondary)', fontWeight: 700, textTransform: 'uppercase', textAlign: 'left', whiteSpace: 'nowrap' }}>
                          {col.label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {importModal.rows.map((row) => {
                      const isOk = row.status === 'OK';
                      return (
                        <tr key={row.rowNum} style={{ borderBottom: '1px solid var(--border)', background: isOk ? undefined : 'rgba(184,134,11,0.025)' }}>
                          <td style={{ textAlign: 'center', padding: '0.5rem', fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 600, verticalAlign: 'middle' }}>{row.rowNum}</td>
                          <td style={{ padding: '0.5rem 0.75rem', verticalAlign: 'middle' }}>
                            {isOk ? (
                              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.2rem', padding: '0.15rem 0.5rem', borderRadius: '0.25rem', fontSize: '0.67rem', fontWeight: 600, background: 'rgba(61,90,62,0.1)', color: '#2D4A2E', border: '1px solid rgba(61,90,62,0.25)' }}>
                                <Check size={9} /> OK
                              </span>
                            ) : (
                              <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0.15rem 0.4rem', borderRadius: '0.25rem', fontSize: '0.62rem', fontWeight: 700, background: 'rgba(184,134,11,0.12)', color: '#8B6914', border: '1px solid rgba(184,134,11,0.3)', whiteSpace: 'nowrap' }}>
                                PERLU DIPERBAIKI
                              </span>
                            )}
                          </td>
                          {cols.map((col) => {
                            const cellValue = row.data[col.key] ?? '';
                            const issue = row.issues.find((iss) => iss.field === col.key);
                            const isError = !!issue;
                            const isRedError = issue?.severity === 'error';
                            const cellBg = isRedError ? '#FEE2E2' : isError ? '#FEF3C7' : undefined;
                            const cellColor = isRedError ? '#991B1B' : isError ? '#92400E' : undefined;
                            return (
                              <td key={col.key} style={{ padding: '0.4rem 0.625rem', verticalAlign: 'middle', background: cellBg }}>
                                <div style={{ fontSize: '0.78rem', color: cellColor ?? 'var(--text-primary)', whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxWidth: '200px' }}>
                                  {cellValue || <span style={{ color: 'var(--text-secondary)', fontStyle: 'italic' }}>—</span>}
                                </div>
                                {issue && (
                                  <div style={{ fontSize: '0.67rem', color: isRedError ? '#991B1B' : '#92400E', marginTop: '1px', lineHeight: 1.3 }}>
                                    {issue.message}
                                  </div>
                                )}
                              </td>
                            );
                          })}
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              <div style={{ padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', flexShrink: 0 }}>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  {okCount} dari {importModal.rows.length} baris siap diimport
                </span>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button
                    onClick={() => setImportModal({ open: false, rows: [] })}
                    style={{ padding: '0.5rem 1rem', background: 'transparent', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.8rem', cursor: 'pointer', color: 'var(--text-secondary)' }}
                  >
                    Tutup dan Perbaiki
                  </button>
                  <button
                    onClick={confirmImport}
                    disabled={!allOk}
                    title={!allOk ? 'Perbaiki semua baris bermasalah terlebih dahulu' : undefined}
                    style={{ padding: '0.5rem 1.25rem', background: allOk ? 'var(--bg-dark)' : 'rgba(26,16,8,0.3)', border: 'none', borderRadius: '0.375rem', fontSize: '0.8rem', fontWeight: 600, cursor: allOk ? 'pointer' : 'not-allowed', color: allOk ? 'var(--accent-gold)' : 'rgba(201,168,76,0.4)' }}
                  >
                    Import {okCount} Baris
                  </button>
                </div>
              </div>
            </div>
          </>
        );
      })()}

      {/* UPDATE_PRICE import modal — code resolved by matching against the registry */}
      {priceImportModal.open && (() => {
        const rows = priceImportModal.rows;
        const rejected = rows.filter((r) => r.match.type === 'none');
        const matched = rows.filter((r) => r.match.type !== 'none');
        const readyCount = rows.filter(priceRowReady).length;
        const fmtRp = (n: number) => n.toLocaleString('id-ID');

        const badge = (ready: boolean) => ready ? (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.2rem', padding: '0.15rem 0.5rem', borderRadius: '0.25rem', fontSize: '0.67rem', fontWeight: 600, background: 'rgba(61,90,62,0.1)', color: '#2D4A2E', border: '1px solid rgba(61,90,62,0.25)', whiteSpace: 'nowrap' }}>
            <Check size={9} /> SIAP
          </span>
        ) : (
          <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0.15rem 0.4rem', borderRadius: '0.25rem', fontSize: '0.62rem', fontWeight: 700, background: 'rgba(184,134,11,0.12)', color: '#8B6914', border: '1px solid rgba(184,134,11,0.3)', whiteSpace: 'nowrap' }}>
            PERLU DIPERBAIKI
          </span>
        );

        const matchBasisLabel = (t: string) => t === 'barcode' ? 'Cocok via barcode' : t === 'namecat' ? 'Cocok via nama + kategori' : t === 'fuzzy' ? 'Nama mirip' : '';

        return (
          <>
            <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 60 }} />
            <div style={{
              position: 'fixed', top: '5vh', left: '50%', transform: 'translateX(-50%)',
              width: 'min(940px, 96vw)', maxHeight: '90vh',
              zIndex: 70, background: 'var(--bg-card)', borderRadius: '0.5rem',
              boxShadow: '0 8px 40px rgba(0,0,0,0.2)', display: 'flex', flexDirection: 'column', overflow: 'hidden',
            }}>
              <div style={{ padding: '1.25rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 }}>
                <div>
                  <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.25rem', fontWeight: 500, margin: 0 }}>Periksa Data Sebelum Import</h2>
                  <p style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', margin: '0.25rem 0 0' }}>
                    Kode PLU dicocokkan otomatis dari Nama / Kategori / Barcode terhadap master item.
                  </p>
                </div>
                <button onClick={() => setPriceImportModal({ open: false, rows: [] })} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-secondary)', padding: '0.25rem' }}>
                  <X size={18} />
                </button>
              </div>

              <div style={{ flex: 1, overflow: 'auto', padding: '0.75rem 1rem' }}>
                {matched.length === 0 && (
                  <div style={{ padding: '1.5rem', textAlign: 'center', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                    Tidak ada baris yang cocok dengan master item.
                  </div>
                )}

                {matched.map((r) => {
                  const m = r.match;
                  const isExact = m.type === 'barcode' || m.type === 'namecat';
                  const cleanExact = isCleanExact(m);
                  const mismatchExact = isExact && !!m.resolvedCode && (m.categoryMismatch || m.departmentMismatch);
                  const needsCandidate = (isExact && !m.resolvedCode) || m.type === 'fuzzy'; // ambiguous or fuzzy
                  const priceOk = priceIsValid(r.price);
                  const ready = priceRowReady(r);

                  return (
                    <div key={r.rowNum} style={{
                      border: `1px solid ${ready ? 'rgba(61,90,62,0.25)' : 'var(--border)'}`,
                      borderLeft: `3px solid ${ready ? '#3D5A3E' : '#B8860B'}`,
                      borderRadius: '0.375rem', padding: '0.75rem 0.875rem', marginBottom: '0.625rem',
                      background: ready ? 'rgba(61,90,62,0.03)' : 'rgba(184,134,11,0.025)',
                    }}>
                      {/* Header line */}
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem', flexWrap: 'wrap' }}>
                        <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', fontWeight: 600, minWidth: '20px' }}>#{r.rowNum}</span>
                        {badge(ready)}
                        <span style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-primary)' }}>{r.name || <em style={{ color: 'var(--text-secondary)' }}>tanpa nama</em>}</span>
                        {r.category && <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>· {r.category}</span>}
                        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                          <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>Harga baru</span>
                          <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>Rp</span>
                          <input
                            type="text" inputMode="numeric" value={formatPriceDisplay(r.price)}
                            onChange={(e) => updatePriceRow(r.rowNum, { price: sanitizePrice(e.target.value) })}
                            placeholder="0"
                            style={{ width: '110px', height: '30px', border: `1px solid ${priceOk ? 'var(--input-border)' : 'rgba(122,46,31,0.5)'}`, borderRadius: '4px', background: 'var(--bg-card)', color: 'var(--text-primary)', padding: '0 0.5rem', fontSize: '0.78rem', outline: 'none', textAlign: 'right' }}
                          />
                        </div>
                      </div>
                      {!priceOk && <div style={{ fontSize: '0.7rem', color: '#8B3A2A', marginTop: '0.35rem' }}>Harga tidak valid — perbaiki sebelum baris ini dapat diimport.</div>}

                      {/* Clean exact match */}
                      {cleanExact && (
                        <div style={{ marginTop: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap', fontSize: '0.76rem' }}>
                          <span style={{ color: 'var(--text-secondary)' }}>{matchBasisLabel(m.type)} →</span>
                          <span style={{ fontFamily: 'monospace', fontWeight: 700, color: '#C9A84C' }}>{m.resolvedCode}</span>
                          <span style={{ color: 'var(--text-primary)' }}>{m.master?.name}</span>
                          <span style={{ color: 'var(--text-secondary)' }}>({m.master?.category})</span>
                          {m.master?.price != null && <span style={{ color: 'var(--text-secondary)' }}>· harga lama Rp {fmtRp(m.master.price)}</span>}
                        </div>
                      )}

                      {/* Exact match but category/department differs — show both sides, require confirm */}
                      {mismatchExact && (
                        <div style={{ marginTop: '0.5rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap', fontSize: '0.76rem', marginBottom: '0.4rem' }}>
                            <span style={{ color: 'var(--text-secondary)' }}>{matchBasisLabel(m.type)} →</span>
                            <span style={{ fontFamily: 'monospace', fontWeight: 700, color: '#C9A84C' }}>{m.resolvedCode}</span>
                            <span style={{ color: 'var(--text-primary)' }}>{m.master?.name}</span>
                            {m.master?.price != null && <span style={{ color: 'var(--text-secondary)' }}>· harga lama Rp {fmtRp(m.master.price)}</span>}
                          </div>
                          <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', fontSize: '0.72rem', background: 'rgba(184,134,11,0.06)', border: '1px solid rgba(184,134,11,0.2)', borderRadius: '0.25rem', padding: '0.4rem 0.6rem' }}>
                            <div>
                              <div style={{ color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '2px' }}>Dari file</div>
                              <div style={{ color: m.categoryMismatch ? '#8B6914' : 'var(--text-primary)' }}>Kategori: {r.category || '—'}</div>
                              <div style={{ color: m.departmentMismatch ? '#8B6914' : 'var(--text-primary)' }}>Departemen: {r.department || '—'}</div>
                            </div>
                            <div style={{ borderLeft: '1px solid rgba(184,134,11,0.25)', paddingLeft: '0.75rem' }}>
                              <div style={{ color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '2px' }}>Master item</div>
                              <div style={{ color: m.categoryMismatch ? '#8B6914' : 'var(--text-primary)', fontWeight: m.categoryMismatch ? 700 : 400 }}>Kategori: {m.master?.category || '—'}</div>
                              <div style={{ color: m.departmentMismatch ? '#8B6914' : 'var(--text-primary)', fontWeight: m.departmentMismatch ? 700 : 400 }}>Departemen: {m.master?.department || '—'}</div>
                            </div>
                          </div>
                          <div style={{ marginTop: '0.4rem' }}>
                            {r.confirmed ? (
                              <span style={{ fontSize: '0.74rem', color: '#2D4A2E' }}>
                                Dikonfirmasi — kode <span style={{ fontFamily: 'monospace', fontWeight: 700 }}>{r.resolvedCode}</span>{' '}
                                <button type="button" onClick={() => updatePriceRow(r.rowNum, { confirmed: false })} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', textDecoration: 'underline', cursor: 'pointer', fontSize: '0.72rem' }}>Ganti</button>
                              </span>
                            ) : (
                              <button type="button" onClick={() => updatePriceRow(r.rowNum, { confirmed: true })}
                                style={{ padding: '0.3rem 0.7rem', background: 'var(--bg-dark)', color: 'var(--accent-gold)', border: 'none', borderRadius: '0.3rem', fontSize: '0.74rem', fontWeight: 600, cursor: 'pointer' }}>
                                Gunakan kode ini
                              </button>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Fuzzy / ambiguous — pick a candidate or enter a code manually */}
                      {needsCandidate && (
                        <div style={{ marginTop: '0.5rem' }}>
                          <div style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', marginBottom: '0.35rem' }}>
                            {m.type === 'fuzzy' ? 'Tidak ada kecocokan persis. Pilih kandidat atau masukkan kode manual:' : 'Lebih dari satu master cocok. Pilih kandidat atau masukkan kode manual:'}
                          </div>
                          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.3rem' }}>
                            {(m.candidates ?? []).map((c: MatchCandidate) => {
                              const selected = r.confirmed && r.resolvedCode === c.code;
                              return (
                                <button key={c.code} type="button"
                                  onClick={() => updatePriceRow(r.rowNum, { resolvedCode: c.code, confirmed: true })}
                                  style={{
                                    display: 'flex', alignItems: 'center', gap: '0.5rem', textAlign: 'left', width: '100%',
                                    padding: '0.35rem 0.55rem', borderRadius: '0.3rem', cursor: 'pointer',
                                    border: `1px solid ${selected ? '#3D5A3E' : 'var(--border)'}`,
                                    background: selected ? 'rgba(61,90,62,0.08)' : 'var(--bg-card)',
                                  }}>
                                  {selected && <Check size={12} style={{ color: '#2D4A2E', flexShrink: 0 }} />}
                                  <span style={{ fontFamily: 'monospace', fontWeight: 700, color: '#C9A84C', fontSize: '0.76rem' }}>{c.code}</span>
                                  <span style={{ fontSize: '0.76rem', color: 'var(--text-primary)' }}>{c.name}</span>
                                  <span style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>({c.category})</span>
                                  {c.price != null && <span style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>· Rp {fmtRp(c.price)}</span>}
                                  {m.type === 'fuzzy' && <span style={{ marginLeft: 'auto', fontSize: '0.68rem', fontWeight: 600, color: '#8B6914' }}>{Math.round(c.score * 100)}%</span>}
                                </button>
                              );
                            })}
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', marginTop: '0.4rem' }}>
                            <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>Atau kode manual:</span>
                            <input
                              type="text"
                              value={r.confirmed && !(m.candidates ?? []).some((c) => c.code === r.resolvedCode) ? r.resolvedCode : ''}
                              onChange={(e) => {
                                const code = e.target.value.trim();
                                updatePriceRow(r.rowNum, { resolvedCode: code, confirmed: code !== '' });
                              }}
                              placeholder="PLU code"
                              style={{ width: '140px', height: '30px', border: '1px solid var(--input-border)', borderRadius: '4px', background: 'var(--bg-card)', color: 'var(--text-primary)', padding: '0 0.5rem', fontSize: '0.78rem', outline: 'none', fontFamily: 'monospace' }}
                            />
                            {r.confirmed && (
                              <button type="button" onClick={() => updatePriceRow(r.rowNum, { confirmed: false, resolvedCode: '' })}
                                style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', textDecoration: 'underline', cursor: 'pointer', fontSize: '0.72rem' }}>Hapus pilihan</button>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Wine-only advisory flags (barcode integrity + active price levels) */}
                      {(() => {
                        const w = effectiveWineWarnings(r);
                        return <WineWarnings barcodeMismatch={w.barcodeMismatch} priceLevels={w.priceLevels} requestedPrice={r.price} />;
                      })()}
                    </div>
                  );
                })}

                {/* Rejected (no match) — separate section, never counts toward import */}
                {rejected.length > 0 && (
                  <div style={{ marginTop: '0.5rem', border: '1px solid rgba(122,46,31,0.2)', borderRadius: '0.375rem', overflow: 'hidden' }}>
                    <button type="button" onClick={() => setShowRejected((v) => !v)}
                      style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.6rem 0.875rem', background: 'rgba(122,46,31,0.05)', border: 'none', cursor: 'pointer' }}>
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.8rem', fontWeight: 600, color: '#7A2E1F' }}>
                        <AlertTriangle size={13} /> Ditolak — tidak ditemukan di master ({rejected.length})
                      </span>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>{showRejected ? 'Sembunyikan' : 'Tampilkan'}</span>
                    </button>
                    {showRejected && (
                      <div style={{ padding: '0.5rem 0.875rem' }}>
                        <p style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', margin: '0 0 0.5rem' }}>
                          Baris ini tidak diimport. Tangani secara manual sebagai permintaan item baru bila perlu.
                        </p>
                        <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '0.5rem' }}>
                          <button type="button"
                            onClick={() => {
                              const date = new Date().toISOString().slice(0, 10);
                              const csv = toCsv(
                                ['Name', 'Category', 'Department', 'Barcode', 'Price'],
                                rejected.map((r) => [r.name, r.category, r.department, r.barcode, r.price]),
                              );
                              downloadBlob(new Blob([csv], { type: 'text/csv;charset=utf-8' }), `import-ditolak-${date}.csv`);
                              toast.success('CSV diunduh');
                            }}
                            style={{ display: 'inline-flex', alignItems: 'center', gap: '0.35rem', padding: '0.3rem 0.7rem', background: 'transparent', border: '1px solid var(--border)', borderRadius: '0.3rem', fontSize: '0.74rem', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                            <Download size={12} /> Download CSV
                          </button>
                        </div>
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.74rem' }}>
                          <thead>
                            <tr style={{ textAlign: 'left', color: 'var(--text-secondary)' }}>
                              <th style={{ padding: '0.25rem 0.4rem', fontWeight: 600 }}>Nama</th>
                              <th style={{ padding: '0.25rem 0.4rem', fontWeight: 600 }}>Kategori</th>
                              <th style={{ padding: '0.25rem 0.4rem', fontWeight: 600 }}>Barcode</th>
                              <th style={{ padding: '0.25rem 0.4rem', fontWeight: 600, textAlign: 'right' }}>Harga</th>
                            </tr>
                          </thead>
                          <tbody>
                            {rejected.map((r) => (
                              <tr key={r.rowNum} style={{ borderTop: '1px solid var(--border)' }}>
                                <td style={{ padding: '0.3rem 0.4rem', color: 'var(--text-primary)' }}>{r.name || '—'}</td>
                                <td style={{ padding: '0.3rem 0.4rem', color: 'var(--text-secondary)' }}>{r.category || '—'}</td>
                                <td style={{ padding: '0.3rem 0.4rem', color: 'var(--text-secondary)', fontFamily: 'monospace' }}>{r.barcode || '—'}</td>
                                <td style={{ padding: '0.3rem 0.4rem', textAlign: 'right', color: 'var(--text-secondary)' }}>{r.price ? `Rp ${formatPriceDisplay(r.price)}` : '—'}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                )}
              </div>

              <div style={{ padding: '1rem 1.5rem', borderTop: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', flexShrink: 0 }}>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  {readyCount} dari {rows.length} baris siap diimport
                  {rejected.length > 0 && <span style={{ color: '#7A2E1F' }}> · {rejected.length} ditolak</span>}
                </span>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button onClick={() => setPriceImportModal({ open: false, rows: [] })}
                    style={{ padding: '0.5rem 1rem', background: 'transparent', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.8rem', cursor: 'pointer', color: 'var(--text-secondary)' }}>
                    Tutup
                  </button>
                  <button
                    onClick={confirmPriceImport}
                    disabled={readyCount === 0}
                    title={readyCount === 0 ? 'Belum ada baris yang siap diimport' : undefined}
                    style={{ padding: '0.5rem 1.25rem', background: readyCount > 0 ? 'var(--bg-dark)' : 'rgba(26,16,8,0.3)', border: 'none', borderRadius: '0.375rem', fontSize: '0.8rem', fontWeight: 600, cursor: readyCount > 0 ? 'pointer' : 'not-allowed', color: readyCount > 0 ? 'var(--accent-gold)' : 'rgba(201,168,76,0.4)' }}>
                    Import {readyCount} Baris
                  </button>
                </div>
              </div>
            </div>
          </>
        );
      })()}

      <SuccessModal
        isOpen={successModal.open}
        itemName={`${successModal.count} item${successModal.count !== 1 ? 's' : ''} submitted under "${successModal.title}"`}
        title="Batch Submitted"
        body="Your batch request has been received and is pending review."
        submitAnotherLabel="Submit Another Batch"
        onSubmitAnother={() => setSuccessModal({ open: false, title: '', count: 0 })}
        onViewRequests={() => { setSuccessModal({ open: false, title: '', count: 0 }); router.push('/cashier/dashboard'); }}
      />

      <h1 className="page-title" style={{ marginBottom: '0.375rem' }}>New Batch Request</h1>
      <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '1.75rem' }}>
        Submit multiple items in one batch. Group them by event or request context.
      </p>

      {configBanner}

      <form onSubmit={handleSubmit}>

        {/* Batch Header */}
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div>
              <label className="label-caps" style={{ display: 'block', marginBottom: '0.4rem' }}>Request Title</label>
              <input
                type="text" value={title} onChange={(e) => { setTitle(e.target.value); setTitleError(''); }}
                placeholder="e.g. New Request Item - Event WTT CORK" required
                style={{ ...INPUT_STYLE, height: '48px', fontSize: '1rem', borderColor: titleError ? 'rgba(122,46,31,0.5)' : undefined }}
              />
              {titleError && <p style={{ fontSize: '0.75rem', color: '#8B3A2A', marginTop: '0.3rem' }}>{titleError}</p>}
              <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.3rem' }}>Give this batch a name that describes what you&apos;re adding or updating.</p>
            </div>

            <div>
              <div className="label-caps" style={{ marginBottom: '0.75rem' }}>Request Type</div>
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {REQUEST_TYPES.map((t) => (
                  <button key={t.value} type="button"
                    onClick={() => { setRequestType(t.value); setItems([makeDefaultRow()]); setApplyHighlight(false); setPriceImportModal({ open: false, rows: [] }); }}
                    style={{ padding: '0.5rem 1rem', borderRadius: '0.375rem', border: `1px solid ${requestType === t.value ? 'var(--bg-dark)' : 'var(--border)'}`, background: requestType === t.value ? 'var(--bg-dark)' : 'transparent', color: requestType === t.value ? 'var(--accent-gold)' : 'var(--text-secondary)', fontSize: '0.8rem', fontWeight: requestType === t.value ? 500 : 400, cursor: 'pointer', transition: 'all 200ms ease' }}>
                    {t.label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Import from File */}
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
            <div className="section-title">Import from File</div>
            <button type="button" onClick={downloadTemplate}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '0.375rem', fontSize: '0.75rem', color: 'var(--text-secondary)', background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline' }}>
              <Download size={12} /> Download template
            </button>
          </div>

          <input ref={fileInputRef} type="file" accept=".xlsx,.csv" onChange={handleFileInput} style={{ display: 'none' }} />

          <div
            onClick={() => { if (!matching) fileInputRef.current?.click(); }}
            onDragOver={(e) => { e.preventDefault(); if (!matching) setIsDragOver(true); }}
            onDragLeave={() => setIsDragOver(false)}
            onDrop={(e) => { if (!matching) handleDrop(e); else e.preventDefault(); }}
            style={{
              border: `2px dashed ${isDragOver ? 'var(--accent-gold)' : 'var(--border)'}`,
              borderRadius: '0.5rem', padding: '1.5rem', textAlign: 'center', cursor: matching ? 'default' : 'pointer',
              background: isDragOver ? 'rgba(201,168,76,0.05)' : 'var(--bg-cream)',
              transition: 'all 200ms ease',
            }}
          >
            {matching ? (
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', color: 'var(--text-secondary)' }}>
                <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} />
                <span style={{ fontSize: '0.8rem' }}>Mencocokkan dengan master item…</span>
              </div>
            ) : (
              <>
                <Upload size={20} style={{ color: 'var(--text-secondary)', margin: '0 auto 0.5rem' }} />
                <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0 }}>
                  Drag & drop atau <span style={{ color: 'var(--accent-gold)', fontWeight: 500 }}>pilih file</span> (.xlsx atau .csv)
                </p>
                {requestType === 'UPDATE_PRICE' && (
                  <p style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', margin: '0.4rem 0 0', fontStyle: 'italic' }}>
                    Kode PLU akan dicocokkan otomatis dari Nama / Kategori / Barcode — kolom Code tidak diperlukan.
                  </p>
                )}
              </>
            )}
          </div>
        </div>

        {/* Global Apply card */}
        {showApplyCard && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem', ...(showApplyHighlight ? { border: '2px solid #C9A84C' } : {}) }}>
            <div style={{ marginBottom: '1rem' }}>
              <div className="section-title">Terapkan ke Semua Baris</div>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginTop: '0.25rem', marginBottom: 0 }}>
                {(showAnyOutlets || showPrintersCol)
                  ? 'Pilih outlet, printer, atau remarks yang akan diterapkan ke seluruh baris sekaligus.'
                  : 'Isi remarks yang akan diterapkan ke seluruh baris sekaligus.'}
              </p>
              {showApplyHighlight && (
                <p style={{ fontSize: '0.8rem', color: '#92400E', marginTop: '0.375rem', marginBottom: 0, fontWeight: 500 }}>
                  Outlet dan printer belum diisi. Gunakan bagian ini untuk mengisi semua baris sekaligus.
                </p>
              )}
            </div>

            {(showAnyOutlets || showPrintersCol) && (
              <>
                <div style={{ display: 'flex', gap: '1rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
                  {showAnyOutlets && (
                    <div style={{ flex: 1, minWidth: '200px' }}>
                      <div className="label-caps" style={{ marginBottom: '0.4rem' }}>Outlets</div>
                      <MultiSelect options={configOutlets} value={globalOutlets} onChange={setGlobalOutlets} placeholder="Pilih outlet..." />
                    </div>
                  )}
                  {showPrintersCol && (
                    <div style={{ flex: 1, minWidth: '200px' }}>
                      <div className="label-caps" style={{ marginBottom: '0.4rem' }}>Printers</div>
                      <MultiSelect options={availablePrinters} value={globalPrinters} onChange={setGlobalPrinters} placeholder="Pilih printer..." />
                    </div>
                  )}
                </div>

                <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                  <button
                    type="button"
                    onClick={() => {
                      const n = items.length;
                      setItems((prev) => prev.map((r) => {
                        const next = {
                          ...r,
                          ...(showAnyOutlets ? { outlets: globalOutlets } : {}),
                          ...(showPrintersCol ? { printers: globalPrinters } : {}),
                        };
                        // Re-derive the prefix/code for NEW_ITEM auto rows from the newly-applied outlets.
                        if (requestType === 'NEW_ITEM' && next.codeIsAutoGenerated && next.category) {
                          next.code = '';
                          next.codeLoading = true;
                        }
                        return next;
                      }));
                      toast.success(`Diterapkan ke ${n} baris`);
                    }}
                    style={{ padding: '0.5rem 1.25rem', background: 'var(--bg-dark)', color: 'var(--accent-gold)', border: 'none', borderRadius: '0.375rem', fontSize: '0.8rem', fontWeight: 600, cursor: 'pointer' }}
                  >
                    Terapkan ke Semua Baris
                  </button>
                </div>

                {showGlobalMultiPrefixNotice && (
                  <div style={{ marginTop: '0.75rem', padding: '0.5rem 0.75rem', borderRadius: '0.375rem', background: 'rgba(201,168,76,0.08)', border: '1px solid rgba(201,168,76,0.25)', fontSize: '0.78rem', color: '#8B6914' }}>
                    Outlet dipilih memiliki {globalPrefixCount} prefix berbeda. Setiap baris akan menghasilkan {globalPrefixCount} item terpisah.
                  </div>
                )}
              </>
            )}

            {showGlobalRemarks && (
              <div style={{ marginTop: (showAnyOutlets || showPrintersCol) ? '1.25rem' : 0, paddingTop: (showAnyOutlets || showPrintersCol) ? '1.25rem' : 0, borderTop: (showAnyOutlets || showPrintersCol) ? '1px solid var(--border)' : undefined }}>
                <div className="label-caps" style={{ marginBottom: '0.4rem' }}>REMARKS (opsional)</div>
                <input
                  type="text" value={globalRemarks} onChange={(e) => setGlobalRemarks(e.target.value)}
                  placeholder="Catatan untuk semua baris..."
                  style={INPUT_STYLE}
                />
                <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '0.75rem' }}>
                  <button
                    type="button"
                    onClick={() => {
                      const n = items.length;
                      setItems((prev) => prev.map((r) => ({ ...r, remarks: globalRemarks })));
                      toast.success(`Remarks diterapkan ke ${n} baris`);
                    }}
                    style={{ padding: '0.375rem 0.875rem', background: 'transparent', color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.75rem', fontWeight: 500, cursor: 'pointer' }}
                  >
                    Terapkan Remarks ke Semua
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Items Table */}
        <div className="card" style={{ marginBottom: '1rem', overflow: 'hidden' }}>
          <div style={{ padding: '1rem 1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem' }}>
              <span className="section-title">Items</span>
              <span style={{ background: 'var(--bg-dark)', color: 'var(--accent-gold)', fontSize: '0.7rem', fontWeight: 600, padding: '0.1rem 0.5rem', borderRadius: '9999px' }}>
                {items.length}
              </span>
              {!isRemovePLU && (
                <span style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', fontStyle: 'italic' }}>
                  ← scroll right for printers, outlets & POS settings
                </span>
              )}
            </div>
            <button type="button" onClick={addRow} disabled={configLoading}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '0.375rem', padding: '0.375rem 0.875rem', background: 'transparent', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.8rem', color: 'var(--text-secondary)', cursor: configLoading ? 'not-allowed' : 'pointer', flexShrink: 0, opacity: configLoading ? 0.5 : 1 }}>
              <Plus size={13} /> Add Row
            </button>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ tableLayout: 'auto', minWidth: isRemovePLU ? '600px' : '900px' }}>
              <thead>
                <tr>
                  <th style={{ width: '36px', textAlign: 'center' }}>#</th>
                  {/* REMOVE_PLU columns */}
                  {isRemovePLU && <th style={{ minWidth: '200px' }}>PLU Code</th>}
                  {isRemovePLU && <th style={{ minWidth: '180px' }}>Item Name</th>}
                  {isRemovePLU && <th style={{ minWidth: '120px' }}>Folder</th>}
                  {isRemovePLU && <th style={{ minWidth: '200px' }}>Remarks</th>}
                  {/* Standard columns */}
                  {!isRemovePLU && (isUpdate || requestType === 'NEW_ITEM') && <th style={{ minWidth: '160px' }}>PLU Code</th>}
                  {!isRemovePLU && showCurrentRefCols && <th style={{ minWidth: '170px' }}>Current Name</th>}
                  {!isRemovePLU && showCurrentRefCols && <th style={{ minWidth: '140px' }}>Current Price</th>}
                  {!isRemovePLU && showNameCol && <th style={{ minWidth: '180px' }}>{requestType === 'UPDATE_NAME' ? 'New Name' : 'Name'}</th>}
                  {!isRemovePLU && showCategoryCol && <th style={{ minWidth: '160px' }}>Category</th>}
                  {!isRemovePLU && showCategoryCol && <th style={{ minWidth: '90px' }}>Dept</th>}
                  {!isRemovePLU && showPriceCol && <th style={{ minWidth: '170px' }}>{requestType === 'UPDATE_PRICE' ? 'New Price (IDR)' : 'Price (IDR)'}</th>}
                  {!isRemovePLU && showBarcodeColumn && <th style={{ minWidth: '100px' }}>Barcode</th>}
                  {!isRemovePLU && showFolderCol && <th style={{ minWidth: '120px' }}>Folder</th>}
                  {!isRemovePLU && showPrintersCol && <th style={{ minWidth: '155px' }}>Printers</th>}
                  {!isRemovePLU && showOutletsCol && <th style={{ minWidth: '140px' }}>Outlets</th>}
                  {!isRemovePLU && showPOSCol && <th style={{ minWidth: '110px' }}>Sales Def</th>}
                  {!isRemovePLU && showPOSCol && <th style={{ minWidth: '150px' }}>POS</th>}
                  {!isRemovePLU && showRemarksCol && <th style={{ minWidth: '200px' }}>Remarks</th>}
                  {showUpdateOutletsCol && <th style={{ minWidth: '140px' }}>Outlets</th>}
                  <th style={{ width: '66px' }}></th>
                </tr>
              </thead>
              <tbody>
                {items.map((row, idx) => {
                  const hasError = Object.keys(row.errors).length > 0;
                  // Prefix groups for this row's outlets (NEW_ITEM only). >1 means the row
                  // expands into that many separate items at submit.
                  const rowGroups = requestType === 'NEW_ITEM' ? derivePrefixGroups(row.category, row.outlets, categoryCodeMap) : [];
                  const rowMulti = rowGroups.length > 1;
                  return (
                    <tr key={row._id} style={{ borderLeft: hasError ? '2px solid rgba(122,46,31,0.6)' : undefined, verticalAlign: 'top' }}>
                      <td style={{ textAlign: 'center', fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 600, paddingTop: '0.6rem' }}>{idx + 1}</td>

                      {/* REMOVE_PLU rows */}
                      {isRemovePLU && (
                        <>
                          <td>
                            <PLUCodeSearch
                              value={row.code}
                              onChange={(code) => handleCodeSearchChange(idx, code)}
                              onItemSelect={(item) => handleCodeItemSelect(idx, item)}
                              placeholder="Search PLU code..."
                              error={row.errors.code}
                            />
                            {row.errors.code && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.code}</p>}
                          </td>
                          <td>
                            <input type="text" value={row.name} readOnly placeholder="Auto-populated"
                              style={{ ...INPUT_STYLE, background: 'var(--bg-cream)', color: row.name ? 'var(--text-primary)' : 'var(--text-secondary)', fontSize: '0.75rem' }} />
                          </td>
                          <td>
                            <input type="text" value={row.folder} readOnly placeholder="Auto-populated"
                              style={{ ...INPUT_STYLE, background: 'var(--bg-cream)', color: row.folder ? 'var(--text-primary)' : 'var(--text-secondary)', fontSize: '0.75rem' }} />
                          </td>
                          <td>
                            <input type="text" value={row.remarks} onChange={(e) => updateRow(idx, 'remarks', e.target.value)}
                              placeholder="Alasan penghapusan..."
                              style={{ ...INPUT_STYLE, borderColor: row.errors.remarks ? 'rgba(122,46,31,0.5)' : undefined }} />
                            {row.errors.remarks && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.remarks}</p>}
                          </td>
                        </>
                      )}

                      {/* Standard columns */}
                      {!isRemovePLU && isUpdate && (
                        <td>
                          <PLUCodeSearch
                            value={row.code}
                            onChange={(code) => handleCodeSearchChange(idx, code)}
                            onItemSelect={(item) => handleCodeItemSelect(idx, item)}
                            placeholder="PLU code"
                            error={row.errors.code}
                          />
                          {row.errors.code && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.code}</p>}
                        </td>
                      )}

                      {!isRemovePLU && requestType === 'NEW_ITEM' && (
                        <td style={{ minWidth: '160px', padding: '6px 10px', verticalAlign: 'middle' }}>
                          {rowMulti ? (
                            <div>
                              <div style={{ fontSize: '0.72rem', fontWeight: 600, color: '#8B6914', whiteSpace: 'nowrap' }}>
                                {rowGroups.length} item akan dibuat
                              </div>
                              <div style={{ fontSize: '0.68rem', color: 'var(--text-secondary)', fontFamily: 'monospace', marginTop: '2px' }}>
                                {rowGroups.map((g) => g.prefix).join(' · ')}
                              </div>
                            </div>
                          ) : (
                            <div style={{ fontFamily: 'monospace', fontSize: '0.78rem', fontWeight: 600, letterSpacing: '0.03em', color: '#C9A84C', whiteSpace: 'nowrap' }}>
                              {row.codeLoading ? '…' : (row.code || '—')}
                            </div>
                          )}
                        </td>
                      )}

                      {!isRemovePLU && showCurrentRefCols && (
                        <td>
                          <PLUCodeSearch
                            mode="name"
                            value={row.currentName}
                            onChange={(name) => handleNameSearchChange(idx, name)}
                            onItemSelect={(item) => handleCodeItemSelect(idx, item)}
                            placeholder="Search item name..."
                          />
                        </td>
                      )}

                      {!isRemovePLU && showCurrentRefCols && (
                        <td>
                          <input type="text" value={row.currentPrice ? `Rp ${formatPriceDisplay(row.currentPrice)}` : ''} readOnly placeholder="—"
                            style={{ ...INPUT_STYLE, background: 'var(--bg-cream)', color: row.currentPrice ? 'var(--text-primary)' : 'var(--text-secondary)', fontSize: '0.75rem' }} />
                        </td>
                      )}

                      {!isRemovePLU && showNameCol && (
                        <td>
                          <input type="text" value={row.name} onChange={(e) => updateRow(idx, 'name', e.target.value)} placeholder="Item name"
                            style={{ ...INPUT_STYLE, borderColor: row.errors.name ? 'rgba(122,46,31,0.5)' : undefined }} />
                          {row.errors.name && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.name}</p>}
                        </td>
                      )}

                      {!isRemovePLU && showCategoryCol && (
                        <td>
                          <Combobox options={categoryOptions} value={row.category} onChange={(v) => updateRow(idx, 'category', v)} placeholder="Category..." searchPlaceholder="Search..." />
                        </td>
                      )}

                      {!isRemovePLU && showCategoryCol && (
                        <td>
                          <input type="text" value={row.department} readOnly style={{ ...INPUT_STYLE, background: 'var(--bg-cream)', fontSize: '0.75rem' }} />
                        </td>
                      )}

                      {!isRemovePLU && showPriceCol && (
                        <td>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                            <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', flexShrink: 0 }}>Rp</span>
                            <input type="text" inputMode="numeric" value={formatPriceDisplay(row.price)}
                              onChange={(e) => updateRow(idx, 'price', e.target.value.replace(/\D/g, ''))}
                              placeholder="0"
                              style={{ ...INPUT_STYLE, flex: 1, minWidth: '140px', borderColor: row.errors.price ? 'rgba(122,46,31,0.5)' : undefined }} />
                          </div>
                          {row.errors.price && <p style={{ fontSize: '0.7rem', color: '#8B3A2A', margin: '2px 0 0' }}>{row.errors.price}</p>}
                        </td>
                      )}

                      {!isRemovePLU && showBarcodeColumn && (
                        <td>
                          {row.department === 'WINE' ? (
                            <input type="text" value={row.barcode} onChange={(e) => updateRow(idx, 'barcode', e.target.value)} placeholder="Barcode" style={INPUT_STYLE} />
                          ) : null}
                        </td>
                      )}

                      {!isRemovePLU && showFolderCol && (
                        <td>
                          <input type="text" value={row.folder} onChange={(e) => updateRow(idx, 'folder', e.target.value)} placeholder="Folder" style={INPUT_STYLE} />
                        </td>
                      )}

                      {!isRemovePLU && showPrintersCol && (
                        <td>
                          <MultiSelect options={availablePrinters} value={row.printers} onChange={(v) => updateRow(idx, 'printers', v)} placeholder="Printers…" error={row.errors.printers} />
                        </td>
                      )}

                      {!isRemovePLU && showOutletsCol && (
                        <td>
                          <MultiSelect options={configOutlets} value={row.outlets} onChange={(v) => updateRow(idx, 'outlets', v)} placeholder="Outlets…" error={row.errors.outlets} />
                        </td>
                      )}

                      {!isRemovePLU && showPOSCol && (
                        <td>
                          <select value={row.salesDef} onChange={(e) => updateRow(idx, 'salesDef', e.target.value)} style={INPUT_STYLE}>
                            <option value="SALES">SALES</option>
                            <option value="MODIFIER">MODIFIER</option>
                          </select>
                        </td>
                      )}

                      {!isRemovePLU && showPOSCol && (
                        <td>
                          <MultiSelect
                            options={POS_FIELDS.map((f) => f.full)}
                            value={POS_FIELDS.filter((f) => row[f.key] as boolean).map((f) => f.full)}
                            onChange={(selected) => {
                              setItems((prev) => prev.map((r, i) => {
                                if (i !== idx) return r;
                                const updates: Partial<ItemRow> = {};
                                POS_FIELDS.forEach(({ key, full }) => { (updates as any)[key] = selected.includes(full); });
                                return { ...r, ...updates };
                              }));
                            }}
                            placeholder="POS Settings..."
                          />
                        </td>
                      )}

                      {!isRemovePLU && showRemarksCol && (
                        <td>
                          <input type="text" value={row.remarks} onChange={(e) => updateRow(idx, 'remarks', e.target.value)}
                            placeholder="Catatan..." style={INPUT_STYLE} />
                        </td>
                      )}

                      {showUpdateOutletsCol && (
                        <td>
                          <MultiSelect options={configOutlets} value={row.outlets} onChange={(v) => updateRow(idx, 'outlets', v)} placeholder="Outlets…" />
                        </td>
                      )}

                      <td style={{ paddingTop: '0.5rem' }}>
                        <div style={{ display: 'flex', gap: '0.25rem', justifyContent: 'center' }}>
                          <button type="button" onClick={() => duplicateRow(idx)} title="Duplicate row"
                            style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: '3px', padding: '0.25rem 0.4rem', cursor: 'pointer', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center' }}>
                            <Copy size={11} />
                          </button>
                          <button type="button" onClick={() => deleteRow(idx)} title={items.length <= 1 ? 'Cannot remove the last item' : 'Delete row'}
                            style={{ background: 'transparent', border: `1px solid ${items.length <= 1 ? 'var(--border)' : 'rgba(139,58,42,0.25)'}`, borderRadius: '3px', padding: '0.25rem 0.4rem', cursor: items.length <= 1 ? 'not-allowed' : 'pointer', color: items.length <= 1 ? 'var(--text-secondary)' : '#7A2E1F', display: 'flex', alignItems: 'center', opacity: items.length <= 1 ? 0.4 : 1 }}>
                            <Trash2 size={11} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Duplicate PLU code warning */}
        {requestType === 'NEW_ITEM' && (() => {
          const autoCodes = items.filter((r) => r.codeIsAutoGenerated && r.code).map((r) => r.code);
          const dupes = Array.from(new Set(autoCodes.filter((c, i) => autoCodes.indexOf(c) !== i)));
          if (dupes.length === 0) return null;
          return (
            <div style={{ marginBottom: '0.75rem', padding: '0.625rem 0.875rem', borderRadius: '0.375rem', background: 'rgba(122,46,31,0.07)', border: '1px solid rgba(122,46,31,0.25)', fontSize: '0.8rem', color: '#8B3A2A' }}>
              Duplicate PLU codes detected: {dupes.join(', ')}. Check outlet/category selection.
            </div>
          );
        })()}

        {/* Submit bar */}
        <div className="card" style={{ padding: '1rem 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}>
          <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
            <strong style={{ color: 'var(--text-primary)' }}>{items.length}</strong> item{items.length !== 1 ? 's' : ''} ready to submit
          </span>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button type="submit" disabled={loading || configLoading || !!configError}
              style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.625rem 1.5rem', background: (loading || configLoading || configError) ? 'rgba(26,16,8,0.5)' : 'var(--bg-dark)', color: 'var(--accent-gold)', border: 'none', borderRadius: '0.375rem', fontSize: '0.875rem', fontWeight: 600, cursor: (loading || configLoading || configError) ? 'not-allowed' : 'pointer' }}>
              {loading && <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />}
              {loading ? 'Submitting…' : 'Submit Batch'}
            </button>
            <button type="button" onClick={() => { setTitle(''); setItems([makeDefaultRow()]); }}
              style={{ padding: '0.625rem 1.125rem', background: 'transparent', color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.875rem', cursor: 'pointer' }}>
              Clear
            </button>
          </div>
        </div>

      </form>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
