import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/session';
import { getPLURequests, createPLURequest, getMasterItemByCode, getAllSapItemsForMatch, getMaxExistingBarcode, getBarcodeOccupancy } from '@/lib/db';
import { createRequestSchema } from '@/lib/validations';
import { loadOutletPrefixMap, loadCategoryCodeMap } from '@/lib/configLoader';
import { shouldRouteToCostControl, suggestBarcode, isWineEventCategory, STATUS_PENDING_COST_CONTROL, BARCODE_SOURCE_CASHIER } from '@/lib/costControl';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function GET() {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const requests = await getPLURequests({ userId: session.user.id, limit: 500 });
    return NextResponse.json(requests);
  } catch (error) {
    console.error('[GET /api/requests]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await request.json();
    const parsed = createRequestSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: 'Validation failed', issues: parsed.error.issues }, { status: 400 });
    }

    const data = parsed.data;

    if (data.requestType === 'NEW_ITEM') {
      const [outletPrefixMap, categoryCodeMap] = await Promise.all([
        loadOutletPrefixMap(),
        loadCategoryCodeMap(),
      ]);
      if (Object.keys(outletPrefixMap).length === 0 || Object.keys(categoryCodeMap).length === 0) {
        return NextResponse.json(
          { error: 'Konfigurasi sistem tidak tersedia. Hubungi administrator.' },
          { status: 500 }
        );
      }
    }

    // Cost Control routing — only WINE NEW_ITEM from a Cork cashier diverts to PENDING_COST_CONTROL.
    // Every other path is untouched and follows the normal PENDING flow.
    const routeToCostControl = shouldRouteToCostControl(
      data.requestType, data.department, session.user.outlet, data.category,
    );
    let suggestedBarcode: string | null = null;
    let suggestedBarcodeSource: string | null = null;
    // Defensive: Wine Event never generates a barcode even if some future routing change lets it in.
    if (routeToCostControl && !isWineEventCategory(data.category)) {
      const cashierBarcode = data.barcode ?? null;
      if (cashierBarcode && cashierBarcode.trim() !== '') {
        // Trust the cashier's barcode 100% — no SAP fuzzy match, no NCK derivation, no sequential
        // fallback. Their submitted value IS the suggestion.
        suggestedBarcode = cashierBarcode;
        suggestedBarcodeSource = BARCODE_SOURCE_CASHIER;
      } else {
        // No cashier barcode — derive one. Load occupancy as late as possible (immediately before
        // generation + create) to minimise the window where a concurrent request could claim the same
        // barcode. sql.js writes are serialised under a single-process write lock, so this plus the
        // persisted-suggestion occupancy check is the tightest guard available without a cross-request lock.
        const [saps, maxBarcode, occupancy] = await Promise.all([
          getAllSapItemsForMatch(),
          getMaxExistingBarcode(),
          getBarcodeOccupancy(),
        ]);
        const suggestion = suggestBarcode(data.name, saps, maxBarcode, occupancy);
        suggestedBarcode = suggestion.value;
        suggestedBarcodeSource = suggestion.source;
      }
    }

    const pluRequest = await createPLURequest({
      requestType: data.requestType,
      code: data.code ?? null,
      codeIsAutoGenerated: data.codeIsAutoGenerated,
      name: data.name,
      category: data.category,
      department: data.department,
      price: data.price ?? null,
      folder: data.folder ?? null,
      serviceCharge: data.serviceCharge,
      tax1: data.tax1,
      tax2: data.tax2,
      noDiscount: data.noDiscount,
      hideReceipt: data.hideReceipt,
      printers: data.printers,
      outlets: data.outlets,
      barcode: isWineEventCategory(data.category)
        ? null
        : data.department === 'WINE' ? (data.barcode ?? null) : null,
      status: routeToCostControl ? STATUS_PENDING_COST_CONTROL : undefined,
      suggestedBarcode,
      suggestedBarcodeSource,
      salesDef: data.salesDef ?? 'SALES',
      remarks: data.remarks ?? null,
      userId: session.user.id,
      outletGroup: session.user.outletGroup,
      cashierOutlet: session.user.outlet,
    });

    let warning: string | undefined;
    if (data.requestType === 'NEW_ITEM' && data.code) {
      const existing = await getMasterItemByCode(data.code);
      if (existing) {
        warning = `Code ${data.code} already exists in the master registry as '${existing.name}'. Admin will review.`;
      }
    }

    return NextResponse.json({ ...pluRequest, warning }, { status: 201 });
  } catch (error) {
    console.error('[POST /api/requests]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
