'use client';

import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Lock, LockOpen, AlertTriangle, Info } from 'lucide-react';
import { suggestPLUCode, assemblePLUCode, OUTLET_TO_PREFIX, KNOWN_PREFIXES, CATEGORY_CODE_MAP, hasFallbackPrefix } from '@/lib/pluCode';

interface Props {
  category: string;
  cashierOutlet: string;
  selectedOutlets: string[];
  onValueChange: (code: string, isAutoGenerated: boolean) => void;
  isAdmin?: boolean;
}

const VALID_DEPT_CODES = new Set([10, 20, 30, 40, 50, 60, 70, 80, 90]);

function validateManualCode(code: string): string | null {
  if (code.length !== 16) return 'Code must be exactly 16 characters';
  const prefix = code.slice(0, 3);
  if (!KNOWN_PREFIXES.includes(prefix)) return `Unknown prefix "${prefix}"`;
  const dept = parseInt(code.slice(3, 5), 10);
  if (!VALID_DEPT_CODES.has(dept)) return `Invalid department code "${code.slice(3, 5)}"`;
  const catCode = parseInt(code.slice(5, 8), 10);
  const validCats = CATEGORY_CODE_MAP.filter((e) => e.departmentCode === dept).map((e) => e.categoryCode);
  if (!validCats.includes(catCode)) return `Category code "${code.slice(5, 8)}" not valid for dept ${dept}`;
  if (!/^\d{8}$/.test(code.slice(8))) return 'Last 8 characters must be digits';
  return null;
}

export function PLUCodeSection({ category, cashierOutlet, selectedOutlets, onValueChange, isAdmin = false }: Props) {
  const [locked, setLocked] = useState(!isAdmin);
  const [manualCode, setManualCode] = useState('');
  const [showRelockConfirm, setShowRelockConfirm] = useState(false);
  const [fetchedSeq, setFetchedSeq] = useState<number | null>(null);
  const [seqLoading, setSeqLoading] = useState(false);

  // Recompute suggestion with the fetched (or placeholder) sequence
  const suggestion = suggestPLUCode(category, cashierOutlet, selectedOutlets, fetchedSeq ?? 4000);
  const suggestedCode = suggestion?.code ?? '';

  // Stable ref for onValueChange so effects don't depend on it directly
  const onValueChangeRef = useRef(onValueChange);
  useLayoutEffect(() => { onValueChangeRef.current = onValueChange; });

  // Fetch the real next-sequence from the API whenever the key inputs change
  const depKey = `${category}|${cashierOutlet}|${[...selectedOutlets].sort().join(',')}`;
  useEffect(() => {
    const s = suggestPLUCode(category, cashierOutlet, selectedOutlets, 4000);
    if (!s) {
      setSeqLoading(false);
      return;
    }
    setFetchedSeq(null);
    setSeqLoading(true);
    const { prefix, deptCode, catCode } = s;
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(
          `/api/plu/next-sequence?prefix=${encodeURIComponent(prefix)}&deptCode=${encodeURIComponent(deptCode)}&catCode=${encodeURIComponent(catCode)}`
        );
        const data = res.ok ? await res.json() : {};
        setFetchedSeq(typeof data.sequence === 'number' ? data.sequence : 4000);
      } catch {
        setFetchedSeq(4000);
      } finally {
        setSeqLoading(false);
      }
    }, 300);
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [depKey]);

  // Notify parent only once we have a real sequence (not while loading)
  useEffect(() => {
    if (locked) {
      if (!seqLoading && suggestedCode) {
        onValueChangeRef.current(suggestedCode, true);
      }
    } else {
      onValueChangeRef.current(manualCode, false);
    }
  }, [locked, suggestedCode, manualCode, seqLoading]);

  function handleUnlock() {
    setManualCode(suggestedCode);
    setLocked(false);
    setShowRelockConfirm(false);
  }

  function handleLockButtonClick() {
    if (locked) {
      // Locked → unlock
      handleUnlock();
    } else {
      // Unlocked → try to relock
      if (manualCode && manualCode !== suggestedCode) {
        setShowRelockConfirm(true);
      } else {
        setLocked(true);
      }
    }
  }

  function handleRelockYes() {
    setShowRelockConfirm(false);
    setLocked(true);
  }

  function handleRelockKeepManual() {
    setShowRelockConfirm(false);
    // stay unlocked, manual value preserved
  }

  function handleUnlockAndChangePrefix() {
    if (!suggestion) return;
    const outletPrefix = OUTLET_TO_PREFIX[cashierOutlet] ?? 'UNI';
    const newCode = assemblePLUCode(outletPrefix, suggestion.deptCode, suggestion.catCode, fetchedSeq ?? 4000);
    setManualCode(newCode);
    setLocked(false);
    setShowRelockConfirm(false);
  }

  const manualValidationError = !locked && manualCode ? validateManualCode(manualCode) : null;
  const seqNum = !locked && manualCode.length === 16 ? parseInt(manualCode.slice(8), 10) : NaN;
  const showSeqWarning = !isNaN(seqNum) && seqNum < 4000;

  if (!category) return null;

  if (!suggestion) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
        <label className="label-caps">PLU Code (Auto-Generated)</label>
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          padding: '0.625rem 0.875rem', borderRadius: '0.375rem',
          border: '1px dashed rgba(122,46,31,0.4)', background: 'rgba(122,46,31,0.06)',
        }}>
          <AlertTriangle size={14} style={{ color: '#8B3A2A', flexShrink: 0 }} />
          <span style={{ fontSize: '0.8rem', color: '#8B3A2A' }}>
            Code cannot be generated for this category. Please enter manually.
          </span>
        </div>
        <input
          type="text"
          value={manualCode}
          onChange={(e) => setManualCode(e.target.value.toUpperCase())}
          placeholder="e.g. ROM1010800000027"
          className="flex h-10 w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200"
          style={{ fontFamily: 'monospace' }}
        />
      </div>
    );
  }

  const showFallbackWarning = !locked && hasFallbackPrefix(cashierOutlet);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
      <label className="label-caps">PLU Code (Auto-Generated)</label>

      {/* Code display / input */}
      <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'stretch' }}>
        {locked ? (
          <div style={{
            flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '0 0.875rem', height: '40px', borderRadius: '0.375rem',
            border: '1px dashed #C9A84C', background: '#1A1008',
            fontFamily: 'monospace', fontSize: '0.875rem', color: '#C9A84C',
            letterSpacing: '0.04em', userSelect: 'all',
          }}>
            {seqLoading ? (
              <span style={{ opacity: 0.45 }}>
                {suggestion ? `${suggestion.prefix}${suggestion.deptCode}${suggestion.catCode}…` : '…'}
              </span>
            ) : (
              <span>{suggestedCode}</span>
            )}
            <Lock size={14} style={{ color: 'rgba(201,168,76,0.5)', flexShrink: 0 }} />
          </div>
        ) : (
          <input
            type="text"
            value={manualCode}
            onChange={(e) => setManualCode(e.target.value.toUpperCase())}
            maxLength={16}
            className="flex h-10 w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200"
            style={{ flex: 1, fontFamily: 'monospace' }}
            placeholder="e.g. ROM1010800000027"
          />
        )}

        <button
          type="button"
          onClick={handleLockButtonClick}
          title={locked ? 'Unlock to edit manually' : 'Re-lock to auto-generate'}
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            width: '40px', height: '40px', flexShrink: 0, borderRadius: '0.375rem',
            border: `1px solid ${locked ? '#C9A84C' : 'var(--border)'}`,
            background: locked ? 'rgba(201,168,76,0.1)' : 'transparent',
            color: locked ? '#C9A84C' : 'var(--text-secondary)',
            cursor: 'pointer', transition: 'all 200ms ease',
          }}
        >
          {locked ? <Lock size={15} /> : <LockOpen size={15} />}
        </button>
      </div>

      {/* Prefix reason badge (locked state only) */}
      {locked && suggestion && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          <span style={{
            fontSize: '0.68rem', letterSpacing: '0.06em', textTransform: 'uppercase',
            color: 'var(--text-secondary)', fontWeight: 500,
          }}>
            {suggestion.reason}
          </span>
        </div>
      )}

      {/* TUG callout */}
      {locked && suggestion.isTUG && (
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.625rem',
          padding: '0.5rem 0.75rem', borderRadius: '0.375rem',
          background: 'rgba(201,168,76,0.08)', border: '1px solid rgba(201,168,76,0.25)',
        }}>
          <Info size={13} style={{ color: '#C9A84C', flexShrink: 0 }} />
          <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', flex: 1 }}>
            This item is classified as a group beverage (TUG). Unlock to use your outlet&apos;s prefix instead.
          </span>
          <button
            type="button"
            onClick={handleUnlockAndChangePrefix}
            style={{
              fontSize: '0.7rem', color: '#C9A84C', background: 'none', border: 'none',
              cursor: 'pointer', whiteSpace: 'nowrap', fontWeight: 500, padding: 0,
            }}
          >
            Unlock & change prefix
          </button>
        </div>
      )}

      {/* Fallback warning */}
      {showFallbackWarning && (
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          padding: '0.4rem 0.625rem', borderRadius: '0.25rem',
          background: 'rgba(122,46,31,0.07)', border: '1px solid rgba(122,46,31,0.2)',
        }}>
          <AlertTriangle size={12} style={{ color: '#8B3A2A', flexShrink: 0 }} />
          <span style={{ fontSize: '0.72rem', color: '#8B3A2A' }}>
            Outlet {cashierOutlet} has no prefix mapping — using UNI as fallback. Verify with your manager.
          </span>
        </div>
      )}

      {/* Manual mode warning */}
      {!locked && (
        <div style={{
          display: 'flex', alignItems: 'flex-start', gap: '0.5rem',
          padding: '0.5rem 0.75rem', borderRadius: '0.375rem',
          background: 'rgba(122,46,31,0.06)', border: '1px solid rgba(122,46,31,0.2)',
        }}>
          <AlertTriangle size={13} style={{ color: '#8B3A2A', flexShrink: 0, marginTop: '1px' }} />
          <span style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>
            You are manually overriding the suggested PLU code. Ensure the code follows the format
            PREFIX(3) + DEPT(2) + CAT(3) + SEQ(8) and does not conflict with existing Quinos items.
          </span>
        </div>
      )}

      {manualValidationError && (
        <p style={{ fontSize: '0.72rem', color: '#8B3A2A', margin: 0 }}>{manualValidationError}</p>
      )}

      {showSeqWarning && (
        <p style={{ fontSize: '0.72rem', color: '#8B6A2A', margin: 0 }}>
          Sequence below 4000 — this may conflict with existing Quinos items. Numbers below 4000 are reserved for pre-existing PLUs.
        </p>
      )}

      {/* Re-lock confirmation */}
      {showRelockConfirm && (
        <div style={{
          padding: '0.75rem', borderRadius: '0.375rem',
          border: '1px solid var(--border)', background: 'var(--bg-card)',
          display: 'flex', flexDirection: 'column', gap: '0.625rem',
        }}>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-primary)', margin: 0 }}>
            Reset to suggested code?
          </p>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button
              type="button"
              onClick={handleRelockYes}
              style={{
                padding: '0.375rem 0.875rem', fontSize: '0.8rem', fontWeight: 500,
                background: 'var(--bg-dark)', color: 'var(--accent-gold)',
                border: 'none', borderRadius: '0.25rem', cursor: 'pointer',
              }}
            >
              Yes, reset
            </button>
            <button
              type="button"
              onClick={handleRelockKeepManual}
              style={{
                padding: '0.375rem 0.875rem', fontSize: '0.8rem',
                background: 'transparent', color: 'var(--text-secondary)',
                border: '1px solid var(--border)', borderRadius: '0.25rem', cursor: 'pointer',
              }}
            >
              Keep manual
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
