export interface CategoryEntry {
  department: string;
  category: string;
}

export const STANDARD_CATEGORIES: CategoryEntry[] = [
  // FOOD
  { department: 'FOOD', category: 'Asian' },
  { department: 'FOOD', category: 'Grilled' },
  { department: 'FOOD', category: 'Mains' },
  { department: 'FOOD', category: 'Pasta' },
  { department: 'FOOD', category: 'Sandwich' },
  { department: 'FOOD', category: 'Snack' },
  { department: 'FOOD', category: 'Starter' },
  { department: 'FOOD', category: 'Side Dishes' },
  { department: 'FOOD', category: 'Salad' },
  { department: 'FOOD', category: 'Dessert Food' },
  { department: 'FOOD', category: 'Special' },
  { department: 'FOOD', category: 'Food Event' },
  { department: 'FOOD', category: 'Food Promo' },
  { department: 'FOOD', category: 'Additional Food' },
  { department: 'FOOD', category: 'Special Feast' },
  { department: 'FOOD', category: 'Breakfast' },
  { department: 'FOOD', category: 'Pizza' },
  { department: 'FOOD', category: 'Modifier Food' },
  { department: 'FOOD', category: 'U+Reward Food' },
  { department: 'FOOD', category: 'Tapas' },
  { department: 'FOOD', category: 'Brunch' },
  { department: 'FOOD', category: 'Complimentary Food' },
  { department: 'FOOD', category: 'Set Menu' },
  // ALCOHOLIC BEVERAGES
  { department: 'ALCOHOLIC BEVERAGES', category: 'Aperitif and Liqueur' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Beer' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Brandy and Cognac' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Gin' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Rum' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Tequila and Mezcal' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Vodka' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Whisk(e)y' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Beverages Promo' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'Modifier Spirit' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'U+Reward Beverages' },
  // NON ALCOHOLIC BEVERAGES
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Additional Bev Non Alcohol' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Coffee' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Mocktails and Smoothies' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Tea' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Mineral Water' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Soft Drink' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Juices' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Mixer' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Beverages Modifier' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'Beverages Promo Non Alcohol' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'U+Reward Beverages Non Alcohol' },
  // COCKTAILS
  { department: 'COCKTAILS', category: 'Cocktails Classic' },
  { department: 'COCKTAILS', category: 'Cocktails Signature' },
  { department: 'COCKTAILS', category: 'Cocktails Event' },
  { department: 'COCKTAILS', category: 'Cocktails Promo' },
  { department: 'COCKTAILS', category: 'Modifier Cocktail' },
  { department: 'COCKTAILS', category: 'U+Reward Cocktails' },
  // WINE
  { department: 'WINE', category: 'Argentina' },
  { department: 'WINE', category: 'Australia' },
  { department: 'WINE', category: 'Austria' },
  { department: 'WINE', category: 'Bordeaux' },
  { department: 'WINE', category: 'Burgundy' },
  { department: 'WINE', category: 'Canada' },
  { department: 'WINE', category: 'Champagne' },
  { department: 'WINE', category: 'Usa' },
  { department: 'WINE', category: 'Chile' },
  { department: 'WINE', category: 'Czech Republic' },
  { department: 'WINE', category: 'France' },
  { department: 'WINE', category: 'Germany' },
  { department: 'WINE', category: 'Portugal' },
  { department: 'WINE', category: 'Italy' },
  { department: 'WINE', category: 'New Zealand' },
  { department: 'WINE', category: 'South Africa' },
  { department: 'WINE', category: 'Spain' },
  { department: 'WINE', category: 'Sparkling Wine' },
  { department: 'WINE', category: 'House Wine' },
  { department: 'WINE', category: 'Wine Event' },
  { department: 'WINE', category: 'Wine Promo' },
  { department: 'WINE', category: 'U+Reward Wine' },
  { department: 'WINE', category: 'Set Menu Wine' },
  // PASTRY
  { department: 'PASTRY', category: 'Pastry Dessert' },
  { department: 'PASTRY', category: 'Pastry Whole' },
  { department: 'PASTRY', category: 'Pastry Slice' },
  { department: 'PASTRY', category: 'Pastry Promo' },
  { department: 'PASTRY', category: 'Pastry Waste' },
  { department: 'PASTRY', category: 'Pastry Modifier' },
  { department: 'PASTRY', category: 'Pastry Refill' },
  { department: 'PASTRY', category: 'Additional Pastry' },
  { department: 'PASTRY', category: 'U+Reward Pastry' },
  // BAKERY
  { department: 'BAKERY', category: 'Bread' },
  { department: 'BAKERY', category: 'Brioche' },
  { department: 'BAKERY', category: 'Croisant' },
  { department: 'BAKERY', category: 'Donut' },
  { department: 'BAKERY', category: 'Bakery Promo' },
  { department: 'BAKERY', category: 'Waste Bakery' },
  { department: 'BAKERY', category: 'Modifier Bakery' },
  // CIGAR-ETTES
  { department: 'CIGAR-ETTES', category: 'Cigar' },
  { department: 'CIGAR-ETTES', category: 'Cigarette' },
  // MISCELLANEOUS
  { department: 'MISCELLANEOUS', category: 'Merchandise' },
  { department: 'MISCELLANEOUS', category: 'Corkage' },
  { department: 'MISCELLANEOUS', category: 'Delivery Fee' },
  { department: 'MISCELLANEOUS', category: 'Add General Supplies' },
  { department: 'MISCELLANEOUS', category: 'Modifier Miscellaneous' },
  { department: 'MISCELLANEOUS', category: 'Retail' },
];

export const MIL_CATEGORIES: CategoryEntry[] = [
  { department: 'FOOD', category: 'MIL Asian' },
  { department: 'FOOD', category: 'MIL Grilled' },
  { department: 'FOOD', category: 'MIL Mains' },
  { department: 'FOOD', category: 'MIL Pasta' },
  { department: 'FOOD', category: 'MIL Sandwich' },
  { department: 'FOOD', category: 'MIL Snack' },
  { department: 'FOOD', category: 'MIL Starter' },
  { department: 'FOOD', category: 'MIL Side Dishes' },
  { department: 'FOOD', category: 'MIL Salad' },
  { department: 'FOOD', category: 'MIL Dessert Food' },
  { department: 'FOOD', category: 'MIL Lunch Specials' },
  { department: 'FOOD', category: 'MIL Special' },
  { department: 'FOOD', category: 'MIL Food Event' },
  { department: 'FOOD', category: 'MIL Food Promo' },
  { department: 'FOOD', category: 'MIL Additional Food' },
  { department: 'FOOD', category: 'MIL Special Feast' },
  { department: 'FOOD', category: 'MIL Breakfast' },
  { department: 'FOOD', category: 'MIL Pizza' },
  { department: 'FOOD', category: 'MIL Modifier Food' },
  { department: 'FOOD', category: 'MIL U+Reward Food' },
  { department: 'FOOD', category: 'MIL Tapas' },
  { department: 'FOOD', category: 'MIL Brunch' },
  { department: 'FOOD', category: 'MIL Complimentary Food' },
  { department: 'FOOD', category: 'MIL Set Menu' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Aperitif and Liqueur' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Beer' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Brandy and Cognac' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Gin' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Rum' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Tequila and Mezcal' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Vodka' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Whisk(e)y' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Beverages Promo' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL Modifier Spirit' },
  { department: 'ALCOHOLIC BEVERAGES', category: 'MIL U+Reward Beverages' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Additional Bev Non Alcohol' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Coffee' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Mocktails and Smoothies' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Tea' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Mineral Water' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Soft Drink' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Juices' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Mixer' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Beverages Modifier' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Beverages Promo Non Alcohol' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL U+Reward Beverages Non Alcohol' },
  { department: 'NON ALCOHOLIC BEVERAGES', category: 'MIL Beverages Event Non Alcohol' },
  { department: 'COCKTAILS', category: 'MIL Cocktails Classic' },
  { department: 'COCKTAILS', category: 'MIL Cocktails Signature' },
  { department: 'COCKTAILS', category: 'MIL Cocktails Event' },
  { department: 'COCKTAILS', category: 'MIL Cocktails Promo' },
  { department: 'COCKTAILS', category: 'MIL Modifier Cocktail' },
  { department: 'COCKTAILS', category: 'MIL U+Reward Cocktails' },
  { department: 'WINE', category: 'MIL Argentina' },
  { department: 'WINE', category: 'MIL Australia' },
  { department: 'WINE', category: 'MIL Austria' },
  { department: 'WINE', category: 'MIL Bordeaux' },
  { department: 'WINE', category: 'MIL Burgundy' },
  { department: 'WINE', category: 'MIL Canada' },
  { department: 'WINE', category: 'MIL Champagne' },
  { department: 'WINE', category: 'MIL Usa' },
  { department: 'WINE', category: 'MIL Chile' },
  { department: 'WINE', category: 'MIL Czech Republic' },
  { department: 'WINE', category: 'MIL France' },
  { department: 'WINE', category: 'MIL Germany' },
  { department: 'WINE', category: 'MIL Portugal' },
  { department: 'WINE', category: 'MIL Italy' },
  { department: 'WINE', category: 'MIL New Zealand' },
  { department: 'WINE', category: 'MIL South Africa' },
  { department: 'WINE', category: 'MIL Spain' },
  { department: 'WINE', category: 'MIL Sparkling Wine' },
  { department: 'WINE', category: 'MIL House Wine' },
  { department: 'WINE', category: 'MIL Wine Event' },
  { department: 'WINE', category: 'MIL Wine Promo' },
  { department: 'WINE', category: 'MIL U+Reward Wine' },
  { department: 'PASTRY', category: 'MIL Pastry Dessert' },
  { department: 'PASTRY', category: 'MIL Pastry Whole' },
  { department: 'PASTRY', category: 'MIL Pastry Slice' },
  { department: 'PASTRY', category: 'MIL Pastry Promo' },
  { department: 'PASTRY', category: 'MIL Pastry Waste' },
  { department: 'PASTRY', category: 'MIL Pastry Modifier' },
  { department: 'PASTRY', category: 'MIL Pastry Refill' },
  { department: 'PASTRY', category: 'MIL Additional Pastry' },
  { department: 'PASTRY', category: 'MIL U+Reward Pastry' },
  { department: 'BAKERY', category: 'MIL Bread' },
  { department: 'BAKERY', category: 'MIL Brioche' },
  { department: 'BAKERY', category: 'MIL Croisant' },
  { department: 'BAKERY', category: 'MIL Donut' },
  { department: 'BAKERY', category: 'MIL Bakery Promo' },
  { department: 'BAKERY', category: 'MIL Waste Bakery' },
  { department: 'BAKERY', category: 'MIL Modifier Bakery' },
  { department: 'CIGAR-ETTES', category: 'MIL Cigar' },
  { department: 'CIGAR-ETTES', category: 'MIL Cigarette' },
  { department: 'MISCELLANEOUS', category: 'MIL Merchandise' },
  { department: 'MISCELLANEOUS', category: 'MIL Corkage' },
  { department: 'MISCELLANEOUS', category: 'MIL Delivery Fee' },
  { department: 'MISCELLANEOUS', category: 'MIL Add General Supplies' },
  { department: 'MISCELLANEOUS', category: 'MIL Modifier Miscellaneous' },
  { department: 'MISCELLANEOUS', category: 'MIL Retail' },
];

const ALL_CATEGORIES = [...STANDARD_CATEGORIES, ...MIL_CATEGORIES];

export function getCategoriesForOutlet(_outlet: string): CategoryEntry[] {
  return ALL_CATEGORIES;
}

export function getDepartmentForCategory(category: string): string {
  return ALL_CATEGORIES.find((c) => c.category === category)?.department ?? '';
}
