import initSqlJs from 'sql.js';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

// ── Types ────────────────────────────────────────────────────────────────────

export interface DbUser {
  id: string;
  email: string;
  password: string;
  name: string;
  role: string;
  outlet: string;
  active: boolean;
  createdAt: string;
}

export interface DbUserPublic {
  id: string;
  email: string;
  name: string;
  role: string;
  outlet: string;
  active: boolean;
  createdAt: string;
}

export interface DbPLURequest {
  id: string;
  requestType: string;
  status: string;
  code: string | null;
  codeIsAutoGenerated: boolean;
  name: string;
  category: string;
  department: string;
  price: number | null;
  folder: string | null;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  printers: string;
  outlets: string;
  salesDef: string;
  barcode: string | null;
  remarks: string | null;
  userId: string;
  outletGroup: string;
  cashierOutlet: string;
  createdAt: string;
  updatedAt: string;
  doneAt: string | null;
  adminNote: string | null;
  exportedAt: string | null;
  exportBatchId: string | null;
}

export interface DbPLURequestWithUser extends DbPLURequest {
  submittedBy: { id: string; name: string; email: string; outlet: string };
}

export interface DbRequestBatchItem {
  id: string;
  batchId: string;
  code: string | null;
  codeIsAutoGenerated: boolean;
  name: string;
  category: string;
  department: string;
  price: number | null;
  folder: string | null;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  printers: string;
  outlets: string;
  salesDef: string;
  barcode: string | null;
  remarks: string | null;
  sortOrder: number;
}

export interface DbRequestBatch {
  id: string;
  title: string;
  requestType: string;
  status: string;
  outletGroup: string;
  cashierOutlet: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  doneAt: string | null;
  adminNote: string | null;
  exportedAt: string | null;
  exportBatchId: string | null;
}

export interface DbRequestBatchWithItems extends DbRequestBatch {
  items: DbRequestBatchItem[];
  submittedBy?: { id: string; name: string; email: string; outlet: string };
}

export interface BatchItemInput {
  code?: string | null;
  codeIsAutoGenerated?: boolean;
  name: string;
  category: string;
  department: string;
  price?: number | null;
  folder?: string | null;
  serviceCharge?: boolean;
  tax1?: boolean;
  tax2?: boolean;
  noDiscount?: boolean;
  hideReceipt?: boolean;
  printers: string;
  outlets: string;
  salesDef?: string;
  barcode?: string | null;
  remarks?: string | null;
}

export interface PLURequestFilters {
  status?: string;
  outletGroup?: string;
  requestType?: string;
  from?: string;
  to?: string;
  userId?: string;
  ids?: string[];
  limit?: number;
  orderAsc?: boolean;
}

export interface RequestBatchFilters {
  status?: string;
  outletGroup?: string;
  requestType?: string;
  from?: string;
  to?: string;
  userId?: string;
  ids?: string[];
  limit?: number;
  orderAsc?: boolean;
}

// ── DB init ──────────────────────────────────────────────────────────────────

function resolveDbPath(): string {
  const url = process.env.DATABASE_URL ?? 'file:./dev.db';
  const filePart = url.replace(/^file:/, '');
  if (path.isAbsolute(filePart)) return filePart;
  return path.resolve(process.cwd(), filePart);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const g = globalThis as unknown as { __sqljsDb?: any; __sqljsSql?: any };

async function getDb() {
  if (!g.__sqljsDb) {
    const dbPath = resolveDbPath();
    if (!fs.existsSync(dbPath)) throw new Error(`DB file not found: ${dbPath}`);
    if (!g.__sqljsSql) {
      g.__sqljsSql = await initSqlJs({
        locateFile: () => path.join(process.cwd(), 'public', 'sql-wasm.wasm'),
      });
    }
    g.__sqljsDb = new g.__sqljsSql.Database(fs.readFileSync(dbPath));
    // Schema migrations — idempotent, silently ignored if column already exists
    try { g.__sqljsDb.run('ALTER TABLE "PLURequest" ADD COLUMN "codeIsAutoGenerated" INTEGER NOT NULL DEFAULT 1'); } catch { /* already exists */ }
    try { g.__sqljsDb.run('ALTER TABLE "RequestBatchItem" ADD COLUMN "codeIsAutoGenerated" INTEGER NOT NULL DEFAULT 1'); } catch { /* already exists */ }
    try { g.__sqljsDb.run('ALTER TABLE "PLURequest" ADD COLUMN "barcode" TEXT'); } catch { /* already exists */ }
    try { g.__sqljsDb.run('ALTER TABLE "RequestBatchItem" ADD COLUMN "barcode" TEXT'); } catch { /* already exists */ }
    try { g.__sqljsDb.run('ALTER TABLE "RequestBatchItem" ADD COLUMN "remarks" TEXT'); } catch { /* already exists */ }
    // KB tables
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "MasterItem" (
      id TEXT PRIMARY KEY, active INTEGER NOT NULL DEFAULT 1, code TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL, category TEXT NOT NULL, department TEXT NOT NULL,
      salesDef TEXT NOT NULL DEFAULT 'SALES', price REAL, plu TEXT, barcode TEXT,
      uom TEXT, folder TEXT, serviceCharge INTEGER NOT NULL DEFAULT 1,
      tax1 INTEGER NOT NULL DEFAULT 1, tax2 INTEGER NOT NULL DEFAULT 1,
      noDiscount INTEGER NOT NULL DEFAULT 1, hideReceipt INTEGER NOT NULL DEFAULT 0,
      printers TEXT, outlets TEXT, outletGroup TEXT,
      importedAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "WikiArticle" (
      id TEXT PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL,
      category TEXT NOT NULL DEFAULT 'General', isPinned INTEGER NOT NULL DEFAULT 0,
      createdBy TEXT NOT NULL, updatedBy TEXT, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "GlossaryEntry" (
      id TEXT PRIMARY KEY, type TEXT NOT NULL, term TEXT NOT NULL,
      definition TEXT NOT NULL, defaultDefinition TEXT, grp TEXT,
      isSeeded INTEGER NOT NULL DEFAULT 0, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "DiscountRequest" (
      id TEXT PRIMARY KEY,
      status TEXT NOT NULL DEFAULT 'PENDING',
      outletGroup TEXT NOT NULL,
      cashierOutlet TEXT NOT NULL,
      userId TEXT NOT NULL,
      buttonName TEXT NOT NULL,
      discountType TEXT NOT NULL,
      discountValue REAL NOT NULL,
      discountValueType TEXT NOT NULL,
      outlets TEXT NOT NULL DEFAULT '',
      applicableTo TEXT NOT NULL,
      conditions TEXT,
      remarks TEXT,
      adminNote TEXT,
      createdAt TEXT NOT NULL,
      updatedAt TEXT NOT NULL,
      doneAt TEXT
    )`);
    // Add outlets column to existing DiscountRequest tables that were created before this column was added
    const drCols = execAll(g.__sqljsDb, `PRAGMA table_info("DiscountRequest")`, []);
    if (!drCols.some((c) => c.name === 'outlets')) {
      g.__sqljsDb.run(`ALTER TABLE "DiscountRequest" ADD COLUMN outlets TEXT NOT NULL DEFAULT ''`);
    }
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "OutletConfig" (
      id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, "group" TEXT NOT NULL,
      isActive INTEGER NOT NULL DEFAULT 1, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "PrinterConfig" (
      id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, "group" TEXT NOT NULL,
      isActive INTEGER NOT NULL DEFAULT 1, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    g.__sqljsDb.run(`CREATE TABLE IF NOT EXISTS "CategoryConfig" (
      id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, department TEXT NOT NULL,
      departmentCode INTEGER NOT NULL, categoryCode INTEGER NOT NULL,
      isActive INTEGER NOT NULL DEFAULT 1, createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL
    )`);
    fs.writeFileSync(dbPath, Buffer.from(g.__sqljsDb.export()));
  }
  return g.__sqljsDb;
}


// Write lock — chains writes sequentially so concurrent requests don't race.
let writeQueue: Promise<unknown> = Promise.resolve();

async function withWriteLock<T>(fn: (db: ReturnType<typeof getDb> extends Promise<infer U> ? U : never) => T | Promise<T>): Promise<T> {
  const task = writeQueue.then(async () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const db: any = await getDb();
    const result = await fn(db);
    fs.writeFileSync(resolveDbPath(), Buffer.from(db.export()));
    return result;
  });
  writeQueue = task.catch(() => {});
  return task as Promise<T>;
}

// ── Row utilities ────────────────────────────────────────────────────────────

function rowToObj(columns: string[], values: unknown[]): Record<string, unknown> {
  const obj: Record<string, unknown> = {};
  columns.forEach((col, i) => { obj[col] = values[i]; });
  return obj;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function execFirst(db: any, sql: string, params: unknown[] = []): Record<string, unknown> | null {
  const results = db.exec(sql, params);
  if (!results.length || !results[0].values.length) return null;
  return rowToObj(results[0].columns, results[0].values[0]);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function execAll(db: any, sql: string, params: unknown[] = []): Record<string, unknown>[] {
  const results = db.exec(sql, params);
  if (!results.length) return [];
  const { columns, values } = results[0];
  return (values as unknown[][]).map((row) => rowToObj(columns, row));
}

function normBool(v: unknown): boolean { return v === 1 || v === true; }
function normStr(v: unknown): string | null { return v == null ? null : String(v); }
function newId(): string { return crypto.randomUUID(); }
function nowIso(): string { return new Date().toISOString(); }

// ── User row mappers ─────────────────────────────────────────────────────────

function rowToDbUser(row: Record<string, unknown>): DbUser {
  return {
    id: String(row.id),
    email: String(row.email),
    password: String(row.password),
    name: String(row.name),
    role: String(row.role),
    outlet: String(row.outlet),
    active: normBool(row.active),
    createdAt: String(row.createdAt),
  };
}

function rowToDbUserPublic(row: Record<string, unknown>): DbUserPublic {
  return {
    id: String(row.id),
    email: String(row.email),
    name: String(row.name),
    role: String(row.role),
    outlet: String(row.outlet),
    active: normBool(row.active),
    createdAt: String(row.createdAt),
  };
}

// ── User helpers ─────────────────────────────────────────────────────────────

export async function getUserByEmail(email: string): Promise<DbUser | null> {
  try {
    const db = await getDb();
    const row = execFirst(db,
      'SELECT id, email, password, name, role, outlet, active, createdAt FROM "User" WHERE email = ? LIMIT 1',
      [email]);
    return row ? rowToDbUser(row) : null;
  } catch (err) {
    console.error('[db] getUserByEmail failed:', err);
    return null;
  }
}

export async function getUserById(id: string): Promise<DbUserPublic | null> {
  try {
    const db = await getDb();
    const row = execFirst(db,
      'SELECT id, email, name, role, outlet, active, createdAt FROM "User" WHERE id = ? LIMIT 1',
      [id]);
    return row ? rowToDbUserPublic(row) : null;
  } catch (err) {
    console.error('[db] getUserById failed:', err);
    return null;
  }
}

export async function getAllUsers(): Promise<DbUserPublic[]> {
  try {
    const db = await getDb();
    const rows = execAll(db,
      'SELECT id, email, name, role, outlet, active, createdAt FROM "User" ORDER BY createdAt DESC');
    return rows.map(rowToDbUserPublic);
  } catch (err) {
    console.error('[db] getAllUsers failed:', err);
    return [];
  }
}

export async function findUserByEmailExcluding(email: string, excludeId: string): Promise<DbUserPublic | null> {
  try {
    const db = await getDb();
    const row = execFirst(db,
      'SELECT id, email, name, role, outlet, active, createdAt FROM "User" WHERE email = ? AND id != ? LIMIT 1',
      [email, excludeId]);
    return row ? rowToDbUserPublic(row) : null;
  } catch (err) {
    console.error('[db] findUserByEmailExcluding failed:', err);
    return null;
  }
}

export async function createUser(data: {
  email: string; password: string; name: string; role: string; outlet: string;
}): Promise<DbUserPublic> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    db.run(
      'INSERT INTO "User" (id, email, password, name, role, outlet, active, createdAt) VALUES (?,?,?,?,?,?,1,?)',
      [id, data.email, data.password, data.name, data.role, data.outlet, now]);
    const row = execFirst(db, 'SELECT id, email, name, role, outlet, active, createdAt FROM "User" WHERE id = ?', [id]);
    if (!row) throw new Error('User creation failed');
    return rowToDbUserPublic(row);
  });
}

export async function updateUser(id: string, data: Partial<{
  email: string; password: string; name: string; role: string; outlet: string; active: boolean;
}>): Promise<DbUserPublic | null> {
  return withWriteLock((db) => {
    const sets: string[] = [];
    const vals: unknown[] = [];
    if (data.email !== undefined)    { sets.push('email = ?');    vals.push(data.email); }
    if (data.password !== undefined) { sets.push('password = ?'); vals.push(data.password); }
    if (data.name !== undefined)     { sets.push('name = ?');     vals.push(data.name); }
    if (data.role !== undefined)     { sets.push('role = ?');     vals.push(data.role); }
    if (data.outlet !== undefined)   { sets.push('outlet = ?');   vals.push(data.outlet); }
    if (data.active !== undefined)   { sets.push('active = ?');   vals.push(data.active ? 1 : 0); }
    if (sets.length > 0) {
      vals.push(id);
      db.run(`UPDATE "User" SET ${sets.join(', ')} WHERE id = ?`, vals);
    }
    const row = execFirst(db, 'SELECT id, email, name, role, outlet, active, createdAt FROM "User" WHERE id = ?', [id]);
    return row ? rowToDbUserPublic(row) : null;
  });
}

export async function deleteUser(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "User" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "User" WHERE id = ?', [id]);
    return true;
  });
}

// ── PLURequest row mapper ────────────────────────────────────────────────────

function rowToPLURequest(row: Record<string, unknown>): DbPLURequest {
  return {
    id: String(row.id),
    requestType: String(row.requestType),
    status: String(row.status),
    code: normStr(row.code),
    codeIsAutoGenerated: normBool(row.codeIsAutoGenerated ?? 1),
    name: String(row.name),
    category: String(row.category),
    department: String(row.department),
    price: row.price != null ? Number(row.price) : null,
    folder: normStr(row.folder),
    serviceCharge: normBool(row.serviceCharge),
    tax1: normBool(row.tax1),
    tax2: normBool(row.tax2),
    noDiscount: normBool(row.noDiscount),
    hideReceipt: normBool(row.hideReceipt),
    printers: String(row.printers ?? ''),
    outlets: String(row.outlets ?? ''),
    salesDef: String(row.salesDef ?? 'SALES'),
    barcode: normStr(row.barcode),
    remarks: normStr(row.remarks),
    userId: String(row.userId),
    outletGroup: String(row.outletGroup),
    cashierOutlet: String(row.cashierOutlet),
    createdAt: String(row.createdAt),
    updatedAt: String(row.updatedAt),
    doneAt: normStr(row.doneAt),
    adminNote: normStr(row.adminNote),
    exportedAt: normStr(row.exportedAt),
    exportBatchId: normStr(row.exportBatchId),
  };
}

function rowToPLURequestWithUser(row: Record<string, unknown>): DbPLURequestWithUser {
  return {
    ...rowToPLURequest(row),
    submittedBy: {
      id: String(row.u_id ?? row.userId),
      name: String(row.u_name ?? ''),
      email: String(row.u_email ?? ''),
      outlet: String(row.u_outlet ?? ''),
    },
  };
}

// ── PLURequest filter builder ────────────────────────────────────────────────

function buildPLUConditions(filters: PLURequestFilters, alias: string): { conditions: string[]; params: unknown[] } {
  const conditions: string[] = [];
  const params: unknown[] = [];
  if (filters.status && filters.status !== 'ALL')           { conditions.push(`${alias}.status = ?`);       params.push(filters.status); }
  if (filters.outletGroup && filters.outletGroup !== 'ALL') { conditions.push(`${alias}.outletGroup = ?`);  params.push(filters.outletGroup); }
  if (filters.requestType && filters.requestType !== 'ALL') { conditions.push(`${alias}.requestType = ?`);  params.push(filters.requestType); }
  if (filters.userId)                                        { conditions.push(`${alias}.userId = ?`);      params.push(filters.userId); }
  if (filters.from) {
    conditions.push(`${alias}.createdAt >= ?`);
    params.push(filters.from);
  }
  if (filters.to) {
    const d = new Date(filters.to); d.setHours(23, 59, 59, 999);
    conditions.push(`${alias}.createdAt <= ?`);
    params.push(d.toISOString());
  }
  if (filters.ids && filters.ids.length > 0) {
    conditions.push(`${alias}.id IN (${filters.ids.map(() => '?').join(',')})`);
    params.push(...filters.ids);
  }
  return { conditions, params };
}

// ── PLURequest helpers ───────────────────────────────────────────────────────

export async function getPLURequests(filters: PLURequestFilters = {}): Promise<DbPLURequestWithUser[]> {
  try {
    const db = await getDb();
    const { conditions, params } = buildPLUConditions(filters, 'pr');
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const limit = Math.min(filters.limit ?? 500, 2000);
    const order = filters.orderAsc ? 'ASC' : 'DESC';
    const rows = execAll(db, `
      SELECT pr.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "PLURequest" pr LEFT JOIN "User" u ON pr.userId = u.id
      ${where} ORDER BY pr.createdAt ${order} LIMIT ?
    `, [...params, limit]);
    return rows.map(rowToPLURequestWithUser);
  } catch (err) {
    console.error('[db] getPLURequests failed:', err);
    return [];
  }
}

export async function getPLURequestsRaw(filters: PLURequestFilters = {}): Promise<DbPLURequest[]> {
  try {
    const db = await getDb();
    const { conditions, params } = buildPLUConditions(filters, 'pr');
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const limit = Math.min(filters.limit ?? 500, 2000);
    const order = filters.orderAsc ? 'ASC' : 'DESC';
    const rows = execAll(db, `
      SELECT pr.* FROM "PLURequest" pr
      ${where} ORDER BY pr.createdAt ${order} LIMIT ?
    `, [...params, limit]);
    return rows.map(rowToPLURequest);
  } catch (err) {
    console.error('[db] getPLURequestsRaw failed:', err);
    return [];
  }
}

export async function countPLURequests(filters: PLURequestFilters = {}): Promise<number> {
  try {
    const db = await getDb();
    const { conditions, params } = buildPLUConditions(filters, 'pr');
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const row = execFirst(db,
      `SELECT COUNT(*) as cnt FROM "PLURequest" pr ${where}`, params);
    return row ? Number(row.cnt) : 0;
  } catch (err) {
    console.error('[db] countPLURequests failed:', err);
    return 0;
  }
}

export async function getPLURequestById(id: string): Promise<DbPLURequestWithUser | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, `
      SELECT pr.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "PLURequest" pr LEFT JOIN "User" u ON pr.userId = u.id
      WHERE pr.id = ? LIMIT 1
    `, [id]);
    return row ? rowToPLURequestWithUser(row) : null;
  } catch (err) {
    console.error('[db] getPLURequestById failed:', err);
    return null;
  }
}

export async function getPLURequestByIdSimple(id: string): Promise<DbPLURequest | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT * FROM "PLURequest" WHERE id = ? LIMIT 1', [id]);
    return row ? rowToPLURequest(row) : null;
  } catch (err) {
    console.error('[db] getPLURequestByIdSimple failed:', err);
    return null;
  }
}

export async function createPLURequest(data: {
  requestType: string; code?: string | null; codeIsAutoGenerated?: boolean; name: string; category: string;
  department: string; price?: number | null; folder?: string | null;
  serviceCharge: boolean; tax1: boolean; tax2: boolean; noDiscount: boolean;
  hideReceipt: boolean; printers: string; outlets: string;
  barcode?: string | null;
  remarks?: string | null; userId: string; outletGroup: string; cashierOutlet: string;
  salesDef?: string;
}): Promise<DbPLURequest> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    const codeIsAuto = (data.codeIsAutoGenerated ?? true) ? 1 : 0;
    db.run(`
      INSERT INTO "PLURequest" (
        id, requestType, status, code, codeIsAutoGenerated, name, category, department, price, folder,
        serviceCharge, tax1, tax2, noDiscount, hideReceipt, printers, outlets,
        salesDef, barcode, remarks, userId, outletGroup, cashierOutlet,
        createdAt, updatedAt, doneAt, adminNote, exportedAt, exportBatchId
      ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,null,null,null,null)
    `, [
      id, data.requestType, 'PENDING', data.code ?? null, codeIsAuto, data.name, data.category,
      data.department, data.price ?? null, data.folder ?? null,
      data.serviceCharge ? 1 : 0, data.tax1 ? 1 : 0, data.tax2 ? 1 : 0,
      data.noDiscount ? 1 : 0, data.hideReceipt ? 1 : 0,
      data.printers, data.outlets, data.salesDef ?? 'SALES', data.barcode ?? null, data.remarks ?? null,
      data.userId, data.outletGroup, data.cashierOutlet, now, now,
    ]);
    const row = execFirst(db, 'SELECT * FROM "PLURequest" WHERE id = ?', [id]);
    if (!row) throw new Error('PLURequest creation failed');
    return rowToPLURequest(row);
  });
}

export async function updatePLURequest(id: string, data: Partial<{
  code: string | null; name: string; category: string; department: string;
  price: number | null; folder: string | null;
  serviceCharge: boolean; tax1: boolean; tax2: boolean; noDiscount: boolean;
  hideReceipt: boolean; printers: string; outlets: string;
  barcode: string | null;
  remarks: string | null; adminNote: string | null; status: string;
  doneAt: string | null; exportedAt: string | null; exportBatchId: string | null;
}>): Promise<DbPLURequest | null> {
  return withWriteLock((db) => {
    const sets: string[] = ['updatedAt = ?'];
    const vals: unknown[] = [nowIso()];

    const boolFields = ['serviceCharge', 'tax1', 'tax2', 'noDiscount', 'hideReceipt'] as const;
    const strFields = [
      'code', 'name', 'category', 'department', 'folder', 'printers', 'outlets',
      'barcode', 'remarks', 'adminNote', 'status', 'doneAt', 'exportedAt', 'exportBatchId',
    ] as const;

    for (const f of boolFields) {
      if (f in data && data[f] !== undefined) { sets.push(`${f} = ?`); vals.push(data[f] ? 1 : 0); }
    }
    for (const f of strFields) {
      if (f in data) { sets.push(`${f} = ?`); vals.push(data[f] ?? null); }
    }
    if ('price' in data) { sets.push('price = ?'); vals.push(data.price ?? null); }

    vals.push(id);
    db.run(`UPDATE "PLURequest" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "PLURequest" WHERE id = ?', [id]);
    return row ? rowToPLURequest(row) : null;
  });
}

export async function deletePLURequest(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "PLURequest" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "PLURequest" WHERE id = ?', [id]);
    return true;
  });
}

export async function bulkMarkPLURequestsDone(ids: string[]): Promise<number> {
  if (ids.length === 0) return 0;
  return withWriteLock((db) => {
    const now = nowIso();
    const ph = ids.map(() => '?').join(',');
    db.run(
      `UPDATE "PLURequest" SET status = 'DONE', doneAt = ?, updatedAt = ? WHERE id IN (${ph}) AND status = 'PENDING'`,
      [now, now, ...ids]);
    return db.getRowsModified() as number;
  });
}

export async function markPLURequestsExported(ids: string[], exportedAt: string, exportBatchId: string): Promise<void> {
  if (ids.length === 0) return;
  await withWriteLock((db) => {
    const now = nowIso();
    const ph = ids.map(() => '?').join(',');
    db.run(
      `UPDATE "PLURequest" SET exportedAt = ?, exportBatchId = ?, updatedAt = ? WHERE id IN (${ph})`,
      [exportedAt, exportBatchId, now, ...ids]);
  });
}

// ── Metrics ──────────────────────────────────────────────────────────────────

export async function getPLUMetrics(filters: { outletGroup?: string; from?: string; to?: string } = {}): Promise<{
  newItems: number; updatePrice: number; updateName: number; updatePrinter: number; totalDone: number;
}> {
  const zero = { newItems: 0, updatePrice: 0, updateName: 0, updatePrinter: 0, totalDone: 0 };
  try {
    const db = await getDb();
    const conditions: string[] = [];
    const params: unknown[] = [];
    if (filters.outletGroup && filters.outletGroup !== 'ALL') { conditions.push('outletGroup = ?'); params.push(filters.outletGroup); }
    if (filters.from) { conditions.push('createdAt >= ?'); params.push(filters.from); }
    if (filters.to) {
      const d = new Date(filters.to); d.setHours(23, 59, 59, 999);
      conditions.push('createdAt <= ?'); params.push(d.toISOString());
    }
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const row = execFirst(db, `
      SELECT
        COUNT(CASE WHEN requestType = 'NEW_ITEM' THEN 1 END) as newItems,
        COUNT(CASE WHEN requestType = 'UPDATE_PRICE' THEN 1 END) as updatePrice,
        COUNT(CASE WHEN requestType = 'UPDATE_NAME' THEN 1 END) as updateName,
        COUNT(CASE WHEN requestType = 'UPDATE_PRINTER' THEN 1 END) as updatePrinter,
        COUNT(CASE WHEN status = 'DONE' THEN 1 END) as totalDone
      FROM "PLURequest" ${where}
    `, params);
    if (!row) return zero;
    return {
      newItems: Number(row.newItems),
      updatePrice: Number(row.updatePrice),
      updateName: Number(row.updateName),
      updatePrinter: Number(row.updatePrinter),
      totalDone: Number(row.totalDone),
    };
  } catch (err) {
    console.error('[db] getPLUMetrics failed:', err);
    return zero;
  }
}

// ── RequestBatchItem row mapper ───────────────────────────────────────────────

function rowToRequestBatchItem(row: Record<string, unknown>): DbRequestBatchItem {
  return {
    id: String(row.id),
    batchId: String(row.batchId),
    code: normStr(row.code),
    codeIsAutoGenerated: normBool(row.codeIsAutoGenerated ?? 1),
    name: String(row.name),
    category: String(row.category),
    department: String(row.department),
    price: row.price != null ? Number(row.price) : null,
    folder: normStr(row.folder),
    serviceCharge: normBool(row.serviceCharge),
    tax1: normBool(row.tax1),
    tax2: normBool(row.tax2),
    noDiscount: normBool(row.noDiscount),
    hideReceipt: normBool(row.hideReceipt),
    printers: String(row.printers ?? ''),
    outlets: String(row.outlets ?? ''),
    salesDef: String(row.salesDef ?? 'SALES'),
    barcode: normStr(row.barcode),
    remarks: normStr(row.remarks),
    sortOrder: Number(row.sortOrder ?? 0),
  };
}

function rowToRequestBatch(row: Record<string, unknown>): DbRequestBatch {
  return {
    id: String(row.id),
    title: String(row.title),
    requestType: String(row.requestType),
    status: String(row.status),
    outletGroup: String(row.outletGroup),
    cashierOutlet: String(row.cashierOutlet),
    userId: String(row.userId),
    createdAt: String(row.createdAt),
    updatedAt: String(row.updatedAt),
    doneAt: normStr(row.doneAt),
    adminNote: normStr(row.adminNote),
    exportedAt: normStr(row.exportedAt),
    exportBatchId: normStr(row.exportBatchId),
  };
}

// ── RequestBatch filter builder ───────────────────────────────────────────────

function buildBatchConditions(filters: RequestBatchFilters, alias: string): { conditions: string[]; params: unknown[] } {
  const conditions: string[] = [];
  const params: unknown[] = [];
  if (filters.status && filters.status !== 'ALL')           { conditions.push(`${alias}.status = ?`);      params.push(filters.status); }
  if (filters.outletGroup && filters.outletGroup !== 'ALL') { conditions.push(`${alias}.outletGroup = ?`); params.push(filters.outletGroup); }
  if (filters.requestType && filters.requestType !== 'ALL') { conditions.push(`${alias}.requestType = ?`); params.push(filters.requestType); }
  if (filters.userId)                                        { conditions.push(`${alias}.userId = ?`);     params.push(filters.userId); }
  if (filters.from) {
    conditions.push(`${alias}.createdAt >= ?`);
    params.push(filters.from);
  }
  if (filters.to) {
    const d = new Date(filters.to); d.setHours(23, 59, 59, 999);
    conditions.push(`${alias}.createdAt <= ?`);
    params.push(d.toISOString());
  }
  if (filters.ids && filters.ids.length > 0) {
    conditions.push(`${alias}.id IN (${filters.ids.map(() => '?').join(',')})`);
    params.push(...filters.ids);
  }
  return { conditions, params };
}

// ── RequestBatch helpers ──────────────────────────────────────────────────────

export async function getRequestBatches(filters: RequestBatchFilters = {}): Promise<DbRequestBatchWithItems[]> {
  try {
    const db = await getDb();
    const { conditions, params } = buildBatchConditions(filters, 'rb');
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const limit = Math.min(filters.limit ?? 500, 2000);
    const order = filters.orderAsc ? 'ASC' : 'DESC';

    const batchRows = execAll(db, `
      SELECT rb.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "RequestBatch" rb LEFT JOIN "User" u ON rb.userId = u.id
      ${where} ORDER BY rb.createdAt ${order} LIMIT ?
    `, [...params, limit]);

    if (batchRows.length === 0) return [];

    const batchIds = batchRows.map((r) => String(r.id));
    const itemRows = execAll(db,
      `SELECT * FROM "RequestBatchItem" WHERE batchId IN (${batchIds.map(() => '?').join(',')}) ORDER BY sortOrder ASC`,
      batchIds);

    const itemsByBatch: Record<string, DbRequestBatchItem[]> = {};
    for (const item of itemRows) {
      const bid = String(item.batchId);
      if (!itemsByBatch[bid]) itemsByBatch[bid] = [];
      itemsByBatch[bid].push(rowToRequestBatchItem(item));
    }

    return batchRows.map((row) => ({
      ...rowToRequestBatch(row),
      items: itemsByBatch[String(row.id)] ?? [],
      submittedBy: {
        id: String(row.u_id ?? row.userId),
        name: String(row.u_name ?? ''),
        email: String(row.u_email ?? ''),
        outlet: String(row.u_outlet ?? ''),
      },
    }));
  } catch (err) {
    console.error('[db] getRequestBatches failed:', err);
    return [];
  }
}

export async function getRequestBatchById(id: string): Promise<DbRequestBatchWithItems | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, `
      SELECT rb.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "RequestBatch" rb LEFT JOIN "User" u ON rb.userId = u.id
      WHERE rb.id = ? LIMIT 1
    `, [id]);
    if (!row) return null;
    const itemRows = execAll(db,
      'SELECT * FROM "RequestBatchItem" WHERE batchId = ? ORDER BY sortOrder ASC', [id]);
    return {
      ...rowToRequestBatch(row),
      items: itemRows.map(rowToRequestBatchItem),
      submittedBy: {
        id: String(row.u_id ?? row.userId),
        name: String(row.u_name ?? ''),
        email: String(row.u_email ?? ''),
        outlet: String(row.u_outlet ?? ''),
      },
    };
  } catch (err) {
    console.error('[db] getRequestBatchById failed:', err);
    return null;
  }
}

function insertBatchItems(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  db: any, batchId: string, items: BatchItemInput[]
): DbRequestBatchItem[] {
  const created: DbRequestBatchItem[] = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const itemId = newId();
    const sc = item.serviceCharge ?? true;
    const t1 = item.tax1 ?? true;
    const t2 = item.tax2 ?? true;
    const nd = item.noDiscount ?? true;
    const hr = item.hideReceipt ?? false;
    const codeIsAuto = (item.codeIsAutoGenerated ?? true) ? 1 : 0;
    db.run(`
      INSERT INTO "RequestBatchItem"
        (id, batchId, code, codeIsAutoGenerated, name, category, department, price, folder,
         serviceCharge, tax1, tax2, noDiscount, hideReceipt, printers, outlets, salesDef, barcode, remarks, sortOrder)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    `, [
      itemId, batchId, item.code ?? null, codeIsAuto, item.name, item.category, item.department,
      item.price ?? null, item.folder ?? null,
      sc ? 1 : 0, t1 ? 1 : 0, t2 ? 1 : 0, nd ? 1 : 0, hr ? 1 : 0,
      item.printers, item.outlets, item.salesDef ?? 'SALES', item.barcode ?? null, item.remarks ?? null, i,
    ]);
    created.push({
      id: itemId, batchId,
      code: item.code ?? null, codeIsAutoGenerated: item.codeIsAutoGenerated ?? true,
      name: item.name, category: item.category,
      department: item.department, price: item.price ?? null, folder: item.folder ?? null,
      serviceCharge: sc, tax1: t1, tax2: t2, noDiscount: nd, hideReceipt: hr,
      printers: item.printers, outlets: item.outlets,
      salesDef: item.salesDef ?? 'SALES', barcode: item.barcode ?? null, remarks: item.remarks ?? null, sortOrder: i,
    });
  }
  return created;
}

export async function createRequestBatch(
  data: { title: string; requestType: string; outletGroup: string; cashierOutlet: string; userId: string },
  items: BatchItemInput[]
): Promise<DbRequestBatchWithItems> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    db.run(`
      INSERT INTO "RequestBatch"
        (id, title, requestType, status, outletGroup, cashierOutlet, userId,
         createdAt, updatedAt, doneAt, adminNote, exportedAt, exportBatchId)
      VALUES (?,?,?,'PENDING',?,?,?,?,?,null,null,null,null)
    `, [id, data.title, data.requestType, data.outletGroup, data.cashierOutlet, data.userId, now, now]);

    const createdItems = insertBatchItems(db, id, items);
    const row = execFirst(db, 'SELECT * FROM "RequestBatch" WHERE id = ?', [id]);
    if (!row) throw new Error('Batch creation failed');
    return { ...rowToRequestBatch(row), items: createdItems };
  });
}

export async function updateRequestBatch(
  id: string,
  data: { title?: string; requestType?: string },
  items: BatchItemInput[]
): Promise<DbRequestBatchWithItems | null> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT * FROM "RequestBatch" WHERE id = ?', [id]);
    if (!existing) return null;

    const now = nowIso();
    db.run('UPDATE "RequestBatch" SET title = ?, requestType = ?, updatedAt = ? WHERE id = ?', [
      data.title ?? String(existing.title),
      data.requestType ?? String(existing.requestType),
      now, id,
    ]);
    db.run('DELETE FROM "RequestBatchItem" WHERE batchId = ?', [id]);
    const createdItems = insertBatchItems(db, id, items);
    const row = execFirst(db, 'SELECT * FROM "RequestBatch" WHERE id = ?', [id]);
    if (!row) return null;
    return { ...rowToRequestBatch(row), items: createdItems };
  });
}

export async function getNextPLUSequence(prefix: string, deptCode: string, catCode: string): Promise<number> {
  try {
    const db = await getDb();
    // LIKE pattern: prefix(3) + deptCode(2) + catCode(3) + 8 single-char wildcards = 16 chars
    const likePattern = `${prefix}${deptCode}${catCode}________`;
    const row = execFirst(db, `
      SELECT MAX(CAST(SUBSTR(code, 9, 8) AS INTEGER)) as maxSeq
      FROM (
        SELECT code FROM "PLURequest"
          WHERE code LIKE ? AND LENGTH(code) = 16
        UNION ALL
        SELECT code FROM "RequestBatchItem"
          WHERE code LIKE ? AND LENGTH(code) = 16
      )
    `, [likePattern, likePattern]);
    const maxSeq = row?.maxSeq != null ? Number(row.maxSeq) : null;
    return maxSeq != null && maxSeq >= 4000 ? maxSeq + 1 : 4000;
  } catch (err) {
    console.error('[db] getNextPLUSequence failed:', err);
    return 4000;
  }
}

export async function deleteRequestBatch(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "RequestBatch" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "RequestBatchItem" WHERE batchId = ?', [id]);
    db.run('DELETE FROM "RequestBatch" WHERE id = ?', [id]);
    return true;
  });
}

export async function markRequestBatchDone(id: string): Promise<{ batch: DbRequestBatch; itemCount: number } | null> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id, status FROM "RequestBatch" WHERE id = ?', [id]);
    if (!existing) return null;
    const now = nowIso();
    db.run('UPDATE "RequestBatch" SET status = ?, doneAt = ?, updatedAt = ? WHERE id = ?',
      ['DONE', now, now, id]);
    const itemCountRow = execFirst(db,
      'SELECT COUNT(*) as cnt FROM "RequestBatchItem" WHERE batchId = ?', [id]);
    const itemCount = itemCountRow ? Number(itemCountRow.cnt) : 0;
    const updated = execFirst(db, 'SELECT * FROM "RequestBatch" WHERE id = ?', [id]);
    if (!updated) return null;
    return { batch: rowToRequestBatch(updated), itemCount };
  });
}

// ── MasterItem ────────────────────────────────────────────────────────────────

export interface DbMasterItem {
  id: string; active: boolean; code: string; name: string;
  category: string; department: string; salesDef: string;
  price: number | null; plu: string | null; barcode: string | null;
  uom: string | null; folder: string | null;
  serviceCharge: boolean; tax1: boolean; tax2: boolean; noDiscount: boolean; hideReceipt: boolean;
  printers: string | null; outlets: string | null; outletGroup: string | null;
  importedAt: string; updatedAt: string;
}

export interface MasterItemFilters {
  search?: string; outletGroup?: string; department?: string; category?: string; outlet?: string; active?: boolean | null;
  limit?: number; offset?: number;
}

function rowToMasterItem(row: Record<string, unknown>): DbMasterItem {
  return {
    id: String(row.id), active: normBool(row.active), code: String(row.code),
    name: String(row.name), category: String(row.category), department: String(row.department),
    salesDef: String(row.salesDef ?? 'SALES'), price: row.price != null ? Number(row.price) : null,
    plu: normStr(row.plu), barcode: normStr(row.barcode), uom: normStr(row.uom),
    folder: normStr(row.folder), serviceCharge: normBool(row.serviceCharge),
    tax1: normBool(row.tax1), tax2: normBool(row.tax2), noDiscount: normBool(row.noDiscount),
    hideReceipt: normBool(row.hideReceipt), printers: normStr(row.printers),
    outlets: normStr(row.outlets), outletGroup: normStr(row.outletGroup),
    importedAt: String(row.importedAt), updatedAt: String(row.updatedAt),
  };
}

function buildMasterItemConditions(f: MasterItemFilters): { conditions: string[]; params: unknown[] } {
  const conditions: string[] = [];
  const params: unknown[] = [];
  if (f.search) {
    const q = `%${f.search}%`;
    conditions.push('(code LIKE ? OR name LIKE ? OR category LIKE ? OR plu LIKE ? OR barcode LIKE ?)');
    params.push(q, q, q, q, q);
  }
  if (f.outletGroup && f.outletGroup !== 'ALL') { conditions.push('outletGroup = ?'); params.push(f.outletGroup); }
  if (f.department && f.department !== 'ALL') { conditions.push('department = ?'); params.push(f.department); }
  if (f.category && f.category !== 'ALL') { conditions.push('category = ?'); params.push(f.category); }
  if (f.outlet && f.outlet !== 'ALL') {
    const code = f.outlet;
    conditions.push('(outlets = ? OR outlets LIKE ? OR outlets LIKE ? OR outlets LIKE ?)');
    params.push(code, `${code};%`, `%;${code};%`, `%;${code}`);
  }
  if (f.active !== undefined && f.active !== null) { conditions.push('active = ?'); params.push(f.active ? 1 : 0); }
  return { conditions, params };
}

export async function getMasterItems(filters: MasterItemFilters = {}): Promise<DbMasterItem[]> {
  try {
    const db = await getDb();
    const { conditions, params } = buildMasterItemConditions(filters);
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const limit = filters.limit ?? 50;
    const offset = filters.offset ?? 0;
    const rows = execAll(db, `SELECT * FROM "MasterItem" ${where} ORDER BY name ASC LIMIT ? OFFSET ?`, [...params, limit, offset]);
    return rows.map(rowToMasterItem);
  } catch (err) {
    console.error('[db] getMasterItems failed:', err);
    return [];
  }
}

export async function countMasterItems(filters: MasterItemFilters = {}): Promise<number> {
  try {
    const db = await getDb();
    const { conditions, params } = buildMasterItemConditions(filters);
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const row = execFirst(db, `SELECT COUNT(*) as cnt FROM "MasterItem" ${where}`, params);
    return row ? Number(row.cnt) : 0;
  } catch (err) {
    console.error('[db] countMasterItems failed:', err);
    return 0;
  }
}

export async function getMasterItemByCode(code: string): Promise<DbMasterItem | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT * FROM "MasterItem" WHERE code = ? LIMIT 1', [code]);
    return row ? rowToMasterItem(row) : null;
  } catch (err) {
    console.error('[db] getMasterItemByCode failed:', err);
    return null;
  }
}

export async function getMasterItemsByCodes(codes: string[]): Promise<DbMasterItem[]> {
  try {
    const unique = Array.from(new Set(codes.filter((c) => typeof c === 'string' && c.trim()).map((c) => c.trim())));
    if (unique.length === 0) return [];
    const db = await getDb();
    const out: DbMasterItem[] = [];
    // Chunk to stay well under SQLite's bound-variable limit for very large batches (100+ codes)
    const CHUNK = 400;
    for (let i = 0; i < unique.length; i += CHUNK) {
      const slice = unique.slice(i, i + CHUNK);
      const placeholders = slice.map(() => '?').join(',');
      const rows = execAll(db, `SELECT * FROM "MasterItem" WHERE code IN (${placeholders})`, slice);
      for (const row of rows) out.push(rowToMasterItem(row));
    }
    return out;
  } catch (err) {
    console.error('[db] getMasterItemsByCodes failed:', err);
    return [];
  }
}

/**
 * Build a code -> MasterItem map for the given (possibly null/duplicate) codes.
 * Used to enrich UPDATE_PRICE / UPDATE_NAME requests with the registry name & category,
 * since those request rows do not store the existing item's name/category themselves.
 */
export async function getMasterMapByCodes(
  codes: (string | null | undefined)[],
): Promise<Map<string, DbMasterItem>> {
  const valid = codes.filter((c): c is string => typeof c === 'string' && c.trim() !== '');
  if (valid.length === 0) return new Map();
  const items = await getMasterItemsByCodes(valid);
  return new Map(items.map((m) => [m.code, m]));
}

export async function searchMasterItems(q: string, limit = 10): Promise<DbMasterItem[]> {
  try {
    const db = await getDb();
    const like = `%${q}%`;
    const rows = execAll(db,
      'SELECT * FROM "MasterItem" WHERE code LIKE ? OR name LIKE ? OR plu LIKE ? OR barcode LIKE ? ORDER BY name ASC LIMIT ?',
      [like, like, like, like, limit]);
    return rows.map(rowToMasterItem);
  } catch (err) {
    console.error('[db] searchMasterItems failed:', err);
    return [];
  }
}

export async function getMasterItemsLastImported(): Promise<string | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT MAX(importedAt) as last FROM "MasterItem"');
    return row?.last ? String(row.last) : null;
  } catch { return null; }
}

export async function getMasterItemDepartments(): Promise<string[]> {
  try {
    const db = await getDb();
    const rows = execAll(db, 'SELECT DISTINCT department FROM "MasterItem" ORDER BY department ASC');
    return rows.map((r) => String(r.department));
  } catch { return []; }
}

export interface MasterItemUpsertInput {
  active: boolean; code: string; name: string; category: string; department: string;
  salesDef?: string; price?: number | null; plu?: string | null; barcode?: string | null;
  uom?: string | null; folder?: string | null;
  serviceCharge?: boolean; tax1?: boolean; tax2?: boolean; noDiscount?: boolean; hideReceipt?: boolean;
  printers?: string | null; outlets?: string | null; outletGroup?: string | null;
}

export async function upsertMasterItems(items: MasterItemUpsertInput[]): Promise<{ inserted: number; updated: number; skipped: number }> {
  if (items.length === 0) return { inserted: 0, updated: 0, skipped: 0 };
  return withWriteLock((db) => {
    let inserted = 0, updated = 0;
    const now = nowIso();
    const chunkSize = 500;
    for (let i = 0; i < items.length; i += chunkSize) {
      const chunk = items.slice(i, i + chunkSize);
      for (const item of chunk) {
        const existing = execFirst(db, 'SELECT id FROM "MasterItem" WHERE code = ?', [item.code]);
        if (existing) {
          db.run(`UPDATE "MasterItem" SET
            active=?,name=?,category=?,department=?,salesDef=?,price=?,plu=?,barcode=?,
            uom=?,folder=?,serviceCharge=?,tax1=?,tax2=?,noDiscount=?,hideReceipt=?,
            printers=?,outlets=?,outletGroup=?,updatedAt=? WHERE code=?`,
            [item.active ? 1 : 0, item.name, item.category, item.department,
             item.salesDef ?? 'SALES', item.price ?? null, item.plu ?? null, item.barcode ?? null,
             item.uom ?? null, item.folder ?? null,
             (item.serviceCharge ?? true) ? 1 : 0, (item.tax1 ?? true) ? 1 : 0,
             (item.tax2 ?? true) ? 1 : 0, (item.noDiscount ?? true) ? 1 : 0,
             (item.hideReceipt ?? false) ? 1 : 0,
             item.printers ?? null, item.outlets ?? null, item.outletGroup ?? null, now, item.code]);
          updated++;
        } else {
          db.run(`INSERT INTO "MasterItem"
            (id,active,code,name,category,department,salesDef,price,plu,barcode,
             uom,folder,serviceCharge,tax1,tax2,noDiscount,hideReceipt,printers,outlets,outletGroup,importedAt,updatedAt)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
            [newId(), item.active ? 1 : 0, item.code, item.name, item.category, item.department,
             item.salesDef ?? 'SALES', item.price ?? null, item.plu ?? null, item.barcode ?? null,
             item.uom ?? null, item.folder ?? null,
             (item.serviceCharge ?? true) ? 1 : 0, (item.tax1 ?? true) ? 1 : 0,
             (item.tax2 ?? true) ? 1 : 0, (item.noDiscount ?? true) ? 1 : 0,
             (item.hideReceipt ?? false) ? 1 : 0,
             item.printers ?? null, item.outlets ?? null, item.outletGroup ?? null, now, now]);
          inserted++;
        }
      }
    }
    return { inserted, updated, skipped: 0 };
  });
}

export interface MasterItemUpdateInput {
  active?: boolean;
  name?: string;
  category?: string;
  department?: string;
  salesDef?: string;
  price?: number | null;
  plu?: string | null;
  barcode?: string | null;
  uom?: string | null;
  folder?: string | null;
  serviceCharge?: boolean;
  tax1?: boolean;
  tax2?: boolean;
  noDiscount?: boolean;
  hideReceipt?: boolean;
  printers?: string | null;
  outlets?: string | null;
  outletGroup?: string | null;
}

export async function getMasterItemById(id: string): Promise<DbMasterItem | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT * FROM "MasterItem" WHERE id = ? LIMIT 1', [id]);
    return row ? rowToMasterItem(row) : null;
  } catch (err) {
    console.error('[db] getMasterItemById failed:', err);
    return null;
  }
}

/**
 * Partial update of a MasterItem by id. Only the provided fields are written.
 * `code` is intentionally not updatable (it is the import key / immutable identifier).
 * Returns the updated row, or null if no item with that id exists.
 */
export async function updateMasterItem(id: string, fields: MasterItemUpdateInput): Promise<DbMasterItem | null> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "MasterItem" WHERE id = ?', [id]);
    if (!existing) return null;

    const BOOL_COLS = new Set(['active', 'serviceCharge', 'tax1', 'tax2', 'noDiscount', 'hideReceipt']);
    const ALLOWED = [
      'active', 'name', 'category', 'department', 'salesDef', 'price', 'plu', 'barcode',
      'uom', 'folder', 'serviceCharge', 'tax1', 'tax2', 'noDiscount', 'hideReceipt',
      'printers', 'outlets', 'outletGroup',
    ] as const;

    const sets: string[] = [];
    const params: unknown[] = [];
    for (const col of ALLOWED) {
      if (!(col in fields)) continue;
      const val = (fields as Record<string, unknown>)[col];
      sets.push(`${col}=?`);
      if (BOOL_COLS.has(col)) params.push(val ? 1 : 0);
      else params.push(val ?? null);
    }
    sets.push('updatedAt=?');
    params.push(nowIso(), id);
    db.run(`UPDATE "MasterItem" SET ${sets.join(',')} WHERE id=?`, params);

    const row = execFirst(db, 'SELECT * FROM "MasterItem" WHERE id = ?', [id]);
    return row ? rowToMasterItem(row) : null;
  });
}

export async function deleteMasterItem(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "MasterItem" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "MasterItem" WHERE id = ?', [id]);
    return true;
  });
}

// ── WikiArticle ───────────────────────────────────────────────────────────────

export interface DbWikiArticle {
  id: string; title: string; content: string; category: string;
  isPinned: boolean; createdBy: string; updatedBy: string | null;
  createdAt: string; updatedAt: string;
}

function rowToWikiArticle(row: Record<string, unknown>): DbWikiArticle {
  return {
    id: String(row.id), title: String(row.title), content: String(row.content),
    category: String(row.category), isPinned: normBool(row.isPinned),
    createdBy: String(row.createdBy), updatedBy: normStr(row.updatedBy),
    createdAt: String(row.createdAt), updatedAt: String(row.updatedAt),
  };
}

export async function getWikiArticles(): Promise<DbWikiArticle[]> {
  try {
    const db = await getDb();
    const rows = execAll(db, 'SELECT * FROM "WikiArticle" ORDER BY isPinned DESC, updatedAt DESC');
    return rows.map(rowToWikiArticle);
  } catch (err) {
    console.error('[db] getWikiArticles failed:', err);
    return [];
  }
}

export async function getWikiArticleById(id: string): Promise<DbWikiArticle | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT * FROM "WikiArticle" WHERE id = ? LIMIT 1', [id]);
    return row ? rowToWikiArticle(row) : null;
  } catch (err) {
    console.error('[db] getWikiArticleById failed:', err);
    return null;
  }
}

export async function createWikiArticle(data: {
  title: string; content: string; category: string; isPinned?: boolean; createdBy: string;
}): Promise<DbWikiArticle> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    db.run(`INSERT INTO "WikiArticle" (id,title,content,category,isPinned,createdBy,updatedBy,createdAt,updatedAt)
      VALUES (?,?,?,?,?,?,null,?,?)`,
      [id, data.title, data.content, data.category, (data.isPinned ?? false) ? 1 : 0, data.createdBy, now, now]);
    const row = execFirst(db, 'SELECT * FROM "WikiArticle" WHERE id = ?', [id]);
    if (!row) throw new Error('WikiArticle creation failed');
    return rowToWikiArticle(row);
  });
}

export async function updateWikiArticle(id: string, data: Partial<{
  title: string; content: string; category: string; isPinned: boolean; updatedBy: string;
}>): Promise<DbWikiArticle | null> {
  return withWriteLock((db) => {
    const sets = ['updatedAt = ?'];
    const vals: unknown[] = [nowIso()];
    if (data.title !== undefined) { sets.push('title = ?'); vals.push(data.title); }
    if (data.content !== undefined) { sets.push('content = ?'); vals.push(data.content); }
    if (data.category !== undefined) { sets.push('category = ?'); vals.push(data.category); }
    if (data.isPinned !== undefined) { sets.push('isPinned = ?'); vals.push(data.isPinned ? 1 : 0); }
    if (data.updatedBy !== undefined) { sets.push('updatedBy = ?'); vals.push(data.updatedBy); }
    vals.push(id);
    db.run(`UPDATE "WikiArticle" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "WikiArticle" WHERE id = ?', [id]);
    return row ? rowToWikiArticle(row) : null;
  });
}

export async function deleteWikiArticle(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "WikiArticle" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "WikiArticle" WHERE id = ?', [id]);
    return true;
  });
}

// ── GlossaryEntry ─────────────────────────────────────────────────────────────

export interface DbGlossaryEntry {
  id: string; type: string; term: string; definition: string;
  defaultDefinition: string | null; grp: string | null;
  isSeeded: boolean; createdAt: string; updatedAt: string;
}

function rowToGlossaryEntry(row: Record<string, unknown>): DbGlossaryEntry {
  return {
    id: String(row.id), type: String(row.type), term: String(row.term),
    definition: String(row.definition), defaultDefinition: normStr(row.defaultDefinition),
    grp: normStr(row.grp), isSeeded: normBool(row.isSeeded),
    createdAt: String(row.createdAt), updatedAt: String(row.updatedAt),
  };
}

export async function getGlossaryEntries(): Promise<DbGlossaryEntry[]> {
  try {
    const db = await getDb();
    const rows = execAll(db, 'SELECT * FROM "GlossaryEntry" ORDER BY type ASC, term ASC');
    return rows.map(rowToGlossaryEntry);
  } catch (err) {
    console.error('[db] getGlossaryEntries failed:', err);
    return [];
  }
}

export async function countGlossaryEntries(): Promise<number> {
  try {
    const db = await getDb();
    const row = execFirst(db, 'SELECT COUNT(*) as cnt FROM "GlossaryEntry"');
    return row ? Number(row.cnt) : 0;
  } catch { return 0; }
}

export async function createGlossaryEntry(data: {
  type: string; term: string; definition: string;
  grp?: string | null; isSeeded?: boolean; defaultDefinition?: string | null;
}): Promise<DbGlossaryEntry> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    db.run(`INSERT INTO "GlossaryEntry" (id,type,term,definition,defaultDefinition,grp,isSeeded,createdAt,updatedAt)
      VALUES (?,?,?,?,?,?,?,?,?)`,
      [id, data.type, data.term, data.definition, data.defaultDefinition ?? null,
       data.grp ?? null, (data.isSeeded ?? false) ? 1 : 0, now, now]);
    const row = execFirst(db, 'SELECT * FROM "GlossaryEntry" WHERE id = ?', [id]);
    if (!row) throw new Error('GlossaryEntry creation failed');
    return rowToGlossaryEntry(row);
  });
}

export async function updateGlossaryEntry(id: string, data: Partial<{
  definition: string; grp: string | null;
}>): Promise<DbGlossaryEntry | null> {
  return withWriteLock((db) => {
    const sets = ['updatedAt = ?'];
    const vals: unknown[] = [nowIso()];
    if (data.definition !== undefined) { sets.push('definition = ?'); vals.push(data.definition); }
    if ('grp' in data) { sets.push('grp = ?'); vals.push(data.grp ?? null); }
    vals.push(id);
    db.run(`UPDATE "GlossaryEntry" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "GlossaryEntry" WHERE id = ?', [id]);
    return row ? rowToGlossaryEntry(row) : null;
  });
}

export async function deleteGlossaryEntry(id: string): Promise<{ deleted: boolean; reason?: string }> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id, isSeeded FROM "GlossaryEntry" WHERE id = ?', [id]);
    if (!existing) return { deleted: false, reason: 'not_found' };
    if (normBool(existing.isSeeded)) return { deleted: false, reason: 'seeded' };
    db.run('DELETE FROM "GlossaryEntry" WHERE id = ?', [id]);
    return { deleted: true };
  });
}

export async function bulkInsertGlossaryEntries(entries: {
  type: string; term: string; definition: string; grp?: string | null; isSeeded?: boolean;
}[]): Promise<number> {
  if (entries.length === 0) return 0;
  return withWriteLock((db) => {
    const now = nowIso();
    for (const e of entries) {
      db.run(`INSERT OR IGNORE INTO "GlossaryEntry" (id,type,term,definition,defaultDefinition,grp,isSeeded,createdAt,updatedAt)
        VALUES (?,?,?,?,?,?,?,?,?)`,
        [newId(), e.type, e.term, e.definition, e.definition,
         e.grp ?? null, (e.isSeeded ?? true) ? 1 : 0, now, now]);
    }
    return entries.length;
  });
}

// ── DiscountRequest ───────────────────────────────────────────────────────────

export interface DbDiscountRequest {
  id: string;
  status: string;
  outletGroup: string;
  cashierOutlet: string;
  userId: string;
  buttonName: string;
  discountType: string;
  discountValue: number;
  discountValueType: string;
  outlets: string;
  applicableTo: string;
  conditions: string | null;
  remarks: string | null;
  adminNote: string | null;
  createdAt: string;
  updatedAt: string;
  doneAt: string | null;
}

export interface DbDiscountRequestWithUser extends DbDiscountRequest {
  submittedBy: { id: string; name: string; email: string; outlet: string };
}

export interface DiscountRequestFilters {
  status?: string;
  outletGroup?: string;
  userId?: string;
  from?: string;
  to?: string;
}

function rowToDiscountRequest(row: Record<string, unknown>): DbDiscountRequest {
  return {
    id: String(row.id),
    status: String(row.status),
    outletGroup: String(row.outletGroup),
    cashierOutlet: String(row.cashierOutlet),
    userId: String(row.userId),
    buttonName: String(row.buttonName),
    discountType: String(row.discountType),
    discountValue: Number(row.discountValue),
    discountValueType: String(row.discountValueType),
    outlets: String(row.outlets ?? ''),
    applicableTo: String(row.applicableTo),
    conditions: normStr(row.conditions),
    remarks: normStr(row.remarks),
    adminNote: normStr(row.adminNote),
    createdAt: String(row.createdAt),
    updatedAt: String(row.updatedAt),
    doneAt: normStr(row.doneAt),
  };
}

function rowToDiscountRequestWithUser(row: Record<string, unknown>): DbDiscountRequestWithUser {
  return {
    ...rowToDiscountRequest(row),
    submittedBy: {
      id: String(row.u_id ?? row.userId),
      name: String(row.u_name ?? ''),
      email: String(row.u_email ?? ''),
      outlet: String(row.u_outlet ?? ''),
    },
  };
}

export async function getDiscountRequests(filters: DiscountRequestFilters = {}): Promise<DbDiscountRequestWithUser[]> {
  try {
    const db = await getDb();
    const conditions: string[] = [];
    const params: unknown[] = [];
    if (filters.status && filters.status !== 'ALL') { conditions.push('dr.status = ?'); params.push(filters.status); }
    if (filters.outletGroup && filters.outletGroup !== 'ALL') { conditions.push('dr.outletGroup = ?'); params.push(filters.outletGroup); }
    if (filters.userId) { conditions.push('dr.userId = ?'); params.push(filters.userId); }
    if (filters.from) { conditions.push('dr.createdAt >= ?'); params.push(filters.from); }
    if (filters.to) {
      const d = new Date(filters.to); d.setHours(23, 59, 59, 999);
      conditions.push('dr.createdAt <= ?'); params.push(d.toISOString());
    }
    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
    const rows = execAll(db, `
      SELECT dr.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "DiscountRequest" dr LEFT JOIN "User" u ON dr.userId = u.id
      ${where} ORDER BY dr.createdAt DESC LIMIT 500
    `, params);
    return rows.map(rowToDiscountRequestWithUser);
  } catch (err) {
    console.error('[db] getDiscountRequests failed:', err);
    return [];
  }
}

export async function getDiscountRequestById(id: string): Promise<DbDiscountRequestWithUser | null> {
  try {
    const db = await getDb();
    const row = execFirst(db, `
      SELECT dr.*, u.id as u_id, u.name as u_name, u.email as u_email, u.outlet as u_outlet
      FROM "DiscountRequest" dr LEFT JOIN "User" u ON dr.userId = u.id
      WHERE dr.id = ? LIMIT 1
    `, [id]);
    return row ? rowToDiscountRequestWithUser(row) : null;
  } catch (err) {
    console.error('[db] getDiscountRequestById failed:', err);
    return null;
  }
}

export async function createDiscountRequest(data: {
  outletGroup: string;
  cashierOutlet: string;
  userId: string;
  buttonName: string;
  discountType: string;
  discountValue: number;
  discountValueType: string;
  applicableTo: string;
  conditions?: string | null;
  remarks?: string | null;
  outlets: string;
}): Promise<DbDiscountRequest> {
  return withWriteLock((db) => {
    const id = newId();
    const now = nowIso();
    db.run(`
      INSERT INTO "DiscountRequest"
        (id, status, outletGroup, cashierOutlet, userId, buttonName, discountType, discountValue,
         discountValueType, outlets, applicableTo, conditions, remarks, adminNote, createdAt, updatedAt, doneAt)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,null,?,?,null)
    `, [
      id, 'PENDING', data.outletGroup, data.cashierOutlet, data.userId,
      data.buttonName, data.discountType, data.discountValue,
      data.discountValueType, data.outlets,
      data.applicableTo, data.conditions ?? null, data.remarks ?? null, now, now,
    ]);
    const row = execFirst(db, 'SELECT * FROM "DiscountRequest" WHERE id = ?', [id]);
    if (!row) throw new Error('DiscountRequest creation failed');
    return rowToDiscountRequest(row);
  });
}

export async function updateDiscountRequest(id: string, data: Partial<{
  buttonName: string;
  discountType: string;
  discountValue: number;
  discountValueType: string;
  applicableTo: string;
  conditions: string | null;
  remarks: string | null;
  adminNote: string | null;
  status: string;
  doneAt: string | null;
  outlets: string;
}>): Promise<DbDiscountRequest | null> {
  return withWriteLock((db) => {
    const sets: string[] = ['updatedAt = ?'];
    const vals: unknown[] = [nowIso()];
    const strFields = [
      'buttonName', 'discountType', 'discountValueType', 'outlets', 'applicableTo',
      'conditions', 'remarks', 'adminNote', 'status', 'doneAt',
    ] as const;
    for (const f of strFields) {
      if (f in data) { sets.push(`${f} = ?`); vals.push((data as Record<string, unknown>)[f] ?? null); }
    }
    if ('discountValue' in data && data.discountValue !== undefined) { sets.push('discountValue = ?'); vals.push(data.discountValue); }
    vals.push(id);
    db.run(`UPDATE "DiscountRequest" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "DiscountRequest" WHERE id = ?', [id]);
    return row ? rowToDiscountRequest(row) : null;
  });
}

export async function deleteDiscountRequest(id: string): Promise<boolean> {
  return withWriteLock((db) => {
    const existing = execFirst(db, 'SELECT id FROM "DiscountRequest" WHERE id = ?', [id]);
    if (!existing) return false;
    db.run('DELETE FROM "DiscountRequest" WHERE id = ?', [id]);
    return true;
  });
}

// ── Config tables ─────────────────────────────────────────────────────────────

export interface DbOutletConfig {
  id: string; code: string; group: string; isActive: boolean; createdAt: string; updatedAt: string;
}
export interface DbPrinterConfig {
  id: string; name: string; group: string; isActive: boolean; createdAt: string; updatedAt: string;
}
export interface DbCategoryConfig {
  id: string; name: string; department: string; departmentCode: number; categoryCode: number;
  isActive: boolean; createdAt: string; updatedAt: string;
}

function rowToOutletConfig(row: Record<string, unknown>): DbOutletConfig {
  return { id: String(row.id), code: String(row.code), group: String(row.group),
    isActive: normBool(row.isActive), createdAt: String(row.createdAt), updatedAt: String(row.updatedAt) };
}
function rowToPrinterConfig(row: Record<string, unknown>): DbPrinterConfig {
  return { id: String(row.id), name: String(row.name), group: String(row.group),
    isActive: normBool(row.isActive), createdAt: String(row.createdAt), updatedAt: String(row.updatedAt) };
}
function rowToCategoryConfig(row: Record<string, unknown>): DbCategoryConfig {
  return { id: String(row.id), name: String(row.name), department: String(row.department),
    departmentCode: Number(row.departmentCode), categoryCode: Number(row.categoryCode),
    isActive: normBool(row.isActive), createdAt: String(row.createdAt), updatedAt: String(row.updatedAt) };
}

export async function getOutletConfigs(): Promise<DbOutletConfig[]> {
  try {
    const db = await getDb();
    return execAll(db, 'SELECT * FROM "OutletConfig" ORDER BY "group" ASC, code ASC').map(rowToOutletConfig);
  } catch (err) { console.error('[db] getOutletConfigs failed:', err); return []; }
}

export async function createOutletConfig(data: { code: string; group: string }): Promise<DbOutletConfig> {
  return withWriteLock((db) => {
    const id = newId(); const now = nowIso();
    db.run('INSERT INTO "OutletConfig" (id,code,"group",isActive,createdAt,updatedAt) VALUES (?,?,?,1,?,?)',
      [id, data.code, data.group, now, now]);
    const row = execFirst(db, 'SELECT * FROM "OutletConfig" WHERE id = ?', [id]);
    if (!row) throw new Error('OutletConfig creation failed');
    return rowToOutletConfig(row);
  });
}

export async function updateOutletConfig(id: string, data: Partial<{ code: string; group: string; isActive: boolean }>): Promise<DbOutletConfig | null> {
  return withWriteLock((db) => {
    const sets: string[] = ['updatedAt = ?']; const vals: unknown[] = [nowIso()];
    if (data.code !== undefined) { sets.push('code = ?'); vals.push(data.code); }
    if (data.group !== undefined) { sets.push('"group" = ?'); vals.push(data.group); }
    if (data.isActive !== undefined) { sets.push('isActive = ?'); vals.push(data.isActive ? 1 : 0); }
    vals.push(id);
    db.run(`UPDATE "OutletConfig" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "OutletConfig" WHERE id = ?', [id]);
    return row ? rowToOutletConfig(row) : null;
  });
}

export async function getPrinterConfigs(): Promise<DbPrinterConfig[]> {
  try {
    const db = await getDb();
    return execAll(db, 'SELECT * FROM "PrinterConfig" ORDER BY "group" ASC, name ASC').map(rowToPrinterConfig);
  } catch (err) { console.error('[db] getPrinterConfigs failed:', err); return []; }
}

export async function createPrinterConfig(data: { name: string; group: string }): Promise<DbPrinterConfig> {
  return withWriteLock((db) => {
    const id = newId(); const now = nowIso();
    db.run('INSERT INTO "PrinterConfig" (id,name,"group",isActive,createdAt,updatedAt) VALUES (?,?,?,1,?,?)',
      [id, data.name, data.group, now, now]);
    const row = execFirst(db, 'SELECT * FROM "PrinterConfig" WHERE id = ?', [id]);
    if (!row) throw new Error('PrinterConfig creation failed');
    return rowToPrinterConfig(row);
  });
}

export async function updatePrinterConfig(id: string, data: Partial<{ name: string; group: string; isActive: boolean }>): Promise<DbPrinterConfig | null> {
  return withWriteLock((db) => {
    const sets: string[] = ['updatedAt = ?']; const vals: unknown[] = [nowIso()];
    if (data.name !== undefined) { sets.push('name = ?'); vals.push(data.name); }
    if (data.group !== undefined) { sets.push('"group" = ?'); vals.push(data.group); }
    if (data.isActive !== undefined) { sets.push('isActive = ?'); vals.push(data.isActive ? 1 : 0); }
    vals.push(id);
    db.run(`UPDATE "PrinterConfig" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "PrinterConfig" WHERE id = ?', [id]);
    return row ? rowToPrinterConfig(row) : null;
  });
}

export async function getCategoryConfigs(): Promise<DbCategoryConfig[]> {
  try {
    const db = await getDb();
    return execAll(db, 'SELECT * FROM "CategoryConfig" ORDER BY departmentCode ASC, categoryCode ASC').map(rowToCategoryConfig);
  } catch (err) { console.error('[db] getCategoryConfigs failed:', err); return []; }
}

export async function createCategoryConfig(data: { name: string; department: string; departmentCode: number; categoryCode: number }): Promise<DbCategoryConfig> {
  return withWriteLock((db) => {
    const id = newId(); const now = nowIso();
    db.run('INSERT INTO "CategoryConfig" (id,name,department,departmentCode,categoryCode,isActive,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?)',
      [id, data.name, data.department, data.departmentCode, data.categoryCode, now, now]);
    const row = execFirst(db, 'SELECT * FROM "CategoryConfig" WHERE id = ?', [id]);
    if (!row) throw new Error('CategoryConfig creation failed');
    return rowToCategoryConfig(row);
  });
}

export async function updateCategoryConfig(id: string, data: Partial<{ name: string; department: string; departmentCode: number; categoryCode: number; isActive: boolean }>): Promise<DbCategoryConfig | null> {
  return withWriteLock((db) => {
    const sets: string[] = ['updatedAt = ?']; const vals: unknown[] = [nowIso()];
    if (data.name !== undefined) { sets.push('name = ?'); vals.push(data.name); }
    if (data.department !== undefined) { sets.push('department = ?'); vals.push(data.department); }
    if (data.departmentCode !== undefined) { sets.push('departmentCode = ?'); vals.push(data.departmentCode); }
    if (data.categoryCode !== undefined) { sets.push('categoryCode = ?'); vals.push(data.categoryCode); }
    if (data.isActive !== undefined) { sets.push('isActive = ?'); vals.push(data.isActive ? 1 : 0); }
    vals.push(id);
    db.run(`UPDATE "CategoryConfig" SET ${sets.join(', ')} WHERE id = ?`, vals);
    const row = execFirst(db, 'SELECT * FROM "CategoryConfig" WHERE id = ?', [id]);
    return row ? rowToCategoryConfig(row) : null;
  });
}

// ── Bulk upsert helpers for the direct seed script ───────────────────────────
// These write through sql.js (withWriteLock) so the data lands in the same
// in-memory instance the application reads from — no WAL gap.

export async function seedOutletConfigs(items: { code: string; group: string }[]): Promise<void> {
  return withWriteLock((db) => {
    const now = nowIso();
    for (const item of items) {
      const existing = execFirst(db, 'SELECT id FROM "OutletConfig" WHERE code = ?', [item.code]);
      if (existing) {
        db.run('UPDATE "OutletConfig" SET "group" = ?, updatedAt = ? WHERE code = ?', [item.group, now, item.code]);
      } else {
        db.run('INSERT INTO "OutletConfig" (id,code,"group",isActive,createdAt,updatedAt) VALUES (?,?,?,1,?,?)',
          [newId(), item.code, item.group, now, now]);
      }
    }
  });
}

export async function seedPrinterConfigs(items: { name: string; group: string }[]): Promise<void> {
  return withWriteLock((db) => {
    const now = nowIso();
    for (const item of items) {
      const existing = execFirst(db, 'SELECT id FROM "PrinterConfig" WHERE name = ?', [item.name]);
      if (existing) {
        db.run('UPDATE "PrinterConfig" SET "group" = ?, updatedAt = ? WHERE name = ?', [item.group, now, item.name]);
      } else {
        db.run('INSERT INTO "PrinterConfig" (id,name,"group",isActive,createdAt,updatedAt) VALUES (?,?,?,1,?,?)',
          [newId(), item.name, item.group, now, now]);
      }
    }
  });
}

export async function seedCategoryConfigs(
  items: { name: string; department: string; departmentCode: number; categoryCode: number }[]
): Promise<void> {
  return withWriteLock((db) => {
    const now = nowIso();
    for (const item of items) {
      const existing = execFirst(db, 'SELECT id FROM "CategoryConfig" WHERE name = ?', [item.name]);
      if (existing) {
        db.run(
          'UPDATE "CategoryConfig" SET department = ?, departmentCode = ?, categoryCode = ?, updatedAt = ? WHERE name = ?',
          [item.department, item.departmentCode, item.categoryCode, now, item.name]
        );
      } else {
        db.run(
          'INSERT INTO "CategoryConfig" (id,name,department,departmentCode,categoryCode,isActive,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?)',
          [newId(), item.name, item.department, item.departmentCode, item.categoryCode, now, now]
        );
      }
    }
  });
}
