import * as XLSX from 'xlsx';

// Constant for the 18 required headers in specific order
const EXPORT_HEADERS = [
  'Active', 'Code', 'Name', 'Category', 'Department', 'SalesDef',
  'Price', 'PLU', 'Barcode', 'UOM', 'Folder', 'ServiceCharge',
  'Tax1', 'Tax2', 'NoDiscount', 'HideReceipt', 'Printers', 'Outlets',
];

// New items XLSX adds PriceLevels placeholder after Outlets
const NEW_ITEM_HEADERS = [...EXPORT_HEADERS, 'PriceLevels'];

interface RequestRow {
  id: string;
  requestType: string;
  status: string;
  code: string | null;
  codeIsAutoGenerated?: boolean;
  name: string;
  category: string;
  department: string;
  price: number | null;
  folder: string | null;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  printers: string;
  outlets: string;
  salesDef: string;
  barcode?: string | null;
  remarks: string | null;
  cashierOutlet: string;
  outletGroup: string;
  createdAt: Date | string;
}

interface BatchItemRow extends Omit<RequestRow, 'id' | 'status' | 'requestType' | 'remarks' | 'cashierOutlet' | 'outletGroup' | 'createdAt'> {
  batchTitle: string;
}

/**
 * Updated XLSX Generator for New Items
 * Criterias: Adds 'Active' column as '1' and follows exact header order.
 */
export function generateNewItemXLSX(requests: RequestRow[]): Buffer {
  const rows = requests.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder ?? '',
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
    PriceLevels: '',
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: NEW_ITEM_HEADERS });

  // Auto-width adjustment
  ws['!cols'] = NEW_ITEM_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 }; // Name column wider

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'New Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * Updated XLSX Generator for Batch Items
 */
export function generateBatchXLSX(items: BatchItemRow[]): Buffer {
  const rows = items.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder || r.batchTitle,
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
    PriceLevels: '',
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: NEW_ITEM_HEADERS });
  ws['!cols'] = NEW_ITEM_HEADERS.map(() => ({ wch: 15 }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Batch Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * CSV Generator for Batch Items (Uses the 18 criteria headers)
 */
export function generateBatchCSV(items: BatchItemRow[]): string {
  const rows = items.map((r) => [
    '1',
    r.code ?? '',
    r.name,
    r.category,
    r.department,
    r.salesDef || '',
    r.price != null ? String(r.price) : '',
    '',
    r.barcode ?? '',
    '',
    r.folder || r.batchTitle,
    r.serviceCharge ? '1' : '0',
    r.tax1 ? '1' : '0',
    r.tax2 ? '1' : '0',
    r.noDiscount ? '1' : '0',
    r.hideReceipt ? '1' : '0',
    r.printers,
    r.outlets,
  ]);
  return [
    EXPORT_HEADERS.join(','),
    ...rows.map((row) => row.map(escapeCsv).join(',')),
  ].join('\n');
}

/**
 * CSV Generator for Single Done Requests
 */
export function generateDoneCSV(requests: RequestRow[]): string {
  const rows = requests.map((r) => [
    '1',
    r.code ?? '',
    r.name,
    r.category,
    r.department,
    r.salesDef || '',
    r.price != null ? String(r.price) : '',
    '',
    r.barcode ?? '',
    '',
    r.folder ?? '',
    r.serviceCharge ? '1' : '0',
    r.tax1 ? '1' : '0',
    r.tax2 ? '1' : '0',
    r.noDiscount ? '1' : '0',
    r.hideReceipt ? '1' : '0',
    r.printers,
    r.outlets,
  ]);

  return [
    EXPORT_HEADERS.join(','),
    ...rows.map((row) => row.map(escapeCsv).join(',')),
  ].join('\n');
}

/**
 * XLSX Generator for Done/Update requests (18-col EXPORT_HEADERS format)
 */
export function generateDoneXLSX(requests: RequestRow[]): Buffer {
  const rows = requests.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder ?? '',
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: EXPORT_HEADERS });
  ws['!cols'] = EXPORT_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 };

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Done Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * XLSX Generator for Done/Update batch items (18-col EXPORT_HEADERS format)
 */
export function generateBatchDoneXLSX(items: BatchItemRow[]): Buffer {
  const rows = items.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder || r.batchTitle,
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: EXPORT_HEADERS });
  ws['!cols'] = EXPORT_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 };

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Batch Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * UPDATE_PRICE / UPDATE_NAME exports are human-readable operational reports (not the 18-col
 * Quinos import format). Name & Category are enriched from the master item registry by the
 * route; '' when the code has no matching master item.
 */
export interface UpdateExportRow {
  code: string | null;
  masterName: string;     // existing item name from registry ('' if not found)
  masterCategory: string; // existing item category from registry ('' if not found)
  newName: string;        // requested new name (UPDATE_NAME)
  price: number | null;   // requested new price (UPDATE_PRICE)
  outlets: string;
  remarks: string | null;
  by: string;             // submitter name
  createdAt: Date | string;
  status: string;
}

const UPDATE_PRICE_HEADERS = ['Code', 'Name', 'Category', 'New Price', 'Outlets', 'Remarks', 'By', 'Date', 'Status'];
const UPDATE_NAME_HEADERS = ['Code', 'Current Name', 'New Name', 'Category', 'Outlets', 'Remarks', 'By', 'Date', 'Status'];

function formatExportDate(value: Date | string): string {
  const d = new Date(value);
  if (isNaN(d.getTime())) return '';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function generateUpdatePriceCSV(rows: UpdateExportRow[]): string {
  const body = rows.map((r) => [
    r.code ?? '', r.masterName, r.masterCategory,
    r.price != null ? String(r.price) : '',
    r.outlets, r.remarks ?? '', r.by, formatExportDate(r.createdAt), r.status,
  ]);
  return [UPDATE_PRICE_HEADERS.join(','), ...body.map((row) => row.map(escapeCsv).join(','))].join('\n');
}

export function generateUpdateNameCSV(rows: UpdateExportRow[]): string {
  const body = rows.map((r) => [
    r.code ?? '', r.masterName, r.newName, r.masterCategory,
    r.outlets, r.remarks ?? '', r.by, formatExportDate(r.createdAt), r.status,
  ]);
  return [UPDATE_NAME_HEADERS.join(','), ...body.map((row) => row.map(escapeCsv).join(','))].join('\n');
}

export function generateUpdatePriceXLSX(rows: UpdateExportRow[]): Buffer {
  const data = rows.map((r) => ({
    Code: r.code ?? '', Name: r.masterName, Category: r.masterCategory,
    'New Price': r.price ?? '', Outlets: r.outlets, Remarks: r.remarks ?? '',
    By: r.by, Date: formatExportDate(r.createdAt), Status: r.status,
  }));
  const ws = XLSX.utils.json_to_sheet(data, { header: UPDATE_PRICE_HEADERS });
  ws['!cols'] = UPDATE_PRICE_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][1] = { wch: 30 };
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Update Price');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

export function generateUpdateNameXLSX(rows: UpdateExportRow[]): Buffer {
  const data = rows.map((r) => ({
    Code: r.code ?? '', 'Current Name': r.masterName, 'New Name': r.newName,
    Category: r.masterCategory, Outlets: r.outlets, Remarks: r.remarks ?? '',
    By: r.by, Date: formatExportDate(r.createdAt), Status: r.status,
  }));
  const ws = XLSX.utils.json_to_sheet(data, { header: UPDATE_NAME_HEADERS });
  ws['!cols'] = UPDATE_NAME_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][1] = { wch: 30 };
  ws['!cols'][2] = { wch: 30 };
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Update Name');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

function escapeCsv(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}