import * as XLSX from 'xlsx';
import type { DbMasterItem } from '@/lib/db';

// Constant for the 18 required headers in specific order
const EXPORT_HEADERS = [
  'Active', 'Code', 'Name', 'Category', 'Department', 'SalesDef',
  'Price', 'PLU', 'Barcode', 'UOM', 'Folder', 'ServiceCharge',
  'Tax1', 'Tax2', 'NoDiscount', 'HideReceipt', 'Printers', 'Outlets',
];

// New items XLSX adds PriceLevels placeholder after Outlets
const NEW_ITEM_HEADERS = [...EXPORT_HEADERS, 'PriceLevels'];

interface RequestRow {
  id: string;
  requestType: string;
  status: string;
  code: string | null;
  codeIsAutoGenerated?: boolean;
  name: string;
  category: string;
  department: string;
  price: number | null;
  folder: string | null;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  printers: string;
  outlets: string;
  salesDef: string;
  barcode?: string | null;
  remarks: string | null;
  cashierOutlet: string;
  outletGroup: string;
  createdAt: Date | string;
}

interface BatchItemRow extends Omit<RequestRow, 'id' | 'status' | 'requestType' | 'remarks' | 'cashierOutlet' | 'outletGroup' | 'createdAt'> {
  batchTitle: string;
}

/**
 * Updated XLSX Generator for New Items
 * Criterias: Adds 'Active' column as '1' and follows exact header order.
 */
export function generateNewItemXLSX(requests: RequestRow[]): Buffer {
  const rows = requests.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder ?? '',
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
    PriceLevels: '',
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: NEW_ITEM_HEADERS });

  // Auto-width adjustment
  ws['!cols'] = NEW_ITEM_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 }; // Name column wider

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'New Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * Updated XLSX Generator for Batch Items
 */
export function generateBatchXLSX(items: BatchItemRow[]): Buffer {
  const rows = items.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder || r.batchTitle,
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
    PriceLevels: '',
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: NEW_ITEM_HEADERS });
  ws['!cols'] = NEW_ITEM_HEADERS.map(() => ({ wch: 15 }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Batch Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * CSV Generator for Batch Items (Uses the 18 criteria headers)
 */
export function generateBatchCSV(items: BatchItemRow[]): string {
  const rows = items.map((r) => [
    '1',
    r.code ?? '',
    r.name,
    r.category,
    r.department,
    r.salesDef || '',
    r.price != null ? String(r.price) : '',
    '',
    r.barcode ?? '',
    '',
    r.folder || r.batchTitle,
    r.serviceCharge ? '1' : '0',
    r.tax1 ? '1' : '0',
    r.tax2 ? '1' : '0',
    r.noDiscount ? '1' : '0',
    r.hideReceipt ? '1' : '0',
    r.printers,
    r.outlets,
  ]);
  return [
    EXPORT_HEADERS.join(','),
    ...rows.map((row) => row.map(escapeCsv).join(',')),
  ].join('\n');
}

/**
 * CSV Generator for Single Done Requests
 */
export function generateDoneCSV(requests: RequestRow[]): string {
  const rows = requests.map((r) => [
    '1',
    r.code ?? '',
    r.name,
    r.category,
    r.department,
    r.salesDef || '',
    r.price != null ? String(r.price) : '',
    '',
    r.barcode ?? '',
    '',
    r.folder ?? '',
    r.serviceCharge ? '1' : '0',
    r.tax1 ? '1' : '0',
    r.tax2 ? '1' : '0',
    r.noDiscount ? '1' : '0',
    r.hideReceipt ? '1' : '0',
    r.printers,
    r.outlets,
  ]);

  return [
    EXPORT_HEADERS.join(','),
    ...rows.map((row) => row.map(escapeCsv).join(',')),
  ].join('\n');
}

/**
 * XLSX Generator for Done/Update requests (18-col EXPORT_HEADERS format)
 */
export function generateDoneXLSX(requests: RequestRow[]): Buffer {
  const rows = requests.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder ?? '',
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: EXPORT_HEADERS });
  ws['!cols'] = EXPORT_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 };

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Done Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * XLSX Generator for Done/Update batch items (18-col EXPORT_HEADERS format)
 */
export function generateBatchDoneXLSX(items: BatchItemRow[]): Buffer {
  const rows = items.map((r) => ({
    Active: '1',
    Code: r.code ?? '',
    Name: r.name,
    Category: r.category,
    Department: r.department,
    SalesDef: r.salesDef || '',
    Price: r.price ?? '',
    PLU: '',
    Barcode: r.barcode ?? '',
    UOM: '',
    Folder: r.folder || r.batchTitle,
    ServiceCharge: r.serviceCharge ? 1 : 0,
    Tax1: r.tax1 ? 1 : 0,
    Tax2: r.tax2 ? 1 : 0,
    NoDiscount: r.noDiscount ? 1 : 0,
    HideReceipt: r.hideReceipt ? 1 : 0,
    Printers: r.printers,
    Outlets: r.outlets,
  }));

  const ws = XLSX.utils.json_to_sheet(rows, { header: EXPORT_HEADERS });
  ws['!cols'] = EXPORT_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][2] = { wch: 30 };

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Batch Items');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

// ── 17-column cashier import template ───────────────────────────────────────────
// NEW_ITEM and UPDATE_PRICE exports must be column-for-column identical to the system's import
// template (sheet name 'Template', no leading 'Active' column). Item attributes are sourced from
// the master item record (looked up by PLU code); the per-type mappers below decide which columns
// come from the request instead.
const TEMPLATE_HEADERS = [
  'Code', 'Name', 'Category', 'Department', 'SalesDef', 'Price', 'PLU', 'Barcode', 'UOM',
  'Folder', 'ServiceCharge', 'Tax1', 'Tax2', 'NoDiscount', 'HideReceipt', 'Printers', 'Outlets',
] as const;

export interface TemplateRow {
  Code: string; Name: string; Category: string; Department: string; SalesDef: string;
  Price: number | string; PLU: string; Barcode: string; UOM: string; Folder: string;
  ServiceCharge: number; Tax1: number; Tax2: number; NoDiscount: number; HideReceipt: number;
  Printers: string; Outlets: string;
}

// Blank only when the master genuinely has no value for the field; booleans default to 0/1.
const str = (v: string | null | undefined): string => v ?? '';
const flag = (v: boolean | null | undefined): number => (v ? 1 : 0);

// UPDATE_PRICE: every column except Price is taken from the master record (looked up by the
// request's stored PLU code). Price is the approved new price from the request. Code falls back to
// the request code so an unmatched row is still identifiable.
export function priceToTemplateRow(
  reqCode: string | null, m: DbMasterItem | undefined, newPrice: number | null,
): TemplateRow {
  return {
    Code: m?.code ?? str(reqCode), Name: str(m?.name), Category: str(m?.category),
    Department: str(m?.department), SalesDef: str(m?.salesDef), Price: newPrice ?? '',
    PLU: str(m?.plu), Barcode: str(m?.barcode), UOM: str(m?.uom), Folder: str(m?.folder),
    ServiceCharge: flag(m?.serviceCharge), Tax1: flag(m?.tax1), Tax2: flag(m?.tax2),
    NoDiscount: flag(m?.noDiscount), HideReceipt: flag(m?.hideReceipt),
    Printers: str(m?.printers), Outlets: str(m?.outlets),
  };
}

// NEW_ITEM: Code (generated, stored on the request) plus the submitted core fields
// (Name/Category/Department/Price/Printers/Outlets); the remaining attributes are enriched from the
// master record — which should exist once the item is created — looked up by the generated code.
export interface NewItemTemplateInput {
  code: string | null; name: string; category: string; department: string;
  price: number | null; printers: string; outlets: string;
}

export function newItemToTemplateRow(r: NewItemTemplateInput, m: DbMasterItem | undefined): TemplateRow {
  return {
    Code: str(r.code), Name: r.name, Category: r.category, Department: r.department,
    SalesDef: str(m?.salesDef), Price: r.price ?? '', PLU: str(m?.plu), Barcode: str(m?.barcode),
    UOM: str(m?.uom), Folder: str(m?.folder), ServiceCharge: flag(m?.serviceCharge),
    Tax1: flag(m?.tax1), Tax2: flag(m?.tax2), NoDiscount: flag(m?.noDiscount),
    HideReceipt: flag(m?.hideReceipt), Printers: r.printers, Outlets: r.outlets,
  };
}

export function generateTemplateXLSX(rows: TemplateRow[]): Buffer {
  const ws = XLSX.utils.json_to_sheet(rows, { header: [...TEMPLATE_HEADERS] });
  ws['!cols'] = TEMPLATE_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][1] = { wch: 30 }; // Name column wider
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Template');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

export function generateTemplateCSV(rows: TemplateRow[]): string {
  const body = rows.map((r) => TEMPLATE_HEADERS.map((h) => {
    const v = r[h];
    return v == null ? '' : String(v);
  }));
  return [TEMPLATE_HEADERS.join(','), ...body.map((row) => row.map(escapeCsv).join(','))].join('\n');
}

/**
 * UPDATE_NAME exports are a human-readable operational report (not the import template). Current
 * name & category are enriched from the master item registry by the route; '' when the code has no
 * matching master item.
 */
export interface UpdateExportRow {
  code: string | null;
  masterName: string;       // existing item name from registry ('' if not found)
  masterCategory: string;   // existing item category from registry ('' if not found)
  masterDepartment: string; // existing item department from registry ('' if not found)
  masterBarcode: string;    // existing item barcode from registry ('' if not found)
  newName: string;          // requested new name (UPDATE_NAME)
  price: number | null;     // requested new price (UPDATE_PRICE)
  outlets: string;
  remarks: string | null;
  by: string;               // submitter name
  createdAt: Date | string;
  status: string;
}

const UPDATE_NAME_HEADERS = ['Code', 'Current Name', 'New Name', 'Category', 'Outlets', 'Remarks', 'By', 'Date', 'Status'];

function formatExportDate(value: Date | string): string {
  const d = new Date(value);
  if (isNaN(d.getTime())) return '';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function generateUpdateNameCSV(rows: UpdateExportRow[]): string {
  const body = rows.map((r) => [
    r.code ?? '', r.masterName, r.newName, r.masterCategory,
    r.outlets, r.remarks ?? '', r.by, formatExportDate(r.createdAt), r.status,
  ]);
  return [UPDATE_NAME_HEADERS.join(','), ...body.map((row) => row.map(escapeCsv).join(','))].join('\n');
}

export function generateUpdateNameXLSX(rows: UpdateExportRow[]): Buffer {
  const data = rows.map((r) => ({
    Code: r.code ?? '', 'Current Name': r.masterName, 'New Name': r.newName,
    Category: r.masterCategory, Outlets: r.outlets, Remarks: r.remarks ?? '',
    By: r.by, Date: formatExportDate(r.createdAt), Status: r.status,
  }));
  const ws = XLSX.utils.json_to_sheet(data, { header: UPDATE_NAME_HEADERS });
  ws['!cols'] = UPDATE_NAME_HEADERS.map(() => ({ wch: 15 }));
  ws['!cols'][1] = { wch: 30 };
  ws['!cols'][2] = { wch: 30 };
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Update Name');
  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

/**
 * Identify export rows whose PLU code has no matching master item — those rows export with the
 * master-sourced template columns left blank. Logs a server-side warning and returns an encoded
 * value for the `X-Export-Warnings` response header so the admin sees which rows are incomplete
 * before the file is saved. Returns null when every row resolved cleanly.
 */
export function buildMissingMasterWarning(
  requests: { code: string | null; name: string }[],
  masterMap: Map<string, unknown>,
  logPrefix: string,
): string | null {
  const missing = requests.filter((r) => !(r.code && masterMap.has(r.code)));
  if (missing.length === 0) return null;

  console.warn(
    `${logPrefix} export: ${missing.length} row(s) without a master item match ` +
    `(master-sourced columns left blank): ${missing.map((r) => r.code ?? '(no code)').join(', ')}`,
  );

  const payload = {
    type: 'MISSING_MASTER',
    count: missing.length,
    rows: missing.slice(0, 50).map((r) => ({ code: r.code ?? '', name: r.name })),
  };
  // encodeURIComponent keeps the header value ASCII-safe (item names may contain non-Latin chars).
  return encodeURIComponent(JSON.stringify(payload));
}

function escapeCsv(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}