import { z } from 'zod';

export const createRequestSchema = z.object({
  requestType: z.enum(['NEW_ITEM', 'UPDATE_PRICE', 'UPDATE_NAME', 'UPDATE_PRINTER', 'UPDATE_FULL', 'REMOVE_PLU']),
  code: z.string().optional(),
  codeIsAutoGenerated: z.boolean().default(true),
  name: z.string(),
  category: z.string(),
  department: z.string(),
  price: z.number().min(0, 'Price must be 0 or greater').optional().nullable(),
  // Optional string fields the edit form sends as `null` when left blank (folder/barcode/remarks) —
  // must accept null, not just undefined, or a blank optional field 400s the whole request.
  folder: z.string().nullable().optional(),
  serviceCharge: z.boolean().default(true),
  tax1: z.boolean().default(true),
  tax2: z.boolean().default(true),
  noDiscount: z.boolean().default(true),
  hideReceipt: z.boolean().default(false),
  printers: z.string(),
  outlets: z.string(),
  barcode: z.string().nullable().optional(),
  salesDef: z.enum(['SALES', 'MODIFIER']).default('SALES'),
  remarks: z.string().nullable().optional(),
}).superRefine((d, ctx) => {
  if (d.requestType !== 'NEW_ITEM' && !d.code) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'PLU code is required for update requests', path: ['code'] });
  }
  if (d.requestType === 'UPDATE_PRICE' && (d.price == null || d.price <= 0)) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Harga baru harus diisi dan lebih dari 0', path: ['price'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_NAME' || d.requestType === 'UPDATE_FULL') {
    if (!d.name.trim()) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Item name is required', path: ['name'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_FULL') {
    if (!d.category) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Category is required', path: ['category'] });
    if (!d.department) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Department is required', path: ['department'] });
    if (!d.outlets) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'At least one outlet is required', path: ['outlets'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_PRINTER' || d.requestType === 'UPDATE_FULL') {
    if (!d.printers) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'At least one printer is required', path: ['printers'] });
  }
  if (d.requestType === 'REMOVE_PLU' && (!d.remarks || !d.remarks.trim())) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Alasan penghapusan harus diisi', path: ['remarks'] });
  }
});

export const updateRequestSchema = z.object({
  code: z.string().optional().nullable(),
  name: z.string().min(1).optional(),
  category: z.string().min(1).optional(),
  department: z.string().min(1).optional(),
  price: z.number().positive().optional().nullable(),
  folder: z.string().optional().nullable(),
  serviceCharge: z.boolean().optional(),
  tax1: z.boolean().optional(),
  tax2: z.boolean().optional(),
  noDiscount: z.boolean().optional(),
  hideReceipt: z.boolean().optional(),
  printers: z.string().optional(),
  outlets: z.string().optional(),
  remarks: z.string().optional().nullable(),
  adminNote: z.string().optional().nullable(),
});

// Wine List identity, additive to role. accountType 'WINE_PIC' marks the Wine Cork account;
// winePermissions ('ALL' or a semicolon-separated list) is the explicit-grant escape hatch for a
// non-WINE_PIC user who needs Wine List access. Both nullable - existing users keep null.
const accountTypeField = z.enum(['WINE_PIC']).nullable().optional();
const businessUnitField = z.string().trim().max(120).nullable().optional();
const winePermissionsField = z.string().trim().max(500).nullable().optional();

export const createUserSchema = z.object({
  email: z.string().email('Valid email required'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  name: z.string().min(1, 'Name is required'),
  role: z.enum(['CASHIER', 'ADMIN', 'COST_CONTROL']),
  outlet: z.string().min(1, 'Outlet is required'),
  accountType: accountTypeField,
  businessUnit: businessUnitField,
  winePermissions: winePermissionsField,
});

export const updateUserSchema = z.object({
  name: z.string().min(1).optional(),
  email: z.string().email().optional(),
  password: z.string().min(8).optional(),
  role: z.enum(['CASHIER', 'ADMIN', 'COST_CONTROL']).optional(),
  outlet: z.string().optional(),
  active: z.boolean().optional(),
  accountType: accountTypeField,
  businessUnit: businessUnitField,
  winePermissions: winePermissionsField,
});

// Cost Control review actions on a PENDING_COST_CONTROL NEW_ITEM request.
export const costControlConfirmSchema = z.object({
  // The barcode cost control confirmed (auto-derived value, optionally corrected). May be blank
  // if no NCK barcode applies - stored as null then.
  confirmedBarcode: z.string().trim().optional(),
});

export const costControlRejectSchema = z.object({
  reason: z.string().trim().min(1, 'Rejection reason is required'),
});

// ── Wine List module ─────────────────────────────────────────────────────────
// Field-level wine rules (required fields, vintage) live in validateWineFields() in lib/wine.ts so
// the same rule text is used by the API, the import pipeline and the form. These schemas only shape
// and coerce the payload; the routes run validateWineFields afterwards.

const wineRefId = z.string().trim().max(64).nullable().optional();
const wineText = z.string().trim().max(4000).nullable().optional();

export const wineVarietalSchema = z.object({
  varietalId: z.string().trim().min(1),
  percentage: z.number().min(0).max(100).nullable().optional(),
});

export const wineFieldsSchema = z.object({
  wineName: z.string().trim().max(300),
  displayName: z.string().trim().max(300).nullable().optional(),
  producerId: wineRefId,
  countryId: wineRefId,
  regionId: wineRefId,
  appellationId: wineRefId,
  classificationId: wineRefId,
  wineTypeId: wineRefId,
  categoryId: wineRefId,
  subCategory1Id: wineRefId,
  subCategory2Id: wineRefId,
  bottleSizeId: wineRefId,
  vintage: z.number().int().nullable().optional(),
  isNonVintage: z.boolean().default(false),
  abv: z.number().nullable().optional(),
  description: wineText,
  tastingNotes: wineText,
  foodPairing: wineText,
  servingTemperature: z.string().trim().max(120).nullable().optional(),
  internalNotes: wineText,
  costPerBottle: z.number().nullable().optional(),
  status: z.enum(['Active', 'Inactive']).default('Active'),
  varietals: z.array(wineVarietalSchema).max(20).default([]),
  legacyWineCode: z.string().trim().max(64).nullable().optional(),
  // Set by the client after the user confirms a POTENTIAL duplicate warning. Exact duplicates are
  // never overridable, whatever this says.
  acknowledgeDuplicate: z.boolean().default(false),
});

export const createWineSchema = wineFieldsSchema.extend({
  masterItemId: z.string().trim().min(1, 'Master Item wajib dipilih'),
});

// masterItemId is intentionally absent: the Master Item link is chosen once at creation. Re-pointing
// a wine at a different PLU would silently rewrite its price/barcode/outlet identity.
export const updateWineSchema = wineFieldsSchema.partial().extend({
  // Optimistic-lock token: the updatedAt the client loaded. A mismatch means a concurrent edit.
  expectedUpdatedAt: z.string().trim().optional(),
});

export const wineStatusSchema = z.object({
  status: z.enum(['Active', 'Inactive']),
  reason: z.string().trim().max(500).optional(),
});

export const publishWineRequestSchema = wineFieldsSchema.extend({
  masterItemId: z.string().trim().min(1, 'Master Item wajib dipilih'),
});

export const wineDuplicateCheckSchema = z.object({
  masterItemId: z.string().trim().nullable().optional(),
  sourceRequestId: z.string().trim().nullable().optional(),
  wineName: z.string().trim().nullable().optional(),
  producerId: z.string().trim().nullable().optional(),
  bottleSizeId: z.string().trim().nullable().optional(),
  vintage: z.number().int().nullable().optional(),
  isNonVintage: z.boolean().optional(),
  excludeWineId: z.string().trim().nullable().optional(),
});

export const wineMasterDataCreateSchema = z.object({
  name: z.string().trim().min(1, 'Nama wajib diisi').max(200),
  code: z.string().trim().max(64).nullable().optional(),
});

export const wineMasterDataUpdateSchema = z.object({
  name: z.string().trim().min(1).max(200).optional(),
  code: z.string().trim().max(64).nullable().optional(),
  status: z.enum(['Active', 'Inactive']).optional(),
});
