import { z } from 'zod';

export const createRequestSchema = z.object({
  requestType: z.enum(['NEW_ITEM', 'UPDATE_PRICE', 'UPDATE_NAME', 'UPDATE_PRINTER', 'UPDATE_FULL', 'REMOVE_PLU']),
  code: z.string().optional(),
  codeIsAutoGenerated: z.boolean().default(true),
  name: z.string(),
  category: z.string(),
  department: z.string(),
  price: z.number().min(0, 'Price must be 0 or greater').optional().nullable(),
  // Optional string fields the edit form sends as `null` when left blank (folder/barcode/remarks) —
  // must accept null, not just undefined, or a blank optional field 400s the whole request.
  folder: z.string().nullable().optional(),
  serviceCharge: z.boolean().default(true),
  tax1: z.boolean().default(true),
  tax2: z.boolean().default(true),
  noDiscount: z.boolean().default(true),
  hideReceipt: z.boolean().default(false),
  printers: z.string(),
  outlets: z.string(),
  barcode: z.string().nullable().optional(),
  salesDef: z.enum(['SALES', 'MODIFIER']).default('SALES'),
  remarks: z.string().nullable().optional(),
}).superRefine((d, ctx) => {
  if (d.requestType !== 'NEW_ITEM' && !d.code) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'PLU code is required for update requests', path: ['code'] });
  }
  if (d.requestType === 'UPDATE_PRICE' && (d.price == null || d.price <= 0)) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Harga baru harus diisi dan lebih dari 0', path: ['price'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_NAME' || d.requestType === 'UPDATE_FULL') {
    if (!d.name.trim()) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Item name is required', path: ['name'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_FULL') {
    if (!d.category) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Category is required', path: ['category'] });
    if (!d.department) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Department is required', path: ['department'] });
    if (!d.outlets) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'At least one outlet is required', path: ['outlets'] });
  }
  if (d.requestType === 'NEW_ITEM' || d.requestType === 'UPDATE_PRINTER' || d.requestType === 'UPDATE_FULL') {
    if (!d.printers) ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'At least one printer is required', path: ['printers'] });
  }
  if (d.requestType === 'REMOVE_PLU' && (!d.remarks || !d.remarks.trim())) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Alasan penghapusan harus diisi', path: ['remarks'] });
  }
});

export const updateRequestSchema = z.object({
  code: z.string().optional().nullable(),
  name: z.string().min(1).optional(),
  category: z.string().min(1).optional(),
  department: z.string().min(1).optional(),
  price: z.number().positive().optional().nullable(),
  folder: z.string().optional().nullable(),
  serviceCharge: z.boolean().optional(),
  tax1: z.boolean().optional(),
  tax2: z.boolean().optional(),
  noDiscount: z.boolean().optional(),
  hideReceipt: z.boolean().optional(),
  printers: z.string().optional(),
  outlets: z.string().optional(),
  remarks: z.string().optional().nullable(),
  adminNote: z.string().optional().nullable(),
});

export const createUserSchema = z.object({
  email: z.string().email('Valid email required'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  name: z.string().min(1, 'Name is required'),
  role: z.enum(['CASHIER', 'ADMIN', 'COST_CONTROL']),
  outlet: z.string().min(1, 'Outlet is required'),
});

export const updateUserSchema = z.object({
  name: z.string().min(1).optional(),
  email: z.string().email().optional(),
  password: z.string().min(8).optional(),
  role: z.enum(['CASHIER', 'ADMIN', 'COST_CONTROL']).optional(),
  outlet: z.string().optional(),
  active: z.boolean().optional(),
});

// Cost Control review actions on a PENDING_COST_CONTROL NEW_ITEM request.
export const costControlConfirmSchema = z.object({
  // The barcode cost control confirmed (auto-derived value, optionally corrected). May be blank
  // if no NCK barcode applies — stored as null then.
  confirmedBarcode: z.string().trim().optional(),
});

export const costControlRejectSchema = z.object({
  reason: z.string().trim().min(1, 'Rejection reason is required'),
});
