import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/session';
import { getRequestBatches, createRequestBatch, getMasterItemByCode, createPLURequest, getAllSapItemsForMatch, getMaxExistingBarcode, getBarcodeOccupancy } from '@/lib/db';
import { OUTLET_TO_GROUP } from '@/lib/outlets';
import { loadOutletPrefixMap, loadCategoryCodeMap } from '@/lib/configLoader';
import { shouldRouteToCostControl, suggestBarcode, isWineEventCategory, STATUS_PENDING_COST_CONTROL } from '@/lib/costControl';
import type { BatchItemInput } from '@/lib/db';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function GET() {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const batches = await getRequestBatches({ userId: session.user.id, limit: 200 });
    return NextResponse.json(batches);
  } catch (error) {
    console.error('[GET /api/batches]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();

    if (!body.title?.trim()) {
      return NextResponse.json({ error: 'Batch title is required' }, { status: 400 });
    }
    if (!Array.isArray(body.items) || body.items.length === 0) {
      return NextResponse.json({ error: 'At least one item is required' }, { status: 400 });
    }

    const validTypes = ['NEW_ITEM', 'UPDATE_PRICE', 'UPDATE_NAME', 'UPDATE_PRINTER', 'UPDATE_FULL', 'REMOVE_PLU'];
    const requestType = validTypes.includes(body.requestType) ? body.requestType : 'NEW_ITEM';

    if (requestType === 'NEW_ITEM') {
      const [outletPrefixMap, categoryCodeMap] = await Promise.all([
        loadOutletPrefixMap(),
        loadCategoryCodeMap(),
      ]);
      if (Object.keys(outletPrefixMap).length === 0 || Object.keys(categoryCodeMap).length === 0) {
        return NextResponse.json(
          { error: 'Konfigurasi sistem tidak tersedia. Hubungi administrator.' },
          { status: 500 }
        );
      }
    }

    const outletGroup = OUTLET_TO_GROUP[session.user.outlet] ?? 'UNION';

    const items: BatchItemInput[] = (body.items as unknown[]).map((item: unknown) => {
      const i = item as Record<string, unknown>;
      const priceRaw = i.price != null ? parseInt(String(i.price).replace(/[.,]/g, ''), 10) : null;
      return {
        code: (i.code as string | null) ?? null,
        codeIsAutoGenerated: i.codeIsAutoGenerated !== false,
        name: String(i.name ?? ''),
        category: String(i.category ?? ''),
        department: String(i.department ?? ''),
        price: priceRaw !== null && !isNaN(priceRaw) ? priceRaw : null,
        folder: (i.folder as string | null) ?? null,
        serviceCharge: i.serviceCharge !== false,
        tax1: i.tax1 !== false,
        tax2: i.tax2 !== false,
        noDiscount: i.noDiscount !== false,
        hideReceipt: i.hideReceipt === true,
        printers: Array.isArray(i.printers) ? (i.printers as string[]).join(';') : String(i.printers ?? ''),
        outlets: Array.isArray(i.outlets) ? (i.outlets as string[]).join(';') : String(i.outlets ?? ''),
        salesDef: (i.salesDef as string | undefined) ?? 'SALES',
        barcode: (i.barcode as string | null) ?? null,
        remarks: (i.remarks as string | null) ?? null,
      };
    });

    // Cost Control routing — applied PER ITEM (cork outlet + NEW_ITEM are batch-constant; the
    // WINE department varies per row). Each qualifying item is created as an INDEPENDENT
    // PENDING_COST_CONTROL single request so it surfaces in the cost-control queue (which reads
    // PLURequest); the remaining items stay in the batch and follow the normal PENDING flow.
    // Same predicate as the single-request route — no duplicated condition.
    const costControlItems = items.filter((it) =>
      shouldRouteToCostControl(requestType, it.department, session.user.outlet, it.category));
    const batchItems = items.filter((it) =>
      !shouldRouteToCostControl(requestType, it.department, session.user.outlet, it.category));

    let costControlCount = 0;
    if (costControlItems.length > 0) {
      // Load SAP refs, the current max barcode, and the persisted barcode occupancy once, then reuse
      // for every item's suggestion. `generatedBarcodes` accumulates the barcodes produced within
      // THIS batch so two items in the same POST can't be handed the same suggestion — each call
      // sees the earlier ones via extraBarcodes on top of the persisted occupancy.
      const [saps, maxBarcode, occupancy] = await Promise.all([
        getAllSapItemsForMatch(),
        getMaxExistingBarcode(),
        getBarcodeOccupancy(),
      ]);
      const generatedBarcodes: string[] = [];
      for (const it of costControlItems) {
        // Defensive: Wine Event never generates a barcode nor consumes/reserves the NCK sequence,
        // even if it somehow reaches this loop. The filter above already excludes it.
        const suggestion = isWineEventCategory(it.category)
          ? { value: null, source: null }
          : suggestBarcode(it.name, saps, maxBarcode, {
              ...occupancy,
              extraBarcodes: generatedBarcodes,
            });
        if (suggestion.value) generatedBarcodes.push(suggestion.value);
        await createPLURequest({
          requestType,
          code: it.code ?? null,
          codeIsAutoGenerated: it.codeIsAutoGenerated,
          name: it.name,
          category: it.category,
          department: it.department,
          price: it.price ?? null,
          folder: it.folder ?? null,
          serviceCharge: it.serviceCharge ?? true,
          tax1: it.tax1 ?? true,
          tax2: it.tax2 ?? true,
          noDiscount: it.noDiscount ?? true,
          hideReceipt: it.hideReceipt ?? false,
          printers: it.printers,
          outlets: it.outlets,
          barcode: isWineEventCategory(it.category)
            ? null
            : it.department === 'WINE' ? (it.barcode ?? null) : null,
          status: STATUS_PENDING_COST_CONTROL,
          suggestedBarcode: suggestion.value,
          suggestedBarcodeSource: suggestion.source,
          salesDef: it.salesDef ?? 'SALES',
          remarks: it.remarks ?? null,
          userId: session.user.id,
          outletGroup,
          cashierOutlet: session.user.outlet,
        });
        costControlCount += 1;
      }
    }

    // Only create the batch from the remaining (non-cost-control) items. A batch where every item
    // routed to cost control produces no RequestBatch.
    const batch = batchItems.length > 0
      ? await createRequestBatch(
          { title: body.title.trim(), requestType, outletGroup, cashierOutlet: session.user.outlet, userId: session.user.id },
          batchItems,
        )
      : null;

    const warnings: string[] = [];
    if (requestType === 'NEW_ITEM') {
      for (const item of items) {
        if (item.code) {
          const existing = await getMasterItemByCode(item.code);
          if (existing) {
            warnings.push(`Code ${item.code} already exists in the master registry as '${existing.name}'.`);
          }
        }
      }
    }

    return NextResponse.json(
      { ...(batch ?? {}), costControlCount, warnings: warnings.length > 0 ? warnings : undefined },
      { status: 201 },
    );
  } catch (error) {
    console.error('[POST /api/batches]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
