'use client';

import { useState, useEffect, useCallback } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { CategoryCodeEntry } from '@/lib/pluCode';
import { Combobox } from '@/components/ui/combobox';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { toast } from 'sonner';
import { Loader2, AlertTriangle } from 'lucide-react';
import { SuccessModal } from '@/components/SuccessModal';
import { PLUCodeSection } from '@/components/PLUCodeSection';
import { PLUCodeSearch } from '@/components/PLUCodeSearch';
import type { PLUSearchResult } from '@/components/PLUCodeSearch';

function formatIDR(value: number): string {
  if (!value || value === 0) return 'Rp 0';
  return 'Rp ' + value.toLocaleString('id-ID');
}

const REQUEST_TYPES = [
  { value: 'NEW_ITEM', label: 'New Item' },
  { value: 'UPDATE_PRICE', label: 'Update Price' },
  { value: 'UPDATE_NAME', label: 'Update Name' },
  { value: 'UPDATE_PRINTER', label: 'Change Printer' },
  { value: 'REMOVE_PLU', label: 'Remove PLU' },
] as const;

type RequestTypeValue = (typeof REQUEST_TYPES)[number]['value'];

interface ConfigCategory {
  id: string; name: string; department: string; departmentCode: number; categoryCode: number; isActive: boolean;
}
interface ConfigPrinter {
  id: string; name: string; group: string; isActive: boolean;
}

interface FormState {
  requestType: RequestTypeValue;
  code: string;
  codeIsAutoGenerated: boolean;
  name: string;
  category: string;
  department: string;
  price: string;
  folder: string;
  barcode: string;
  serviceCharge: boolean;
  tax1: boolean;
  tax2: boolean;
  noDiscount: boolean;
  hideReceipt: boolean;
  salesDef: 'SALES' | 'MODIFIER';
  printers: string[];
  outlets: string[];
  remarks: string;
}

const DEFAULT_FORM: FormState = {
  requestType: 'NEW_ITEM',
  code: '',
  codeIsAutoGenerated: true,
  name: '',
  category: '',
  department: '',
  price: '',
  folder: '',
  barcode: '',
  serviceCharge: true,
  tax1: true,
  tax2: true,
  noDiscount: true,
  hideReceipt: false,
  salesDef: 'SALES',
  printers: [],
  outlets: [],
  remarks: '',
};

function FieldGroup({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
      <label className="label-caps">{label}</label>
      {children}
      {hint && <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', margin: 0 }}>{hint}</p>}
    </div>
  );
}

function ConfigErrorBanner() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem', borderRadius: '0.375rem', background: 'rgba(122,46,31,0.07)', border: '1px solid rgba(122,46,31,0.2)' }}>
      <AlertTriangle size={14} style={{ color: '#8B3A2A', flexShrink: 0 }} />
      <span style={{ fontSize: '0.8rem', color: '#8B3A2A' }}>Gagal memuat data konfigurasi. Coba muat ulang halaman.</span>
    </div>
  );
}

function ConfigSkeleton() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem', borderRadius: '0.375rem', background: 'var(--bg-cream)', border: '1px solid var(--border)' }}>
      <Loader2 size={14} style={{ animation: 'spin 1s linear infinite', color: 'var(--text-secondary)', flexShrink: 0 }} />
      <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Memuat data konfigurasi…</span>
    </div>
  );
}

async function fetchWithRetry<T>(url: string): Promise<T> {
  const doFetch = async () => {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json() as Promise<T>;
  };
  try { return await doFetch(); }
  catch { return await doFetch(); }
}

export default function NewRequestPage() {
  const { data: session } = useSession();
  const router = useRouter();
  const [form, setForm] = useState<FormState>(DEFAULT_FORM);
  const [errors, setErrors] = useState<Partial<Record<keyof FormState, string>>>({});
  const [loading, setLoading] = useState(false);
  const [successModal, setSuccessModal] = useState({ open: false, itemName: '' });

  const sessionUser = session?.user as any;
  const outlet = sessionUser?.outlet ?? '';
  const outletGroup = sessionUser?.outletGroup ?? '';

  const [configCategories, setConfigCategories] = useState<ConfigCategory[]>([]);
  const [configPrinters, setConfigPrinters] = useState<ConfigPrinter[]>([]);
  const [configOutlets, setConfigOutlets] = useState<string[]>([]);
  const [configLoading, setConfigLoading] = useState(true);
  const [configError, setConfigError] = useState<string | null>(null);

  useEffect(() => {
    if (!outletGroup) return;
    setConfigLoading(true);
    setConfigError(null);
    Promise.all([
      fetchWithRetry<ConfigCategory[]>(`/api/config/categories?activeOnly=true`),
      fetchWithRetry<ConfigPrinter[]>(`/api/config/printers?group=${encodeURIComponent(outletGroup)}&activeOnly=true`),
      fetchWithRetry<{ code: string }[]>(`/api/config/outlets?group=${encodeURIComponent(outletGroup)}&activeOnly=true`),
    ])
      .then(([cats, printers, outlets]) => {
        setConfigCategories(cats);
        setConfigPrinters(printers);
        setConfigOutlets(outlets.map((o) => o.code));
      })
      .catch(() => { setConfigError('Gagal memuat data konfigurasi. Coba muat ulang halaman.'); })
      .finally(() => setConfigLoading(false));
  }, [outletGroup]);

  const categoryOptions = configCategories.map((c) => ({ value: c.name, label: c.name, group: c.department }));
  const categoryCodeMap: CategoryCodeEntry[] = configCategories.map((c) => ({
    department: c.department, departmentCode: c.departmentCode, category: c.name, categoryCode: c.categoryCode,
  }));
  const printerNames = configPrinters.map((p) => p.name);

  const isRemovePLU = form.requestType === 'REMOVE_PLU';
  const isUpdate = form.requestType !== 'NEW_ITEM';
  const showName = form.requestType === 'NEW_ITEM' || form.requestType === 'UPDATE_NAME';
  const showCategoryDept = form.requestType === 'NEW_ITEM';
  const showPrice = form.requestType === 'NEW_ITEM' || form.requestType === 'UPDATE_PRICE';
  const showFolder = form.requestType === 'NEW_ITEM';
  const showPrintersCard = form.requestType === 'NEW_ITEM' || form.requestType === 'UPDATE_PRINTER';
  const showOutletsCard = form.requestType === 'NEW_ITEM';
  const showPOSCard = form.requestType === 'NEW_ITEM';
  const showSalesDef = form.requestType === 'NEW_ITEM';

  const handlePLUCodeChange = useCallback((code: string, isAutoGenerated: boolean) => {
    setForm((f) => ({ ...f, code, codeIsAutoGenerated: isAutoGenerated }));
  }, []);

  function handlePLUSearchChange(code: string) {
    setForm((f) => ({ ...f, code, codeIsAutoGenerated: false }));
    setErrors((e) => ({ ...e, code: undefined }));
  }

  function handlePLUItemSelect(item: PLUSearchResult) {
    setForm((f) => ({ ...f, code: item.code, codeIsAutoGenerated: false, name: item.name, folder: item.folder ?? '' }));
    setErrors((e) => ({ ...e, code: undefined }));
  }

  useEffect(() => {
    if (form.category && configCategories.length > 0) {
      const dept = configCategories.find((c) => c.name === form.category)?.department ?? '';
      setForm((f) => ({ ...f, department: dept, barcode: dept !== 'WINE' ? '' : f.barcode }));
    }
  }, [form.category, configCategories]);

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((f) => ({ ...f, [key]: value }));
    setErrors((e) => ({ ...e, [key]: undefined }));
  }

  function toggleList(key: 'printers' | 'outlets', value: string) {
    setForm((f) => {
      const list = f[key];
      const next = list.includes(value) ? list.filter((v) => v !== value) : [...list, value];
      return { ...f, [key]: next };
    });
    setErrors((e) => ({ ...e, [key]: undefined }));
  }

  function validate(): boolean {
    const errs: Partial<Record<keyof FormState, string>> = {};
    if (form.requestType === 'NEW_ITEM') {
      if (!form.name.trim()) errs.name = 'Item name is required';
      if (!form.category) errs.category = 'Category is required';
      if (form.category && !form.code.trim()) errs.code = 'A PLU code is required.';
      if (form.printers.length === 0) errs.printers = 'Select at least one printer';
      if (form.outlets.length === 0) errs.outlets = 'Select at least one outlet';
    } else if (form.requestType === 'UPDATE_PRICE') {
      if (!form.code.trim()) errs.code = 'PLU code is required';
      if (!form.price || isNaN(Number(form.price)) || Number(form.price) <= 0) errs.price = 'Harga baru harus diisi dan lebih dari 0';
    } else if (form.requestType === 'UPDATE_NAME') {
      if (!form.code.trim()) errs.code = 'PLU code is required';
      if (!form.name.trim()) errs.name = 'Item name is required';
    } else if (form.requestType === 'UPDATE_PRINTER') {
      if (!form.code.trim()) errs.code = 'PLU code is required';
      if (form.printers.length === 0) errs.printers = 'Select at least one printer';
    } else if (form.requestType === 'REMOVE_PLU') {
      if (!form.code.trim()) errs.code = 'PLU code is required';
      if (!form.remarks.trim()) errs.remarks = 'Alasan penghapusan harus diisi';
    }
    setErrors(errs);
    return Object.keys(errs).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (configLoading || configError) return;
    if (!validate()) return;
    setLoading(true);
    try {
      const body = {
        requestType: form.requestType,
        code: form.code || undefined,
        codeIsAutoGenerated: form.codeIsAutoGenerated,
        name: form.name.trim() || '',
        category: form.category || '',
        department: form.department || '',
        price: form.price !== '' ? Number(form.price) : 0,
        folder: form.folder || undefined,
        serviceCharge: form.serviceCharge,
        tax1: form.tax1,
        tax2: form.tax2,
        noDiscount: form.noDiscount,
        hideReceipt: form.hideReceipt,
        printers: form.printers.join(';'),
        outlets: form.outlets.join(';'),
        barcode: form.department === 'WINE' ? form.barcode || undefined : undefined,
        salesDef: form.salesDef,
        remarks: form.remarks || undefined,
      };
      const res = await fetch('/api/requests', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error ?? 'Submission failed');
      }
      const data = await res.json();
      setSuccessModal({ open: true, itemName: data.name || form.code || 'item' });
      setForm(DEFAULT_FORM);
    } catch (err: any) {
      toast.error(err.message ?? 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <SuccessModal
        isOpen={successModal.open}
        itemName={successModal.itemName}
        onSubmitAnother={() => setSuccessModal({ open: false, itemName: '' })}
        onViewRequests={() => { setSuccessModal({ open: false, itemName: '' }); router.push('/cashier/dashboard'); }}
      />

      <h1 className="page-title" style={{ marginBottom: '0.375rem' }}>New PLU Request</h1>
      <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '1.75rem' }}>
        Submit a request to add or update a menu item in the POS system.
      </p>

      <form onSubmit={handleSubmit} style={{ maxWidth: '680px', margin: '0 auto' }}>
        {/* Request Type */}
        <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
          <div className="label-caps" style={{ marginBottom: '0.75rem' }}>Request Type</div>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            {REQUEST_TYPES.map((t) => (
              <button
                key={t.value}
                type="button"
                onClick={() => { set('requestType', t.value); setErrors({}); }}
                style={{
                  padding: '0.5rem 1rem', borderRadius: '0.375rem',
                  border: `1px solid ${form.requestType === t.value ? 'var(--bg-dark)' : 'var(--border)'}`,
                  background: form.requestType === t.value ? 'var(--bg-dark)' : 'transparent',
                  color: form.requestType === t.value ? 'var(--accent-gold)' : 'var(--text-secondary)',
                  fontSize: '0.8rem', fontWeight: form.requestType === t.value ? 500 : 400,
                  cursor: 'pointer', transition: 'all 200ms ease',
                }}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* REMOVE PLU layout */}
        {isRemovePLU && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '1.25rem' }}>Item to Remove</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <FieldGroup label="PLU Code" hint="Search or type the PLU code of the item to remove">
                <PLUCodeSearch
                  value={form.code}
                  onChange={handlePLUSearchChange}
                  onItemSelect={handlePLUItemSelect}
                  placeholder="Search PLU code..."
                  error={errors.code}
                />
                {errors.code && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.code}</p>}
              </FieldGroup>

              {form.name && (
                <FieldGroup label="Item Name">
                  <div style={{ padding: '0.5rem 0.75rem', background: 'var(--bg-cream)', borderRadius: '0.375rem', border: '1px solid var(--border)', fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                    {form.name}
                  </div>
                  <p style={{ fontSize: '0.72rem', color: 'var(--text-secondary)', margin: 0 }}>Auto-populated from master item registry</p>
                </FieldGroup>
              )}

              {form.folder && (
                <FieldGroup label="Folder">
                  <div style={{ padding: '0.5rem 0.75rem', background: 'var(--bg-cream)', borderRadius: '0.375rem', border: '1px solid var(--border)', fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                    {form.folder}
                  </div>
                </FieldGroup>
              )}

              <FieldGroup label="Alasan Penghapusan">
                <textarea
                  value={form.remarks}
                  onChange={(e) => set('remarks', e.target.value)}
                  placeholder="Jelaskan alasan penghapusan item ini..."
                  rows={3}
                  className={`flex min-h-[80px] w-full rounded-md border bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 resize-y ${errors.remarks ? 'border-red-400' : 'border-u-input'}`}
                />
                {errors.remarks && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.remarks}</p>}
              </FieldGroup>
            </div>
          </div>
        )}

        {/* Standard update layout (non-REMOVE_PLU, non-NEW_ITEM) */}
        {!isRemovePLU && isUpdate && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '1.25rem' }}>Item Details</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <FieldGroup label="PLU Code" hint="Existing POS code">
                <PLUCodeSearch
                  value={form.code}
                  onChange={handlePLUSearchChange}
                  onItemSelect={(item) => { handlePLUSearchChange(item.code); }}
                  placeholder="Search or enter PLU code..."
                  error={errors.code}
                />
                {errors.code && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.code}</p>}
              </FieldGroup>

              {showName && (
                <FieldGroup label="Item Name">
                  <input
                    type="text" value={form.name} onChange={(e) => set('name', e.target.value)}
                    placeholder="e.g. Chix Poppers"
                    className={`flex h-10 w-full rounded-md border bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 ${errors.name ? 'border-red-400' : 'border-u-input'}`}
                  />
                  {errors.name && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.name}</p>}
                </FieldGroup>
              )}

              {form.requestType === 'UPDATE_PRICE' && (
                <FieldGroup label="New Price (IDR)">
                  <input
                    type="number" value={form.price} onChange={(e) => set('price', e.target.value)}
                    placeholder="95000"
                    className={`flex h-10 w-full rounded-md border bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 ${errors.price ? 'border-red-400' : 'border-u-input'}`}
                  />
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.2rem' }}>{formatIDR(Number(form.price))}</p>
                  {errors.price && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.price}</p>}
                </FieldGroup>
              )}
            </div>
          </div>
        )}

        {/* NEW_ITEM layout */}
        {!isRemovePLU && !isUpdate && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '1.25rem' }}>Item Details</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {showName && (
                <FieldGroup label="Item Name">
                  <input
                    type="text" value={form.name} onChange={(e) => set('name', e.target.value)}
                    placeholder="e.g. Chix Poppers"
                    className={`flex h-10 w-full rounded-md border bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 ${errors.name ? 'border-red-400' : 'border-u-input'}`}
                  />
                  {errors.name && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.name}</p>}
                </FieldGroup>
              )}

              {showCategoryDept && (
                <>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                    <FieldGroup label="Category">
                      {configLoading ? <ConfigSkeleton /> : configError ? <ConfigErrorBanner /> : (
                        <Combobox options={categoryOptions} value={form.category} onChange={(v) => set('category', v)} placeholder="Select category..." searchPlaceholder="Search categories..." />
                      )}
                      {errors.category && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.category}</p>}
                    </FieldGroup>
                    <FieldGroup label="Department" hint="Auto-filled from category">
                      <input type="text" value={form.department} onChange={(e) => set('department', e.target.value)} placeholder="e.g. FOOD" className="flex h-10 w-full rounded-md border border-u-input bg-u-cream px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200" />
                    </FieldGroup>
                  </div>
                  {form.department === 'WINE' && (
                    <FieldGroup label="Barcode">
                      <input type="text" value={form.barcode} onChange={(e) => set('barcode', e.target.value)} placeholder="Enter barcode" className="flex h-10 w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200" />
                    </FieldGroup>
                  )}
                </>
              )}

              {!isUpdate && form.category && (
                <div>
                  <PLUCodeSection category={form.category} cashierOutlet={outlet} selectedOutlets={form.outlets} onValueChange={handlePLUCodeChange} categoryCodeMap={categoryCodeMap} />
                  {errors.code && <p style={{ fontSize: '0.75rem', color: '#8B3A2A', marginTop: '0.25rem' }}>{errors.code}</p>}
                </div>
              )}

              {(showPrice || showFolder) && (
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                  {showPrice && (
                    <FieldGroup label="Price (IDR)">
                      <input type="number" value={form.price} onChange={(e) => set('price', e.target.value)} placeholder="95000" className={`flex h-10 w-full rounded-md border bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 ${errors.price ? 'border-red-400' : 'border-u-input'}`} />
                      <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.2rem' }}>{formatIDR(Number(form.price))}</p>
                      {errors.price && <p style={{ fontSize: '0.75rem', color: '#8B3A2A' }}>{errors.price}</p>}
                    </FieldGroup>
                  )}
                  {showFolder && (
                    <FieldGroup label="Folder / Menu Section">
                      <input type="text" value={form.folder} onChange={(e) => set('folder', e.target.value)} placeholder="e.g. CINCO DE MAYO" className="flex h-10 w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200" />
                    </FieldGroup>
                  )}
                </div>
              )}

              {showSalesDef && (
                <FieldGroup label="SALES DEF">
                  <select value={form.salesDef} onChange={(e) => set('salesDef', e.target.value as 'SALES' | 'MODIFIER')} className="flex h-10 w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200">
                    <option value="SALES">SALES</option>
                    <option value="MODIFIER">MODIFIER</option>
                  </select>
                </FieldGroup>
              )}
            </div>
          </div>
        )}

        {/* Printers (UPDATE_PRINTER only, or NEW_ITEM) */}
        {showPrintersCard && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '0.25rem' }}>Printers</div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>Select which kitchen/bar printers should receive this item&apos;s tickets.</p>
            {configLoading ? <ConfigSkeleton /> : configError ? <ConfigErrorBanner /> : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.375rem 0.5rem' }}>
                {printerNames.map((p) => (
                  <label key={p} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', cursor: 'pointer', fontSize: '0.8rem', color: 'var(--text-primary)' }}>
                    <Checkbox checked={form.printers.includes(p)} onCheckedChange={() => toggleList('printers', p)} />
                    {p}
                  </label>
                ))}
              </div>
            )}
            {errors.printers && <p style={{ fontSize: '0.75rem', color: '#8B3A2A', marginTop: '0.5rem' }}>{errors.printers}</p>}
          </div>
        )}

        {/* Outlets */}
        {showOutletsCard && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '0.25rem' }}>Outlets</div>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>Select which outlets this item applies to.</p>
            {configLoading ? <ConfigSkeleton /> : configError ? <ConfigErrorBanner /> : (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.625rem' }}>
                {configOutlets.map((o) => (
                  <label key={o} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', cursor: 'pointer', fontSize: '0.8rem', color: 'var(--text-primary)' }}>
                    <Checkbox checked={form.outlets.includes(o)} onCheckedChange={() => toggleList('outlets', o)} />
                    {o}
                  </label>
                ))}
              </div>
            )}
            {errors.outlets && <p style={{ fontSize: '0.75rem', color: '#8B3A2A', marginTop: '0.5rem' }}>{errors.outlets}</p>}
          </div>
        )}

        {/* POS Settings */}
        {showPOSCard && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1rem' }}>
            <div className="section-title" style={{ marginBottom: '1.25rem' }}>POS Settings</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.875rem' }}>
              {([
                { key: 'serviceCharge', label: 'Service Charge' },
                { key: 'tax1', label: 'Tax 1' },
                { key: 'tax2', label: 'Tax 2' },
                { key: 'noDiscount', label: 'No Discount' },
                { key: 'hideReceipt', label: 'Hide on Receipt' },
              ] as { key: keyof FormState; label: string }[]).map(({ key, label }) => (
                <label key={key} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer', fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                  {label}
                  <Switch checked={form[key] as boolean} onCheckedChange={(v) => set(key, v as FormState[typeof key])} />
                </label>
              ))}
            </div>
          </div>
        )}

        {/* Remarks (non-REMOVE_PLU) */}
        {!isRemovePLU && (
          <div className="card" style={{ padding: '1.5rem', marginBottom: '1.5rem' }}>
            <FieldGroup label="Remarks" hint="Optional additional context for the admin.">
              <textarea
                value={form.remarks} onChange={(e) => set('remarks', e.target.value)}
                placeholder="Any additional notes..." rows={3}
                className="flex min-h-[80px] w-full rounded-md border border-u-input bg-u-card px-3 py-2 text-sm text-u-primary placeholder:text-u-secondary/60 focus:outline-none focus:ring-2 focus:ring-u-gold/40 focus:border-u-gold transition-all duration-200 resize-y"
              />
            </FieldGroup>
          </div>
        )}

        {isRemovePLU && <div style={{ marginBottom: '1.5rem' }} />}

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button
            type="submit"
            disabled={loading || configLoading || !!configError}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.625rem 1.5rem',
              background: (loading || configLoading || configError) ? 'rgba(26,16,8,0.5)' : 'var(--bg-dark)',
              color: 'var(--accent-gold)', border: 'none', borderRadius: '0.375rem',
              fontSize: '0.875rem', fontWeight: 500,
              cursor: (loading || configLoading || configError) ? 'not-allowed' : 'pointer', transition: 'all 200ms ease',
            }}
          >
            {loading && <Loader2 size={15} style={{ animation: 'spin 1s linear infinite' }} />}
            {loading ? 'Submitting…' : 'Submit Request'}
          </button>
          <button type="button" onClick={() => { setForm(DEFAULT_FORM); setErrors({}); }}
            style={{ padding: '0.625rem 1.125rem', background: 'transparent', color: 'var(--text-secondary)', border: '1px solid var(--border)', borderRadius: '0.375rem', fontSize: '0.875rem', cursor: 'pointer' }}>
            Clear Form
          </button>
        </div>
      </form>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
