import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/session';
import { getRequestBatches, getMasterMapByCodes } from '@/lib/db';
import { generateBatchDoneXLSX, generateUpdateNameXLSX, generateTemplateXLSX, priceToTemplateRow, newItemToTemplateRow, buildMissingMasterWarning, type TemplateRow, type UpdateExportRow } from '@/lib/export';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function GET(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    if (session.user.role !== 'ADMIN') return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

    const { searchParams } = new URL(request.url);
    const idsParam = searchParams.get('ids');
    const ids      = idsParam ? idsParam.split(',').filter(Boolean) : null;
    const type     = searchParams.get('type') ?? 'NEW_ITEM';

    const filters: Parameters<typeof getRequestBatches>[0] = {
      requestType: type, orderAsc: true, limit: 2000,
    };

    if (ids && ids.length > 0) {
      filters.ids = ids;
    } else {
      const group  = searchParams.get('outletGroup') ?? undefined;
      const status = searchParams.get('status') ?? undefined;
      const from   = searchParams.get('from') ?? undefined;
      const to     = searchParams.get('to') ?? undefined;
      if (group && group !== 'ALL') filters.outletGroup = group;
      if (status && status !== 'ALL') filters.status = status;
      if (from) filters.from = from;
      if (to)   filters.to   = to;
    }

    const batches = await getRequestBatches(filters);
    const dateStr  = new Date().toISOString().slice(0, 10);
    const typeLabel = type === 'NEW_ITEM' ? 'batch-new-items' : `batch-${type.toLowerCase().replace(/_/g, '-')}`;
    const filename = `${typeLabel}-${dateStr}.xlsx`;

    let buffer: Buffer;
    let warningHeader: string | null = null;
    if (type === 'UPDATE_PRICE' || type === 'NEW_ITEM') {
      // Both emit the 17-column import template. Item attributes are pulled from the master record
      // by PLU code; UPDATE_PRICE overrides only Price, NEW_ITEM keeps its submitted core fields.
      const masterMap = await getMasterMapByCodes(batches.flatMap((b) => b.items.map((i) => i.code)));
      const items = batches.flatMap((b) => b.items);
      if (items.length === 0) return NextResponse.json({ error: 'No batch items found' }, { status: 404 });
      const rows: TemplateRow[] = items.map((item) => {
        const m = item.code ? masterMap.get(item.code) : undefined;
        return type === 'UPDATE_PRICE' ? priceToTemplateRow(item.code, m, item.price) : newItemToTemplateRow(item, m);
      });
      warningHeader = buildMissingMasterWarning(
        items.map((i) => ({ code: i.code, name: i.name })), masterMap, '[GET /api/admin/export/batches/xlsx]',
      );
      buffer = generateTemplateXLSX(rows);
    } else if (type === 'UPDATE_NAME') {
      // Human-readable report (current vs new name, enriched from the registry).
      const masterMap = await getMasterMapByCodes(batches.flatMap((b) => b.items.map((i) => i.code)));
      const rows: UpdateExportRow[] = batches.flatMap((b) => b.items.map((item) => {
        const m = item.code ? masterMap.get(item.code) : undefined;
        return {
          code: item.code, masterName: m?.name ?? '', masterCategory: m?.category ?? '',
          masterDepartment: m?.department ?? '', masterBarcode: m?.barcode ?? '',
          newName: item.name, price: item.price, outlets: item.outlets, remarks: item.remarks,
          by: b.submittedBy?.name ?? '', createdAt: b.createdAt, status: b.status,
        };
      }));
      if (rows.length === 0) return NextResponse.json({ error: 'No batch items found' }, { status: 404 });
      buffer = generateUpdateNameXLSX(rows);
    } else {
      const items = batches.flatMap((b) => b.items.map((item) => ({
        batchTitle: b.title,
        code: item.code, codeIsAutoGenerated: item.codeIsAutoGenerated,
        name: item.name, category: item.category, department: item.department,
        price: item.price, folder: item.folder,
        serviceCharge: item.serviceCharge, tax1: item.tax1, tax2: item.tax2,
        noDiscount: item.noDiscount, hideReceipt: item.hideReceipt,
        printers: item.printers, outlets: item.outlets, salesDef: item.salesDef,
        barcode: item.barcode,
      })));
      if (items.length === 0) return NextResponse.json({ error: 'No batch items found' }, { status: 404 });
      buffer = generateBatchDoneXLSX(items);
    }

    const headers: Record<string, string> = {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    };
    if (warningHeader) {
      headers['X-Export-Warnings'] = warningHeader;
      headers['Access-Control-Expose-Headers'] = 'X-Export-Warnings';
    }

    return new NextResponse(new Uint8Array(buffer), { status: 200, headers });
  } catch (error) {
    console.error('[GET /api/admin/export/batches/xlsx]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
